- src/core/u-compress.c
- src/core/u-zlib.c
- src/include/sys-zlib.h
- src/tools/make-make.r
- src/tools/make-zlib.r
See notes on this PR at:
https://github.com/rebol/rebol/pull/155
More such scripts would be nice
> Add ZLIB subsetting script and update snapshots to latest (1.2.8)

- src/codecs/rsa/rsa.c
As promised those hefty changes all wrapped up for you!  (oh sneaked in a little Vim .gitignore which should be handy)
> Minor changes for OSX compilation + VIM users

- src/include/sys-int-funcs.h
- src/tools/make-make.r
> Build ren-c with clang

- src/tools/systems.r
A small assortment of minor build-related fixes. See the commit titles for an overview (and the messages for more details, where necessary).
> Miscellaneous build fixes

- src/mezz/mezz-math.r
This lets you do math evaluation with "usual" precedence rules:
>> math [1 + 2 * 3]
== 7
It also has a mode where it will merely do the transformations, which
had been called /TRANSFORM but I called /ONLY for the sake of
its representation of a simpler step (e.g. 'do math/only x' is 'math x')
>> math/only [1 + 2 * 3]
== [add 1 multiply 2 3]
Whether this is an ideal implementation or not isn't really the point.
As CC#2120 argues, having it to demonstrate shows that Rebol's
idea is to make the engine simple and predictable, so you can create
your own if you need to.  (And you usually stop wanting to.)
> Gabriele Santilli's MATH and FACTORIAL (CC#2120)

- src/core/m-gc.c
- src/core/t-routine.c
- src/core/t-struct.c
With these fixes, gtk-demos in https://github.com/zsx/c2r3/tree/master/demos/gtk-demos runs fine.
> Ren c FFI fixes

- src/boot/strings.r
- src/core/b-init.c
- src/core/l-scan.c
- src/core/l-types.c
- src/include/sys-scan.h
These are a few commits tweaking the code in the scanner, with comments and clarifications added during an attempt to understand what it is doing.
They are not intended to introduce any observable changes in behavior.
> Small scanner code audit, commenting/clarification

- src/mezz/mezz-help.r
> check for initialization of argument pat in dump-obj

- src/mezz/mezz-series.r
Motivated by a question about the limits of COLLECT by Darek Nędza,
this reframes COLLECT in terms of a basic building block COLLECT-WITH,
so `collect [...]` is the same as `collect-with keep [...]`
In addition to letting you choose a name besides KEEP for the word
that is assigned the keep function, it allows you to preserve a
*binding* by passing in a LIT-WORD!.  Doing so indicates there is
no need to deep copy or rebind the collect body inside COLLECT-WITH,
it needs only to set the variable to the collecting function.
>> my-keep: none
>> foo: func [] [
my-keep "this will get collected"
]
>> collect-with 'my-keep [foo]
== ["this will get collected"]
Using an ordinary word will go through the function-based binding and
creation of a new variable (as with the old collect).
> Add COLLECT-WITH mezzanine to specify "keeper"

- src/core/n-loop.c
This gives two new ways to specify to LOOP not to loop at all (NONE!
and FALSE), and a way to tell it to loop infinitely (TRUE).
Numbers <= 0 continue to mean "don't loop".
> LOOP accepts logic/none, infinite or no loop

- src/core/s-find.c
> Fix Compare-UTF8

- src/os/host-core.c
The internal structure of a REBSER node was changed inside the core.
An invisible dependency on the layout existed in %host-core.c, which
was exposed when certain encryption methods were used:
https://github.com/zsx/r3/blob/e95a54cb5eb7a5fc38054547879e15eddfb27bbb/src/os/host-core.c#L531
//hack! - will set the tail to key size
*((REBCNT*)(((void**)priv_key.series)+1)) = dh_ctx.len;
This was attempting to set the length of the series, by assuming that
the series length could be found one 32-bit-pointer's width inside
the data structure.  This would not have ever been true on 64-bit
systems, and is obviously a very sketchy thing to be doing...if the
internals of the data structure ever changed.
This replaces the corresponding calls with the now-exported API for
RL_SET_SERIES_LEN (although …
> Eliminate bad cast usage in HTTPS (breaking read on matrix.org)

- src/os/host-start.r
Added following to banner message on Console start:
**    Resources: system/options/resources
**    Console:   system/console/name
Console name can be one of four "states":
"default"  - Not loaded Skin-file script
"loaded"   - Skin-file script run but system/console not updated
"updated"  - Skin-file script run and system/console updated
"error"    - Skin-file produced an error
Console name can be changed by the console! object returned by %console-skin.reb (Skin-file)
The command-line --verbose switch will show more detailed Console skinning messages.
NB. Above replaces original Console skinning messages.  See comments here: https://github.com/metaeducation/ren-c/commit/012c4ae6c9ec2187cbad777fe58779996f6673fc
> Console banner changes

- src/os/host-start.r
* Replaced FAIL with DIE for all other command-line switches (see PR #501)
./r3 +s
Startup encountered an error!
** SECURE is disabled (never finished for R3-Alpha)
* Replaced FAIL with DIE in all (two) other cases in host-start (boot-embedded)
* Now dies when command-line option is missing a parameter:
$ ./r3 --resources
Startup encountered an error!
** RESOURCES parameter missing
* Fixed unknown command-line option catch.  Now also dies:
./r3 --foo
Startup encountered an error!
** Unknown command line option: --foo
!! For a full list of command-line options use:  --help
* USAGE (--help) content brought up-to-date
Along with some other minor fixes I hope above now catches all Command-line errors in a graceful way.
@hostilefork - Obviously even more could be done (see parameter checking). …
> Command-line option improvements

- CHANGES.md
- src/os/host-start.r
* Stub file for providing summary of changes
* Links to changelogs on Rebolchat.me & Github
* CHANGES console shortcut opens browser on CHANGES.md
> CHANGES.md added

- src/os/host-start.r
system/console would no longer update after a change in commit c712df7
Reverted function? to true? check to make console updates work again.
> Console skin update bug fix

- src/mezz/mezz-help.r
Minor formatting changes; HELP on DATATYPE!; Add space to HELP output on single value.
> Miscellaneous HELP changes

- .gitignore
- CHANGES.md
- CREDITS.md
- scripts/changes-file/README.md
- scripts/changes-file/changes-file.reb
- scripts/changes-file/cherry-pick-map.reb
- scripts/changes-file/make-changes-file.reb
- scripts/changes-file/template-CHANGES.md
Script to make CHANGES.md from commit log.
See `/scripts/changes-file/README.md`
> Make CHANGES.md file

- CHANGES.md
- scripts/changes-file/changes-file.reb
Hadn't noticed that these just repeated the main commit each time :(
Now shows all related links correctly following main commit :)
> Fixes CHANGES file related links

- src/mezz/mezz-help.r
- src/os/host-start.r
To see list of topics from console:
>> topics
This is a console shortcut which opens web browser at https://r3n.github.io/topics/
To see specific topic:
>> help #compiling
This opens browser at https://r3n.github.io/topics/compiling
NB. Idea and prototype by @gchiu
> * Added Help Topics

- src/mezz/mezz-files.r
- src/mezz/sys-ports.r
Is tristate really the best way? not sure, but it seems like it was like this to start with.
And it gives you a chance to check wether it was a real no, or anknown input.
> fix Confirm allow blank return, fix choices check and error message

- src/core/n-control.c
(suggestion by @draegtun)
One of the reasons for the enhanced protection on branches is the
somewhat unpredictable nature of how blocks are handled by control
constructs.  e.g.
ssd: "some string data
sbd: [some block data]
value: case [
(1 == 2) ssd
(2 == 2) sbd
]
This would give rise to an error, because it would try to run `sbd`
as code.  Being able to abstract branches in this way is important
when customizing control constructs, but dangerous when choosing data
values when "double-evaluation" wasn't intended.
For this reason, CASE/ONLY used to mean "return the value 'as-is'".
This pattern was removed, but since it is useful this factors out the
code behind CASE into a routine shared with a new native called CHOOSE,
which for the above code would return the block `[some block data]`. …
> Add new CHOOSE native as replacement for old CASE/ONLY behavior

- src/tools/make-make.r
cmdline: -h | -help | --help [TOPIC]
TOPIC: configs | options | targets | os-id | all
Help contents are gathered dynamically.
> make-make.r: add HELP

- .gitignore
- make/make-boot-ext-header.r
- make/make-boot.r
- make/make-embedded-header.r
- make/make-ext-init.r
- make/make-ext-natives.r
- make/make-headers.r
- make/make-host-ext.r
- make/make-host-init.r
- make/make-natives.r
- make/make-os-ext.r
- make/make-reb-lib.r
- make/make.r
Now all files generated during `prep` step go under `make/prep`
Next goal will be: let the user to choose build directory
> build-system: all generated files in make/prep

- src/mezz/mezz-help.r
> fix #723 dump-obj using /match and the new 'match

- .travis.yml
Build on OSX, as suggested from @hostilefork in chat.
> Travis build for Emscripten

- src/mezz/mezz-help.r
> add spaced to print collect [] in help

- make/tools/rebmake.r
This adds some header description text for %rebmake.r, and tries to
simplify a couple of things.
One is that the FILTER-FLAG function seemed to be modifying filtered
tags on an as-needed basis, rather than having the compiler flags
be their literal text.  This seems like it would add confusion for
those who are writing the tags, by adding another variable into
where the strings they're seeing would come from.  It does not seem
any tags were dependent on this "automatic" treatment, so seemingly
a feature that can be dropped.
It also transforms a delimiting pattern like:
if all [D not empty? definitions] [
unspaced [
"/D"
delimit map-each flg definitions [
opt filter-flag flg id
]
" /D"
]
]
Into the easier to understand:
if D [
spaced map-each flg definitions [
unspaced ["/D" any …
> Rebmake Simplifications

- src/mezz/mezz-series.r
> add redescribe to collect variants

- src/os/unzip.reb
> Make Unzip work for Zip Files Created via Stream

- extensions/console/ext-console-init.reb
- extensions/debugger/ext-debugger-init.reb
- make.r
- scripts/encap.reb
- src/include/sys-bind.h
- src/mezz/base-funcs.r
- src/mezz/mezz-legacy.r
- tests/datatypes/object.test.reb
- tests/functions/does.test.reb
- tools/bootstrap-shim.r
- tools/rebmake.r
The historical distinction between FUNC and FUNCTION--as well as
between METH and METHOD--was that the full word forms would look for
SET-WORD!s in the body and implicitly make those locals in the frame
(as if they had been defined as locals in the spec).
That mechanic turned out to have a lot of problems.  SET-WORD!s can
mean many things--especially when dialected.  Having all the fields
of a MAKE OBJECT! in a function body suddenly be added to the frames
would bloat them considerably.  It also tied the hands of dialects to
have to force the use of SET-WORD!s in places they might not have
wanted to...or make them avoid uses in places they would want them.
https://forum.rebol.info/t/rethinking-auto-gathered-set-word-locals/1150/
Virtual binding allows another mechanic, to add bindings …
> Begin phase out of old METHOD, use METH temporarily
