metaeducation/ren-c

.gitignore
Along with the guideline comments I've also removed the "Mac crap".
Haven't pruned anything else because thought best for you to remove (while you build your own .gitignore_global).
=> .gitignore best practice / guidelines

src/boot/natives.r, src/core/n-control.c, src/core/n-math.c, src/core/s-crc.c, src/core/s-find.c, src/core/s-unicode.c, src/include/sys-dec-to-char.h, src/mezz/base-funcs.r, src/mezz/mezz-func.r, src/mezz/mezz-help.r, src/mezz/prot-tls.r, src/os/windows/dev-event.c
This pull request incorporates all (_except one_) missing changes that were previously applied to mainline rebol/rebol but up to now missing from Atronix (and then mostly removed from Ren/C during the Atronix merge).
The following three pull requests were missing completely:
- rebol/rebol#186 (BrianHawley/fix-2109-function-local-not-at-end)
- rebol/rebol#198 (BrianHawley/wish-2121-no-return-redo)
- rebol/rebol#193 (BrianHawley/fix-2113-hash-collision)
Parts of the following six pull requests were missing (mostly just comment changes):
- rebol/rebol#185 (BrianHawley/wish-2077-no-if-else)
- rebol/rebol#167 (earl/fix-851-try-catch-quit)
- rebol/rebol#149 (ladislav/shift)
- rebol/rebol#144 (ladislav/STRTOD)
- rebol/rebol#109 (BrianHawley/wish-1973-function)
- rebol/rebol#168 …
=> Forward-port all missing changes from mainline rebol/rebol to Ren/C

src/core/f-int.c
As pointed out by hostilfork:
I'm having a problem with multiply -1 0 not working:
>> multiply -1 0
** Math error: math or number overflow
** Where: multiply
** Near: multiply -1 0
Took a look, got here. REB_U64_MUL_OF gives back p as zero which we expect, and p is an unsigned 64-bit quantity (superfluous cast). sgn is true because x is -1, and it says sgn = x < 0. So the condition on line 140 becomes:
TRUE && (u64)0 - 1 > MAX_I64
So you wind up with MAX_U64 > MAX_I64, which it is. So it returns TRUE which means Trap:
https://github.com/zsx/r3/blob/f41fb690a0f6fa3a6bbf69e6087d8afb0604494f/src/core/t-integer.c#L124
The Atronix dev download (64-bit Linux) doesn't complain, so I don't know if that's because it got compiled with builtins or something else...
=> Fix multiplication of negative and zero

src/mezz/mezz-series.r
REWORD would die with the error: `** Script error: c: word is not bound to a context`, this request adds `'c` to the list of locals.
=> Fix out-of-context word in Reword function.

src/core/a-lib.c
The same error is in a-lib2.c but it's unused anyway.
=> RL_Map_Word did not provide length to Make_Word

src/boot/natives.r, src/boot/sysobj.r, src/core/a-lib.c, src/core/n-control.c, src/mezz/mezz-files.r
This reworks and elaborates on the implementation of CASE (with
comments).  Because it winds up being a fairly radical change, it has
a switch called `broken-case-semantics` that can be turned on in
debug builds when R3_LEGACY is set in the environment, which
should give it the behavior of an old Rebol2/Rebol3.
A main change is to address [CC#2245](http://curecode.org/rebol3/ticket.rsp?id=2245), where 'case [true add 1 2]'
and 'case [false add 1 2]' have differing interpretations of the structure
of the case.  In Rebol2 they return 3 and 2 respectively, while under
this implementation they return 3 and none.
A second change is the removal of a "feature" which was to tolerate
an odd number of condition/body pairings.  In Rebol2/Rebol3 this
would run the condition and then return TRUE or …
=> New CASE with switch for legacy behavior (CC#2245)

src/boot/errors.r, src/boot/natives.r, src/boot/words.r, src/core/a-lib.c, src/core/b-init.c, src/core/c-do.c, src/core/c-error.c, src/core/c-frame.c, src/core/c-function.c, src/core/c-port.c, src/core/c-task.c, src/core/f-extension.c, src/core/l-scan.c, src/core/n-control.c, src/core/n-loop.c, src/core/n-system.c, src/core/t-object.c, src/core/t-routine.c, src/core/t-struct.c, src/core/u-dialect.c, src/core/u-parse.c, src/include/sys-core.h, src/include/sys-state.h
(Note: Should fix #41)
In the commit description for 2db2935d92 I explained how THROW
had two cases where the longjmp mechanic was used to pass a
value up the stack, instead of "bubbling up" through stacks that did
not have to explicitly initiate a setjmp state or recover from a longjmp
in order to receive the values.  The first was when PARSE needed to
"prematurely" end the parse process (through something other than a
match failure).  The second was when a QUIT was issued.
This takes away the requirement for CATCH to do a setjmp setup by
making QUIT a named throw.  Propagating that decision through
led to finding some more "swallowing" cases where THROWN values
were being ignored and not handled in any way, such as if there were
a THROW out of a MAKE of a PORT! or MODULE!.
There is a …
=> QUIT via THROW, CATCH [] vs CATCH/ANY (CC#2247)

src/boot/errors.r, src/boot/natives.r, src/boot/task.r, src/boot/words.r, src/core/a-lib.c, src/core/b-init.c, src/core/c-do.c, src/core/c-error.c, src/core/c-frame.c, src/core/c-function.c, src/core/c-port.c, src/core/c-task.c, src/core/f-extension.c, src/core/l-scan.c, src/core/m-gc.c, src/core/n-control.c, src/core/n-loop.c, src/core/n-system.c, src/core/s-mold.c, src/core/t-object.c, src/core/t-routine.c, src/core/t-struct.c, src/core/u-dialect.c, src/include/sys-value.h
Expand possible /NAME types for THROW
This is a change which unhinges the THROW and CATCH mechanics
from the implementation details of ERROR!. Keeping them separate
is good for continuing the stamping out of confusion which these
types have experienced, which helps make sure that throws don't get
dropped on the floor. But additionally the switch of THROWN() to an
options bit (that can be applied to any value) permits the /NAME of a
throw to be derived from the full spectrum of the rest of the value.
The prior limitation of name specification to a 32-bit slot inside of an
ERROR! value meant that a named throw could only have the
interpretation of that as a word symbol ID. So only unbound words
could be used as /NAMEs. This change will *mechanically* permit
any name, but currently it limits …
=> Expand possible /NAME types for THROW

src/core/c-frame.c, src/core/m-stacks.c, src/include/sys-stack.h
I knew it was possible to leak out a word from a stack relative
frame lookup and then try to look it up in a forming frame, but I
figured any code that did so would be broken and so an assert
would be good to notify people of that.  What I missed was that
the mechanics of the previous code was such that forming
frames...though positionally deeper in the stack than the frames
which would sneakily look into them...were still not considered
as candidates for stack-relative lookup.
Which is a long way of saying Rebol3 already gave an error on
cases like this, when I thought it was letting it slip:
leaker: func [/eval e /gimme g] [
either gimme [return [g]] [reduce e]
]
leaker/eval reduce leaker/gimme 10
So my assert really should have been an error, and now it is.
I'll note that it's picks up …
=> Skip stack-relative lookups in forming call frames

src/boot/errors.r, src/boot/natives.r, src/core/n-control.c, src/mezz/mezz-legacy.r
This adds the missing ability of CATCH to supply a handler, via the
/WITH refinement.  It is modeled after how TRY worked, which was
to take a BLOCK! or an ANY-FUNCTION! and be willing to take a
function that can process its args -or- one of reduced arity.  The arg
order in CATCH's case is thrown arg first, and then the throw name.
It also renames the TRY native to TRAP, because it's basically just
better in every way...but leaves TRY around for compatibility.  What
makes it better is that it doesn't have the TRY/CATCH baggage
where people will think you use it to catch throws, but also that as
a word it's less ambiguous on the fact that it evaluates to the error.
("TRAP" is more parallel to "CATCH" in that it's an action where
you expect to have a thing in your hand that was …
=> /WITH for CATCH w/handler, TRY => TRAP (+ legacy)

src/core/t-routine.c
As MT_Struct could invoke recycle, which could recycle the REBSER's in
tmp. Save it to the stack to avoid this case.
=> Save the temporary value on the stack

src/core/a-lib.c, src/core/b-init.c, src/core/c-do.c, src/core/c-error.c, src/core/c-frame.c, src/core/c-function.c, src/core/f-blocks.c, src/core/l-scan.c, src/core/n-data.c, src/core/n-loop.c, src/core/p-event.c, src/core/t-block.c, src/core/t-event.c, src/core/t-function.c, src/core/t-gob.c, src/core/t-object.c, src/core/t-routine.c, src/core/t-struct.c, src/core/t-typeset.c, src/core/t-utype.c, src/core/u-parse.c, src/include/sys-core.h, src/include/sys-value.h
In first trying to debug the binding routines, I was quickly confused by
the way the parameters were named and specified.  There would be
a routine with a name like "Bind_BlockXXX" that would take a REBVAL*
that was named block.  You would pass it a REB_BLOCK and it would
crash.  You would then see the code doing things like testing to see
if (IS_WORD(block)) and wonder what was going on.
After a while I realized that the routines were being passed pointers
to the head of a block's data series.  So the 'block' represented the
contents of the block...not a value holding the block series.
The strategy of attack I used to fix this was to give the routines a name
with the word "Array" in it, so "Bind_Array_X" instead of "Bind_Block_X".
That gives a pretty strong hint that even though you are …
=> Overhaul of binding routine names and parameters

src/core/b-init.c, src/core/c-port.c, src/core/c-word.c, src/core/m-pools.c
Rebol's wrapper for memory allocation internally is called
Make_Mem.  I've gone in and commented about why it's done
the way it is (or why I think it is, anyway).  One thing it would do
was that it would zero memory by default.
This takes that off, which brings two benefits.  One benefit is
not paying for the initialization if those zeros are just going to be
overwritten anyway.  The other more important benefit is that
it means address sanitizer and valgrind can tell you when you
are accessing uninitialized parts of an allocation...because once
it sees you've written a zero it assumes the memory is "valid".
One area where memory still has to be cleared in the current
implementation is a "Node" allocation from a series pool, when
it first creates a reusable node (but not on each reused …
=> Don't zero fill memory allocations by default

src/core/c-do.c, src/core/c-error.c, src/core/c-function.c, src/core/f-blocks.c, src/core/m-pools.c, src/core/t-routine.c, src/include/sys-core.h, src/include/sys-globals.h, src/include/sys-state.h, src/include/sys-value.h
This was a question early on, as to whether it should be the
responsibility of code using series to find a way to free the
manual series they'd allocated if an error was going to be
trapped... or if it should be handled automatically.  Handling it
automatically meant that some extra tracking would have to be
in the release build--while not handling it meant the tracking
would only be in the debug build for alerts.
The rationale for not doing it automatically was that in C code,
you cannot do a longjmp in the middle of arbitrary code and not
expect to leak resources.  There is no stack unwinding and no
destructors...so if an error traps while you've got a file open,
then you have a leaked file handle on your hands.  Given that
no general mechanism was in existence, it seemed to suggest …
=> Free extant manual series during Trap()

src/os/host-main.c
This is an extended and fixed up version of a basic line continuation handling for the default console, based on the contribution of user sqlab on StackOverflow Chat/AltME.
Fixes include buffer underruns in the continuation stack (`>> ]]]]`) and handling handling of nested braces (`>> {{}[}`).
Extensions include the handling of parens (`(` and `)`), on-demand growing the buffer the input script is built up in, preservation of end-of-line comments (`>> 1  ; foo`).
Other cleanups include no new warnings when built with `gcc -std=gnu89 -Wall -Wwrite-strings -Wno-unused-variable -Wno-maybe-uninitialized -Wno-switch`, some adjustments to use pre-existing Ren/C facilities (such as `Host_Crash`), and a first factoring of `main` (which was getting long and intermixed) into its three primary …
=> Add basic line continuation handling to the console

src/boot/natives.r, src/core/n-data.c, src/mezz/base-constants.r
This is a step toward CC#1879 moving AND, OR, and XOR to be
conditional, by providing the conditional forms of the operations
in prefix form. The baseline version of NOT was renamed to NOT?
o fit in with the group, and then aliased to NOT (since it has no
infix form).
=> Add AND? OR? XOR? NOT? operations

src/boot/natives.r, src/core/n-loop.c, src/mezz/mezz-control.r, src/mezz/mezz-legacy.r
The name EVERY is used in underscore.js for a routine that
will test a condition for every item in a series.  Although the
idea was to use EVERY as a synonym for FOR-EACH, it
seems that having a cumulative return result that's more like
ALL MAP-EACH is more useful and fitting for the name EVERY.
This adds a starter implementation for EVERY, but note that it
is subject to a quirky behavior regarding UNSET! which is to
treat it as if it were conditionally true.  That is the case for ALL
right now as well.  Both should be resolved, but that is a
separate issue.
There were also some odd numeric constants used in the
loop code, and this goes ahead and turns those into an
enumeration.
=> Differentiate EVERY return result, loop constants

src/boot/natives.r
Because comment did not get-quote its argument, it could wind
up being complicit in an evaluation.  That meant:
>> comment probe {Hello}
Hello
>> comment (probe {Hello})
Hello
>> foo: does [probe {Hello}]
>> comment foo
Hello
This makes comment quote-like, and restricts it so that it does
not quote "active" types that would create confusion even if they
were being quoted (so no parens, any-words, paths...)
>> comment (probe {Hello})
** Script error: comment does not allow paren! for its :value argument
>> comment probe {Hello}
** Script error: comment does not allow word! for its :value argument
>> foo: does [probe {Hello}]
>> comment foo
** Script error: comment does not allow word! for its :value argument
=> No execution possibility/suggestion for comment

src/boot/errors.r, src/boot/natives.r, src/core/n-control.c, src/mezz/prot-http.r, src/mezz/prot-tls.r, src/tools/common.r, src/tools/make-boot.r, src/tools/make-headers.r, src/tools/make-make.r, src/tools/make-os-ext.r, src/tools/make-zlib.r, src/tools/systems.r
The FAIL native takes the place of DO'ing an error to raise it, and
is also able to take a STRING! or a BLOCK!.  The string is sent to
MAKE ERROR! directly, while blocks are processed in a new kind of
"error creation dialect".  The dialect evaluates a WORD! as long as
it does not evaluate to a function, and also will evaluate parens:
fail ["Problem with foo:" foo "occurred at" (1 + 2)]
...this would behave equivalently to what has been written as:
do make error! form reduce [
"problem with foo:" foo "occurred at" (1 + 2)
]
Limiting types is to faciliate the dialect becoming more expressive.
It may use SET-WORD!, TAG!, and other choices to cue the fields
and formatting template structure for the error object being returned
to TRAP.  Hence those types are available for future expansion.  In …
=> Add FAIL native for raising an error or error-spec

src/boot/errors.r, src/boot/natives.r, src/boot/sysobj.r, src/core/a-lib.c, src/core/c-do.c, src/core/n-control.c, src/core/u-parse.c, src/include/sys-value.h, src/mezz/base-defs.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/sys-base.r, src/tools/common.r, src/tools/r2r3-future.r
This adds the special EVAL primitive, which will handle a value inline
however the evaluator would:
>> eval (quote x:) 10
>> print x
10
>> eval :add 10 20
== 30
What makes it special is that it is not a function that could be written
in user code, because it has an arity dictated by its argument...and
user functions have to be fixed arity.
Previously DO was the only operation that exposed the evaluator in
this special way, but it only worked with functions.  EVAL pulls that
out of DO (making it a normal function) and gives the behavior for
all data types, which localizes the specialness.
With DO more limited, it creates another divergence from R3-Alpha,
so this commit carries a tool in it with a new behavior for how DO
handles tags.  You can say `DO <r3-legacy>` and get legacy behaviors …
=> Move eval from DO to EVAL, <r3-legacy> mode

src/boot/natives.r, src/boot/sysobj.r, src/core/n-io.c, src/mezz/mezz-files.r, src/mezz/sys-base.r
This adds support for the ability to change-dir to a URL.  It does not
add support for listing the contents of URL!s...and there is no
common convention for HTML directory listings.  However there may
be something to put in port schemes for SFTP and others (even
HTTP could get plugins for scraping out data for GitHub directory lists,
or auto-generated pages by apache for servers with that enabled).
The motive for this was in particular to facilitate a DO of a URL, in
which that source has relative paths via file to `do %something.reb`.
By letting the DO of the URL put Rebol "into that path", then when
a FILE! is run it will be relative to that URL.  This way, if you have
files organized on web server paths to match the scheme you
would have them locally, it will still work.
=> CHANGE-DIR to URL, relative paths for DO of URL

src/boot/sysobj.r, src/core/a-lib.c, src/core/b-init.c, src/core/n-control.c, src/include/sys-core.h, src/include/sys-globals.h, src/mezz/mezz-legacy.r
The evolving story for how to continue running code in Ren/C
which has not been updated (either partially-or-fully) is that DO of
`<r3-legacy>` will turn back the clock and morph the behavior to act
more like an R3-Alpha.  This requires some shim code written as
Rebol functions working along with some conditional behavior in
the C code.
The idea originally was that these switches should be hidden and
very hard to get...controlled through an environment variable so
you wouldn't accidentally be running them.  But as the idea
emerged that they'd only be in debug builds, that seems like
enough of a disincentive to depend upon it without making it any
more difficult than that.
=> Legacy switches available in all debug builds

src/boot/sysobj.r, src/core/n-math.c, src/mezz/mezz-legacy.r
This updates the routine that implements the EQUAL? function to
do a coercion of datatypes into a WORD!.  (This coercion is not
applied in STRICT-EQUAL?)
>> (type? 3) = 'integer!
== true
>> (type? 3) == 'integer!
== false
Because SWITCH does not use the same function to test cases,
you can't apply this there yet...(until that change is also committed)
Also makes it clearer that Compare_Modify_Values is boolean.
=> Let DATATYPE! compare as corresponding WORD!

src/boot/errors.r, src/boot/sysobj.r, src/core/c-do.c, src/core/c-function.c, src/core/n-control.c, src/mezz/base-funcs.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/prot-tls.r
This changes it so that when a refinement is used in a function,
the value of that refinement is not #[true] but rather an unbound
WORD! which has the same symbol as the refinement itself.
If the refinement is unused, it is NONE! as before.  A legacy
mode for switching back to using TRUE is provided, but the
property will only apply to functions which were created since
the mode was turned on.
This is part (but not all) of a plan for making chaining smoother.
Another small part of this plan is included which lets you use
NONE! and GET-WORD! in refinement dispatch.  So you can
write `x: 'only` and `append/:x [a b c] [d e]` => `[a b c [d e]]`.
This is just a start, but work will be needed on path dispatch
to allow for parentheses, and just generally fixing mechanisms
so that things like …
=> Word-valued refinement variables, APPLY lockdown

src/boot/actions.r, src/boot/natives.r, src/boot/words.r, src/core/f-round.c, src/core/n-loop.c, src/core/n-sets.c, src/core/t-block.c, src/core/t-image.c, src/core/t-typeset.c, src/include/reb-c.h, src/mezz/base-defs.r, src/mezz/base-series.r, src/mezz/mezz-files.r, src/mezz/mezz-legacy.r, src/mezz/mezz-math.r, src/mezz/mezz-secure.r, src/mezz/mezz-series.r, src/tools/r2r3-future.r
When ARRAY was picked to be the general category word for BLOCK,
PATH, and GROUP...it opened up the ability to make the typeset and
type check either have an ANY- on them or not.  (It did not have that
opportunity when BLOCK was already taken for a category member.)
That opportunity landed on the side of thinking the ANY- was a good
cue for those reading the code.  It helps educate new users to realize
they are not dealing with a concrete type.  It also sort of "self-checks"
because one would not think to write MAKE ANY-ARRAY! because
that comes off as obviously nonsensical, whereas one might have a
harder time immediately processing why MAKE ARRAY! gave an
error after several ARRAY? tests seemed to work just fine, in the
context of a routine with several usable ARRAY! parameters.
This …
=> ANY- prefix for SERIES!, NUMBER!, SCALAR!

src/core/m-gc.c, src/include/sys-core.h, src/include/sys-globals.h
This is a simple way of setting a global function that takes a void
and returns a void...but can make some number of calls to mark
REBVALs for the GC.  It also adds a typeset for determining which
values need to be tracked in this way.
While by no means the final say in Rebol extensibility mechanisms,
it's enough to keep Ren/C++ and Ren Garden from crashing after
a GC happens.
=> Add very basic GC hook mechanism

src/codecs/rsa/rsa.c, src/codecs/rsa/rsa.h, src/os/host-core.c
In order to generate random numbers for the https protocol, the
"core extension" uses /dev/random on linux/posix, but on Windows
uses the platform's CryptGenRandom() API.  However, the first
parameter to CryptGenRandom() is an HCRYPTPROV ("encryption
provider") that was never initialized.
Since the uninitialized variable was global, it defaulted to 0...and it
seems that in some cases Windows is tolerant of this.  However,
linking the same code into another runtime environment (other
DLLs loaded and services used) showed it crashing.  Calling the
initializer for the encryption provider remedied the problem.
Because this code lives in the "core extension", it does not have
an include file strategy laid out for how it would use ordinary
Rebol functions.  Rather than create those dependencies …
=> Initialize encryption context that was left NULL

src/core/a-lib.c, src/core/d-print.c, src/core/p-clipboard.c, src/core/s-file.c, src/core/s-make.c, src/core/s-unicode.c, src/include/sys-core.h, src/os/host-main.c
The "len" argument of Encode_UTF8() was used as the source length on input and
as the result length on output. This caused some confusion in the calling code
about the meaning of a variable before and after the call. Now "len" is updated
to the amount of source used, and the result length is in the function return
value. The meaning of "len" argument and return value of RL_Encode_UTF8() is
changed accordingly. This change fixes bugs involving calls to Encode_UTF8().
Also, "uni" and "ccr" arguments of Encode_UTF8() and Length_As_UTF8() are
replaced with one "opts" argument. REBUNI* source is signalled by
"ENC_OPT_UNISRC" flag, and CRLF handling is signalled by "ENC_OPT_CRLF" flag.
Make_UTF8_Binary() helper function is added that calls Length_As_UTF8(),
Make_Binary(), Encode_UTF8().
=> (via @meshpoint) Change Encode_UTF8 API

src/boot/actions.r, src/boot/booters.r, src/boot/natives.r, src/boot/words.r, src/core/n-data.c, src/core/t-image.c, src/core/t-typeset.c, src/mezz/base-debug.r, src/mezz/base-defs.r, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/prot-tls.r, src/tools/r2r3-future.r
There is an ambiguity inherent when types themselves are values
in the language, and you say "ANY-TYPE".  The problem is that may
suggest something more narrow than what has been meant, which
historically is that ANY-TYPE meant "any legal Rebol value" (and that
included UNSET!, when UNSET! was a legal Rebol value, which it is
now planned to not be).
Renaming it to ANY-VALUE! clears up the problem, so you don't think
it suggests it could be "any type", e.g. STRING! or INTEGER! etc.
ANY-TYPE! added to legacy for backward compatibilty.
=> ANY-TYPE! => ANY-VALUE!

src/core/b-init.c, src/core/c-error.c, src/core/f-series.c, src/include/sys-value.h
At one point in time, ERROR! objects did double duty as the value
type for THROWN() values generated for function returns and
similar.  The error then contained a number identifying the throw
and a possible argument.
With the desire to allow a "full value's worth" of value to /NAME a
throw, the THROWN() convention was changed to a header bit that
could be set on any value type.  This meant all errors were changed
to have "object frames" and be ordinary objects which could be
handed to the user (with two exceptions: halt and a parse hack).
This commit started as comment maintenance but then shifted to
merging ERROR! in to be in the same form as PORT!, MODULE!,
and OBJECT! which share a common REBVAL structure.  (This
is similar to how series values like BLOCK! and STRING! and
PAREN! and …
=> ERROR => same struct as OBJECT/PORT/MODULE

src/boot/sysobj.r, src/core/t-integer.c, src/mezz/mezz-legacy.r
This was motivated by discovery that Rebol3's CRC32 hash values
are returned as signed quantities.  When reading a 32-bit CRC out
of the zip container as bytes, using TO-INTEGER on it would extend
it to a 64-bit quantity which was never signed...leading to a difference
of comparison.
Using logic based on a previous futureproofing proposal from...
someone, this does not interpret to-integer #{FFFFFFFF} in Ren/C as
#{00000000FFFFFFFF} but rather #{FFFFFFFFFFFFFFF}.  It will
effectively extend the bytes to the left to make a 64-bit number based
on the high bit of the most significant big-endian byte of the input.
If a 4-byte number coming from Rebol2's TO-BINARY of an integer is
read then it will be compatible, and if an 8-byte number coming from
Rebol3's TO-BINARY of an integer is read then …
=> Differentiate 4-byte/8-byte binary-to-int process

src/boot/natives.r, src/core/l-scan.c, src/core/l-types.c, src/core/s-ops.c, src/core/t-decimal.c, src/core/t-integer.c, src/mezz/mezz-types.r
This factors out the functionality of INTEGER!'s TO conversion into
a service function, and then adds a parameter to that function for
enforcing interpretation to be unsigned.  Then it creates a NATIVE!
version of TO-INTEGER! which provides an /UNSIGNED refinement
to use the new ability.
It also fixes a bug in the TO INTEGER! implementation for numbers
(introduced in fea5921).  The problem would occur when leading 0xFF
bytes were followed by a byte without the high bit set.  This would
lead to positive interpretations of those numbers.
Several other adjustments were made to correct edge cases or add
informative errors for surprising results.  As a by-product of writing the
routine for general purposes, it can generate a REBI64 directly into a
value cell or into a REBI64 without a value …
=> TO-INTEGER/UNSIGNED and conversion fixes

src/boot/sysobj.r, src/core/d-print.c, src/core/n-io.c, src/mezz/mezz-legacy.r
An issue discovered regarding Rebol's limitations of interacting in a
web CGI environment is that it has no way to do full 8-bit transport to
the console.  Unlike WRITE, PRINT of a binary would not send the
raw bytes to the device but rather do an effective PROBE of the data.
The general idea that a PRINT of a value is a general-purpose way
of inspecting any arbitrary Rebol type is already undermined by its
longstanding behavior with BLOCK!.  Hence, in order to make it
possible to access things like terminal escape codes and other needs
it makes more sense to treat printing of a binary in a way that gives
full raw access to the device.
(This does not change the behavior of BINARY! inside of a block that
is passed to PRINT, which is currently the domain of FORM.)
This adds another behavior …
=> Print BINARY! as raw bytes to console, skip NONE!

src/boot/errors.r, src/core/l-scan.c, src/core/s-crc.c, src/core/s-find.c, src/core/s-unicode.c, src/core/t-char.c
This is a rescue of some tinkering from before Ren/C in a mostly
irrelevant clone.  It seemed to be clarifying enough to be worth going
ahead and trying to merge in before throwing that repository away.
The interface of Decode_UTF8_Char and its callers was complex
and obscured the need to handle certain invalid return results.  Some
places did not check the result and shouldn't have to.  This makes it
more standardized by matching the Scan_XXX routines more
closely.  It also adds documentation for the behavior.
A special error is also added to help distinguish invalid UTF8 data
from one with a codepoint simply too high for the Rebol implementation
to currently handle.
A likely redundant check is moved for now to assert that the redundant
check matches the result if the check is not run.
=> Tighten/clarify UTF8 char decoding interfaces

src/boot/errors.r, src/boot/sysobj.r, src/core/n-control.c, src/mezz/mezz-legacy.r
When FAIL was conceived, it seemed that letting DO raise errors was
encouraging of unclear practices.  (DO X doesn't look like a failure or
exception triggering mechanism if you don't know that X is an error, and
it's not that great of a way of saying it even if it's clear that it is an error.)
So DO of an ERROR! was turned into a different error than the one you
asked for...instructing you to use FAIL instead.
This was creating a bit of a bump, and likely an unnecessary one.  If DO
of an ERROR! is just going to give you an error anyway, it might as well
give the error you asked for.
However, THROW not allowing you to pass it an ERROR! is important and
being kept.  If THROW is used instead of FAIL (or DO) then it will confuse
matters with TRAP, making it seem surprising that a thrown …
=> Permit DO to raise errors again

src/core/a-lib.c, src/core/c-do.c, src/core/c-error.c, src/core/c-function.c, src/core/d-dump.c, src/core/d-print.c, src/core/m-gc.c, src/core/m-pools.c, src/core/n-io.c, src/core/n-loop.c, src/core/t-routine.c, src/core/u-parse.c, src/include/sys-core.h, src/include/sys-globals.h, src/include/sys-state.h
In order to protect a series from being garbage collected in a way that was
efficient and safe for recursively protecting and unprotecting the same
series, the SAVE_SERIES and UNSAVE_SERIES macros existed.  They
used a stack to efficiently save and release the pointers, as well as to
check in the debug build to make sure the last saved series was the next
to be unsaved.
No parallel way of saving a value existed, perhaps because most values
live in series.  (You don't want to hold onto pointers to them because the
series can have their data arrays moved during reallocation.)  However, if
a value is known to live in stable memory it could use the same technique
to keep any series it references protected from GC (as long as it is, actually
stable).
Because no mechanism existed, it was …
=> Add "SAVE/UNSAVE_VALUE" (rename to GUARD...)

src/boot/errors.r, src/boot/root.r, src/core/a-lib.c, src/core/b-init.c, src/core/c-error.c, src/core/c-function.c, src/core/m-gc.c, src/core/n-control.c, src/core/n-loop.c, src/core/n-system.c, src/core/u-parse.c, src/include/sys-value.h
Rebol uses C's precarious longjmp construct to implement error
handling, because it wants to (for instance) not have to add a check
after every memory allocation to determine if it failed...and then have
to gracefully find a way to move an error into its returning slot.
In PARSE's C implementation, it was using the error longjmp in a
hacky way in order to proxy out return results or throws from within an
embedded rule.  No error had actually occurred... it just was somewhat
deep into a stack and did not have a return result to indicate a throw
had happened.  Rather than adding the result, it pretended an error
occurred and "jumped the stack".
There are several reasons not to do this, including the unnecessary set
up and tear down of a setjmp/longjmp state on each parse call.  It also …
=> Kill parse longjmp hack, native THROW/NAMEs

src/boot/natives.r, src/boot/sysobj.r, src/core/n-control.c, src/core/n-loop.c, src/include/sys-value.h, src/mezz/mezz-legacy.r
This commit adds a /WITH refinement to CONTINUE, such that it
will skip the rest of the loop body but still act like it had returned the
value it is passed:
>> map-each x [1 2 3] [continue/with 4 "foo"]
== [4 4 4]
This also reconciles the behavior of /WITH for BREAK in a similar
way, so that it will effectively make the body return that value for the
last iteration.  This leads to a concrete difference from /RETURN
which did not have the intention (and would not make sense to put
onto continue).
For more explanation and why /RETURN is not being kept around
(instead suggesting people use CATCH+THROW), see porting guide:
https://trello.com/c/cOgdiOAD
An `<r3-legacy>` switch is added for making /WITH act with the old
behavior of /RETURN, which is used as a synonym...however the
two behaviors …
=> Add CONTINUE/WITH, modify BREAK/WITH, cleanup

src/core/b-init.c, src/core/c-do.c, src/core/c-error.c, src/core/c-function.c, src/core/c-port.c, src/core/f-extension.c, src/core/m-gc.c, src/core/n-control.c, src/core/n-data.c, src/core/n-io.c, src/core/n-loop.c, src/core/n-strings.c, src/core/n-system.c, src/core/t-gob.c, src/core/t-object.c, src/core/t-struct.c, src/core/u-parse.c, src/include/sys-value.h
Rebol has two methods of interrupting control: errors and throws.
The error mechanism makes use of setjmp/longjmp and must be
explicitly caught by certain stack levels, but a thrown value can be
passed back as a return value from any call into the evaluator and
needs to have some kind of handling at each evaluator call site...
either to catch it, to bubble it up through the next return result, or
to raise an error on it.
Despite the importance of each call into the evaluator having
explicit handling for throws, there was a tendency in the original code
to often forget to handle it.  It has been an ongoing process to give
routines names (like XXX_Throws()) to signal that the caller must
be responsible for triaging a throw.
The elimination of the "parse longjmp hack" facilitated the …
=> Codebase-wide THROWN() audit, plus checks

src/boot/natives.r, src/core/n-control.c, src/core/n-loop.c, src/include/sys-value.h
This change makes ANY and ALL safer to use generically in places
that expect to use the value, such as IF ANY ... or UNLESS ALL ...
Summary on the porting guide:
https://trello.com/c/wyXCkx67/
=> Unsets "no vote" for ALL and ANY, won't return them

src/boot/errors.r, src/boot/natives.r, src/core/c-frame.c, src/core/n-data.c, src/core/n-system.c
Previously `unset unbind 'foo` would silently return an unset instead
of notifying you.  It was silent about other errors as well, e.g. you could
write unset [1 2 3] and not alert you.  You could also not unset other word
types (you can with SET if they are bound).
This adds in the missing errors and allows you to unset other word types.
It also renames the "unbound" error message constant to being not-bound
instead of the vaguer "not-defined"
=> #2219 UNSET of an unbound word gives an error

src/boot/natives.r, src/boot/sysobj.r, src/core/c-do.c, src/core/n-control.c, src/core/n-loop.c, src/include/sys-value.h, src/mezz/base-files.r, src/mezz/mezz-legacy.r, src/mezz/mezz-math.r, src/mezz/sys-load.r, src/mezz/sys-start.r, src/tools/common-parsers.r
**WARNING** this change can cause subtle bugs in previous
patterns of the form:
all [1 (if 1 > 2 [3]) 4]
While ALL always considered unsets a method for "opting out" of
the vote and not causing a test to fail, failing IF's NONE *would*
cause a test to fail.  New patterns of thinking a condition failing means
a 'void' or absence of data instead of a chainable "falsity" is a cool
interpretation--and worth the change systemically.  However, such
code will need to be ported to something more like:
all [1 all [(1 > 2) 3] 4]
Or even more elegantly flattened to:
all [1 (1 > 2) 3 4]
The option to switch to EITHER with NONE also exists, or to
experiment with the new RELAX native.
`<r3-legacy>` has the added switches:
none-instead-of-unsets: false
cant-unset-set-words: false
=> Default IF, WHILE, EVERY to unsets, x: () legal

src/boot/root.r, src/boot/sysobj.r, src/boot/words.r, src/core/b-init.c, src/core/c-error.c, src/core/c-frame.c, src/core/c-function.c, src/core/f-extension.c, src/core/m-stacks.c, src/core/n-control.c, src/core/n-data.c, src/core/s-mold.c, src/core/t-function.c, src/include/sys-value.h, src/mezz/base-funcs.r, src/mezz/mezz-legacy.r
You heard it here first.  The console says it all... ;-P
>> foo: func [x] [return x 20]
== make function! [[x /local return][
return: make function! [
["Returns a value from a function." value [any-value!]]
[throw/name value bind-of 'return]
]
catch/name [
return x 20
] bind-of 'return
]]
>> foo 10
== 10
If you do not wish to have your function bind or provide a definitional return use
`<transparent>`:
>> bar: func [<transparent> y] [return y 304]
== make function! [[y][return y 304]]
>> bar 1020
** User error: {RETURN called--but no function generator providing it in use}
...of course, the console does NOT tell the whole story.  The code may not either
but there are a lot of comments.  Blog posts and videos forthcoming.
Happy Halloween 2015... and Ren/C'ing is Ren/beliving...
=> Definitional Returns. Solved.

src/mezz/base-funcs.r, src/mezz/mezz-control.r, src/mezz/mezz-debug.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/sys-base.r
The original implementation of `<transparent>` was fairly trivial, and it
often marked cases of functions that would **do code** where the code
passed in was foreign.  So they weren't where the buck stopped with
a return, rather it would continue to the caller.
*That usage* of transparent is no longer interesting or necessary...a
passed in RETURN living inside of CODE knows its binding and where
to go.  But there are cases where <transparent> is actually needed, for
instance where instead of DO-ing foreign code you are using that code
as the body of a function as part of your implementation.
Two good case studies of this are USE and COLLECT.  And COLLECT
is such a good case study of the Zen of language extension using Rebol
that now that it's working, I wanted to clean it all the way up. …
=> Remove wasted transparents, COLLECT beautify

src/boot/root.r, src/boot/sysobj.r, src/boot/words.r, src/core/b-init.c, src/core/c-do.c, src/core/c-function.c, src/core/m-stacks.c
While implementing the native FUNC and CLOS generators and
needing to work with adding locals, it became apparent that finding
and managing the relationship with /LOCAL was unnecessary overhead.
It also brought another instance of a "special" word into the system...
at the same time it was ensuring RETURN was not special.
(For the record, there was no SYM_LOCAL reference internally prior
to the definitional return work...so it had to introduce it.)
With definitional returns finished, this takes a step back on that and adds
a more useful feature.  SET-WORD! in function specs are "true locals".
This means that they will be bound and will be in the function frame, but
will be invisible to and un-injectable by the outside world.  They will not
appear in WORDS-OF or other outside inspections. …
=> SET-WORD! in func spec are "true locals", permit RETURN:

src/boot/natives.r, src/core/n-strings.c
This adds the SPELLING-OF native from the rebol-proposals repository.
It works on ANY-STRING! or ANY-WORD!, and extracts the "pre-formed"
string data from them:
>> spelling-of <abc>
"abc"
>> spelling-of quote def:
"def"
>> spelling-of "ghi"
"ghi"
Very easy to write as a native, somewhat harder to engineer from outside
the system (especially as Rebol2 would to-string on a SET-WORD! as
the spelling, while R3-Alpha had the delimiter...)
=> SPELLING-OF as native function

src/boot/sysobj.r, src/boot/words.r, src/core/n-math.c, src/core/t-datatype.c, src/core/t-word.c, src/mezz/base-constants.r, src/mezz/mezz-legacy.r
These commits reverse the feature addition of the ability to compare datatypes and words as non-strict equal, e.g. `type-of 3 = 'integer!`.  That feature suggested mostly to support matches in switch:
switch type-of 3 [
integer! [print "people wanted this to print"]
....
]
That sort-of-hackish change is probably just asking for trouble, especially considering that an improvement to switch makes it possible to get *any* type synonym to work:
switch type-of 3 [
:integer! [print "get-word will evaluate..."]
(first reduce [integer! string!]) [print "parens will evaluate too..."]
]
With this available, hacking up the core with some equality hacks seems misguided.
This also removes a word equivalence hack for the word GROUP! and the word PAREN! for the same reason... if evaluation is used, then …
=> Second thoughts - back out datatype/word equality, GROUP/PAREN

src/core/f-qsort.c, src/core/t-block.c, src/core/t-string.c, src/include/sys-core.h
(Completion of lingering incomplete fix from September 13, 2014 that had
died as a PR to GitHub rebol/rebol...being cleaned out during prep for source
code format conversion.)
In Rebol2:
>> sort "ABCabcdefDEF"
== "AaBbCcdDeEfF"
>> sort/case "ABCabcdefDEF"
== "ABCDEFabcdef"
In R3-Alpha:
>> sort "ABCabcdefDEF"
== "ABCDEFabcdef"
This fixes the behavior to be consistent with Rebol2.  It also adds support
for unicode characters, which were being "randomly" compared based on one
of their bytes.
To reduce the number of comparison functions that would have to be written
and avoid the use of global state, this imported the qsort_r implementation of
the quicksort instead of qsort.  (Fun fact: qsort_r() is not part of any standard...
so the parameter orders vary.  Rebol builds in the same version …
=> Fix case-sensitivity in string sort, support unicode, #2170

src/boot/natives.r, src/core/n-sets.c, src/core/s-crc.c
Previously the set operations would only allow BLOCK! and STRING!.
This makes it possible to use any two ANY-STRING! or ANY-BLOCK!
types together on set operations:
>> exclude quote (a b c d e) 'd/e/f/d/e
== (a b c)
>> intersect <abcde> "defde"
== <de>
The result type will be the type of the first parameter.
(This was the by-product of a reorganization to try and locate a bug in the
series termination logic, and was easy enough to do after that was found.)
=> Allow ANY-STRING! and ANY-BLOCK! types in set ops

src/boot/root.r, src/boot/sysobj.r, src/core/b-init.c, src/core/c-do.c, src/core/c-function.c, src/core/f-extension.c, src/mezz/mezz-help.r
With "Pure Local" generation offered via set-words, it has the problem of
being a bit "undifferentiated-looking":
foo: func [date [date!] out: d1: d2:][
out: [0 0]
set [d1 d2] get-iso-year out/2: date/year
vs.
foo: func [date [date!] /local out d1 d2][
out: [0 0]
set [d1 d2] get-iso-year out/2: date/year
The advantage of "pure locals" is that they aren't shown by WORDS-OF
and cannot be injected (e.g. by calling foo/local).  But the refinement lets
you use regular words and looks a little bit "less like code".
This modifies the FUNC generator to use the <local> tag as a cue to
convert WORD! following it into SET-WORD!, up to the next refinement.  It
will ignore any pure locals (set-words), and error on other kinds of words
(e.g. `<local> 'x #y :z`).  The appearance is better, and it gives …
=> Add <local> tag to FUNC + CLOS, move <infix>

src/boot/errors.r, src/core/c-do.c, src/core/c-frame.c, src/core/m-stacks.c, src/include/sys-value.h
The previous semi-hack of an evaluation trick so that get-words would
evaluate in paths has been upgraded to a much less hacky trick.  This
now allows for the evaluation of parens to also be used to get the words
to use as refinements in dispatch:
>> append/(first [only])/(to-word "dup") [a b c] [d e] 2
== [a b c [d e] [d e]]
The method by which this is done--as well as reducing the number of
writes done into call frames--has improved performance in a build of
the hostilefork.com using the static builder by 10%.  This means Ren/C
optimized non-debug builds are--for the first time--ever so slightly
faster than the rebolsource download (in that measurement).
=> Evaluate parens in refinement dispatch, ~10% speedup

src/boot/types.r, src/core/c-do.c, src/core/n-control.c, src/core/n-data.c, src/core/s-mold.c, src/core/t-routine.c, src/core/t-struct.c, src/core/u-parse.c, src/include/sys-core.h, src/include/sys-value.h, src/tools/make-boot.r
The evaluator loop is fairly optimized in the release build, but it
still costs more than not calling a function at all. This makes a new
note in the type table about whether that type has any behavior in
the evaluator at all... and that is used to generate a small TRUE/FALSE
table of whether each REB_XXX type needs the evaluator. This is
used in a new macro implementation for DO_NEXT_MAY_THROW in
order to bypass evaluation altogether.
The test isn't actually as simple as just checking the next value, due
to the behavior of infix. Even `foo [x] + [y]` might have some meaning
for an infix operator. Hence to take advantage of the skip there must be
*two* inert values in a row, like `foo [x] [y]` or `foo {a} 2`. (For these
purposes, REB_END counts as an inert value, so `foo [x]` is also able …
=> Eval_Table skips unnecessary evals, ~6% (?) speedup

src/boot/errors.r, src/core/c-do.c, src/core/c-frame.c, src/core/f-modify.c, src/core/f-stubs.c, src/core/m-stacks.c, src/core/t-block.c, src/core/t-string.c, src/mezz/base-funcs.r, src/mezz/base-series.r, src/mezz/mezz-math.r, src/mezz/mezz-series.r, src/mezz/sys-base.r, src/mezz/sys-load.r, src/tools/systems.r
This is a MAJOR change--that also corrects a bug introduced in
0c76e51 where the evaluator handled refinements used out of
order incorrectly.
Rather than being NONE!, an unused refinements args will now
be UNSET! when not running in legacy mode.  The switch for
controlling whether this is done is the same switch as the one that
controls whether refinement words are TRUE when used vs the
word of their refinement--so it is not possible to enable one without
getting the other.
The code most drastically affected by this change was the module
system, which would frequently take advantage of the NONE!
without testing whether the refinement was provided or not.  However
the advantages of the new rules are readily apparent--especially
when combined with the rule that an unset refinement argument …
=> Unset unused refinement args, MAJOR changes

src/core/c-do.c, src/mezz/prot-tls.r, src/mezz/sys-ports.r
This corrects an issue that was preventing HTTPS from working after
definitional returns were introduced.  Port actions such as OPEN
were implemented in user-code, but archetypally established as an
ACTION! definition.  The function call frame was established for the
definition of that action, e.g. `foo: action [port [port!]]`, but then each
port type could implement it with differences in the frame such as
`foo-impl: func [port [integer! port!] /local x y z]`.  Hence the frame
would have to be "redone" to get it prepared for the implementation.
The trick used to implement definitional returns was missing in building
these redone frames.  This adds that trick, as well as comments on the
issue and corrections for unset refinement arguments.
=> Redo_Func_Throws patch for definitional return

src/boot/errors.r, src/boot/sysobj.r, src/boot/words.r, src/core/c-error.c, src/core/s-mold.c, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r, src/tools/make-boot.r
This change brings about new flexibilities in the error design as
well as some new features.  It is large in terms of number of lines of
code, yet many of those lines of code are asserts and checks to make
sure the assumptions are correct.  Because the tests provided the list
of what most of those assumptions were, it did not change them and can
pass core-tests.r with nearly no modification...in both legacy mode and in
normal mode.
Key features include eliminating the fixed idea of `arg1: arg2: arg3:` as
the parameterization, letting you define named properties of an error
object that are more meaningful.  It also lets you define a template that
will do substitutions when the error is printed, as system errors could:
>> err: make error! [message: ["the" :animal "has claws"] animal: "cat"] …
=> Starting overhaul of errors incl. "self-awareness"

src/boot/natives.r, src/core/n-control.c, src/mezz/mezz-legacy.r
Though being a suggestion from myself, IF/ONLY and its friends
have not turned out to be all that popular.  In addition to being used
very rarely, they present a barrier to optimization in the evaluator,
which becomes more pressing as the unset changes open doors to
the use of IF for rapid chaining and "opting out".  Should IF, UNLESS,
and EITHER be constrained to not having refinements, and join ANY
and ALL...then these natives can be folded into the evaluator loop
sans call frames.
Syntactically, the construction `if a [[b]]` may be contracted down to
`if a '[b]` under future ideas of "lit bit".  In the meantime accepting the
idea that the branches don't have to be blocks is an overall "win", so
that change that came in the same commit will be retained as this one
is removed.
Support …
=> Move IF/ONLY and relatives to r3-legacy

src/tools/common-parsers.r
This fixes a bug where ren-c cannot build itself due to an error in line-of caused by FUNCTION defaulting local variables to Unset! instead of None!
=> Make default return-value from line-of explicit.

src/core/b-init.c, src/core/c-do.c, src/core/u-parse.c, src/include/sys-core.h, src/mezz/base-defs.r
Historically, the DO evaluator would take a series and an index offset
into that series.  The first step it would take would be to observe the value
at that index, and then proceed along from there.
This moves the first step of observing the value out so that the initial
value comes from the caller.  While most clients will treat this the same,
it makes it possible to simulate a head value for an evaluation that is
not resident in that series.  e.g. if one had the path `append/only` in
one location, and the series `[[a b c] [d e]]` in another, one would not
need to splice them together in order to `append/only [a b c] [d e]`
because that first value can be "pre-imaged" in the position at 0 cost.
*(This savings can be significant, as the array model of Rebol often must
"slide down" the …
=> Allow seeding of evaluator with value not in series

src/boot/core.r, src/core/c-do.c, src/core/n-control.c, src/mezz/mezz-legacy.r
There have been considerable enhancements to the evaluator--with
features like unset arguments to refinements revoking the request for
that refinement--and get-words or parens able to be used to evaluate
a refinement within a path.  These enhancements provide a general
replacement for the rather brittle positional mechanisms of APPLY.
Advantages to removing the now-deprecated APPLY implementation
out of the C code to userspace are numerous.  It means that there
can be a focus on just one evaluator, that can be tuned and sped up,
without worries about the numerous bugs that result from having two
parallel C codebases that must be adjusted when the bit-level needs
of the evaluator change.
This user-mode apply does not support infix functions.  It could be
modified to do so, but as it is …
=> Move APPLY to user-mode, legacy

src/core/c-do.c, src/core/m-gc.c, src/core/n-control.c, src/include/sys-value.h
There was a bit reserved in every value for whether that value was
a "reevaluating" value. This bit was the mechanism by which the now-dead
RETURN/REDO worked, but also how DO was able to return a FUNCTION!
and then have the evaluator go back and execute it inline with the next
arguments. When EVAL was introduced it used a similar mechanism.
Having an arbitrary "re-execute" bit that lives inside of each and every value
not only takes up a rare bit (that could be used for something else), but it's
also design-wise a very precarious idea. The settlement of the issue in
Ren-C is to have exactly one full-spectrum function that can do this, and
EVAL is that function.
https://trello.com/c/YMAb89dv
This handles the issue by merely recognizing eval as a NATIVE! specially,
and handling it in the …
=> Kill OPT_VALUE_REEVALUATE, EVAL inside evaluator

src/tools/common-parsers.r
Tweak C parser to allow redefinition of function body rule and other rule.
This allows Test to extend the parser for more detailed parsing without duplicating it, avoids slowing down the build process.
=> Tweak C parser to support Test changes (source analysis)

src/core/s-make.c
Copy_String(src, n, -1) must not try copy beyond tail
=> Fix Copy_String

src/core/f-stubs.c, src/core/t-bitset.c
R3-Alpha would allow you to poke numbers into bitsets, and checked
to see if those numbers were zero or not (where zero is false).  This
behavior of zero-detection as logic is used no other place in the code,
confuses the type handling, and isn't consistent with Rebol's "zero is
not false" belief.
>> foo: make bitset! 1
== make bitset! #{00}
>> poke foo 0 0.000000000000001
== make bitset! #{80}
>> bar: make bitset! 1
== make bitset! #{00}
>> poke foo 0 0.000000000000000
== make bitset! #{00}
It makes more sense to constrain to logic true and false than it does
to open the field to anything conditionally true by default.  (It's easy
enough to say TRUE? xxx or NOT ZERO? xxx to get a LOGIC!.)
So this reigns in the feature and makes anything poked into a bitset
that isn't a LOGIC! an error.
=> POKE on BITSET! only pokes LOGIC! values

src/core/d-print.c, src/core/n-sets.c, src/core/s-find.c, src/core/t-string.c, src/core/u-parse.c
The Find_Str_Char() routine was taking up about 10% of the build time
for hostilefork.com using the Draem static website builder, and it
seemed a bit excessive considering what the routine did.  By making
the routine a little more sophisticated and leaning on C library
routines for the common case of finding 1 or 2 characters in a byte
string (that aren't NUL)--when searching forward and skipping by 1
character at a time--this makes it faster.
For the moment the old routine is called as a double-check in debug
builds just to make sure nothing has changed.  However, this called
out a problem with infinite loops based on the sign of the index
when a negative skip is used and nothing is found.  Rather than
change the old routine in the same commit this defers the issue, given
that no working …
=> Optimize Find_Str_Char, fix negative skip

src/core/c-error.c, src/core/n-system.c, src/mezz/mezz-legacy.r
The STACK routine that produced a backtrace was designed mainly for
reporting a block list of labels for an ERROR! to report its "where"
location.  The simple functionality and confusing interface wasn't
fitting for interactive stack exploration.
This implements a more featured version of BACKTRACE, which by default
is zero arity and gives numbered stack frames...suitable for an
interactive console that might be suspended in mid-stack (as in at a
debug break).  It attempts to also cover enough behaviors to implement
the previous STACK function's behavior, which is rewritten as
userspace code in `<r3-legacy>`.
For a version of the bare-bones functionality that just gives back
a list, BACKTRACE/ONLY provides that functionality at the moment.
Names and interface are very likely to change.
=> New BACKTRACE native (replaces STACK)

src/core/a-lib.c, src/os/host-core.c, src/os/host-main.c, src/tools/make-os-ext.r
This removes the dependency of %host-main.c (which implements the REPL)
on the RL_Api.  Instead it is able to use essentially any function that
the interpreter has established for its own use.  This gives it the
ability to inspect REBVALs or REBSERs, to handle THROW and FAIL, etc.
It's accomplished in a fairly minimalist change, which shifts the
responsibility of linking the host table off to %host-core.c - which
is pretty much entirely RL_Api and RXIARG calls (as currently written).
The change is integral to being able to adapt the console to support
interactive debugging (in an era prior to the definition and design
of an RL_Api replacement).
=> Tweak host-main.c to use sys-core.h

src/core/c-do.c, src/include/debugbreak.h
Not to be confused with the current work on breakpoints in the Rebol
code itself, this allows a parallel facility to add programmatic
breakpoints into the C code for Rebol.  It does so by adding in a
header called %debugbreak.h from this GitHub repo:
https://github.com/scottt/debugbreak
It includes an experimental usage in the "break on tick count" code
(which should be triggered by a command line option and not require
a recompilation).
The file says it has a fallback path for unsupported architectures,
so this is to run through the build configurations and see if that
is indeed the case.
=> Programmatic GDB breakpoint support

src/boot/errors.r, src/boot/sysobj.r, src/core/c-do.c, src/core/c-error.c, src/core/c-function.c, src/core/n-control.c, src/core/n-system.c, src/core/u-parse.c, src/include/sys-core.h, src/include/sys-value.h, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r
This alters the behavior of dynamically-scoped EXIT in two significant
ways.  One is that natives will be exited just like non-natives, so
if you were to write:
foo: func [] [if 1 < 2 [exit print "no"] print "yes"]
Then calling foo would print "yes", because IF would respond to the
EXIT signal.
This is coupled with another change which is to allow the targeting of
a specific function or closure to exit via the /FROM refinement.  A
name of a function or the frame object of a closure can be used.  So
this exit will reach past the IF to WHILE to break the infinite loop.
while [true] [if 1 < 2 [exit/from :while]]
Stronger contracts will be possible with FUNCTION! (as with CLOSURE!)
when each function frame is individually distinguishable.  In the
meantime, the most recent call on the stack …
=> EXIT/FROM any stack level, natives

src/boot/errors.r, src/core/u-parse.c, src/mezz/mezz-legacy.r
This implements #2165 where PARSE is to return the input series on
success, and NONE on false, unless a RETURN is used to override it
(in the future, COLLECT would override it as well).
It also implements a twist, with a PARSE? variation that can only
return TRUE or FALSE.  Since it ends in a question mark, the idea that
it act exactly like the old PARSE isn't a precise match...as the rule
is that functions ending in question mark return *only* true or false.
As one possible way of pushing that rule through, the PARSE? variant
does not tolerate RETURN (unless it is a return of a LOGIC!) and
will error.
This makes PARSE? suitable for use in practically every case where the
previous desire to return a TRUE or a FALSE was desired.  In the cases
where it was not, the PARSE variant makes more …
=> PARSE returns input on success, PARSE? variant

src/boot/errors.r, src/core/f-series.c, src/core/t-struct.c, src/include/sys-series.h
When the series has an external data storage, the life cycle of the data storage is not managed by the core. The core needs to know when the data can not be accessed any more, or the core could crash.
`OPT_SER_ACCESSIBLE` is for this purpose.
A new native is added for destroying the data storage and mark it non-accessible.
This is the testing script:
```
REBOL []
libc: make library! %libc.so.6
malloc: make routine! compose [
[
size [uint64]
return: [pointer]
]
(libc) "malloc"
]
free: make routine! compose [
[
mem [pointer]
return: [void]
]
(libc) "free"
]
m: malloc 4
s0: make struct! compose/deep [
[raw-memory: (m)]
i [int32]
]
;normal access
s0/i: 10
print mold values-of s0
print length? s0
;free the external storage
destroy-struct-storage/free s0 :free
err: try …
```
=> Add a series flag OPT_SER_ACCESSIBLE

src/core/c-do.c, src/core/n-control.c, src/include/sys-do.h
EVAL gives special access to "bounce" the evaluator, giving its
argument inline access to subsequent parameters.  It replaces DO of a
FUNCTION! but is more general:
>> eval (quote x:) 1 + 2
== 3
>> print x
3
(See notes: https://trello.com/c/YMAb89dv )
This enhances EVAL with an /ONLY refinement, somewhat in the spirit of
APPLY/ONLY.  This allows one to slip the ensuing values directly and
bypass any evaluation, regardless of quoted or unquoted status:
>> bar: func [a b :c] [print [a b c]]
>> eval/only :bar 1 + 2
1 + 2
The implementation of this feature is a further step toward making
Do_Core() the sole piece of code that is responsible for building
call frames in the codebase (such as doing complete refinement and
error checking on calls to Rebol functions from C, through a single …
=> Experminental EVAL/ONLY, subvert argument eval

src/core/b-init.c, src/core/m-stacks.c, src/include/sys-series.h, src/include/sys-stack.h, src/include/sys-value.h
(Hopeful fix for #208, #211)
The idea of using the lowest bit in the header of a REBVAL to indicate
termination, and making it the size of a REBUPT (Rebol's uintptr_t
abstraction), led to the idea of allowing pointers in data structures
do this termination job as they were a sunk cost--and this would add
little complexity to those structures.
Though a bit sketchy in principle, suggestion that it worked on most
all platforms made it seem like something that could be used and
then disabled on those rare architectures upon which it would not work
in practice:
http://stackoverflow.com/questions/19991506
But in addition to being overall a questionable idea to allow *any*
builds purposefully break undefined behavior, reports were submitted
of conventional platforms (Windows7 Intel w/MinGW, …
=> Change termination trick to not break aliasing

src/boot/sysobj.r, src/core/c-do.c, src/core/n-data.c, src/mezz/base-series.r, src/mezz/mezz-control.r, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/sys-base.r, src/mezz/sys-load.r, src/tools/common.r, src/tools/r2r3-future.r
This is a set of changes rolled up that were triggered by the idea from
@earl to make an operation designed to "set-and-test" a variable, which
came off as notationally pleasing without having to sacrifice the error
on plain get word assignments of unsets.
It makes the core operation where a value is optional named SET/OPT
and GET/OPT, which is just as short as GET/ANY and SET/ANY but more
in line with the present intentions for the connection between the unset
state and optional parameters and values.  The /ANY variations are
moved into user code for reasons that they were likely going to have to be
anyway...which will slow the primitives down some in the near term but
there should be ways of addressing it if it becomes a problem.
Due to hedging as a result of thoughts in chat, a …
=> Back out legality of `x: ()`, CHECK-SET, SET+GET/OPT

src/mezz/base-funcs.r
This adds a construct designed to pass through a value, assuming it
is not NONE! or UNSET!... e.g. that it is a SOMETHING?.  If it is a
NOTHING? then it will fail with an error message.
There is also a refinement that is able to take a data type or types
to check.  If types are provided to the ENSURE then they override the
checking for set and unset--only those types will match, and NONE!
or UNSET! will be fair game.
>> ensure 1020
== 1020
>> ensure none
** user error: ENSURE did not expect value to have type none!
** Note: use WHY? for more error information
>> ensure if 304 > 1020 [print "unsets aren't taken"]
** user error: ENSURE did not expect value to have type unset!
>> ensure/type 1020 string!
** user error: ENSURE did not expect value to have type integer!
>> ensure/type 1020 …
=> Add ENSURE mezzanine (with ENSURE/TYPE)

src/core/a-lib.c, src/core/b-init.c, src/core/c-do.c, src/core/c-error.c, src/core/c-function.c, src/core/c-port.c, src/core/d-crash.c, src/core/d-print.c, src/core/f-extension.c, src/core/f-stubs.c, src/core/m-gc.c, src/core/m-stacks.c, src/core/n-control.c, src/core/n-data.c, src/core/n-io.c, src/core/n-system.c, src/core/s-mold.c, src/core/t-block.c, src/core/t-routine.c, src/core/t-struct.c, src/core/t-typeset.c, src/core/u-parse.c, src/include/sys-core.h, src/include/sys-do-cpp.h, src/include/sys-do.h, src/include/sys-globals.h, src/include/sys-series.h, src/include/sys-state.h, src/include/sys-value.h, src/tools/make-boot.r
*(Note: The changes in this commit in %c-do.c are longer than GitHub
will display.)*
This is a top-to-bottom rewrite of the evaluator, which hones its ways
of acquiring and updating values to process into a stylized API that
allows Do_Core to serve as the basis for all(*) evaluation requests.
(* - "extension" callbacks are not yet using the method, but will.)
This recasts the evaluator to build upon three basic primitives for
navigating the input data (really two, but three for clarity):
- FETCH_NEXT_ONLY_MAYBE_END
- DO_NEXT_REFETCH_MAY_THROW
- DO_NEXT_REFETCH_QUOTED
By organizing the evaluation to not use arbitrary index math on the
input series, this opens the doors to using sources for the data to
evaluate which are not random access (such as C vararg lists).  By
extending the EVAL …
=> Prefetching evaluator (full rewrite)

src/core/f-series.c
Fix that error:
>> select reduce [:exp 1] :exp ==> none ??
=> Fix Cmp_Value for NATIVE!s

src/core/a-lib.c, src/core/b-init.c, src/core/m-gc.c, src/core/m-stacks.c, src/include/sys-do.h, src/include/sys-globals.h, src/include/sys-stack.h, src/include/sys-state.h
R3-Alpha used an ordinary "block" style series of values to represent
its stack, in order to leverage the existing mechanics for expansion
and access operations.  However, it did not want to pay the cost of
checking on each PUSH to see if it was out of bounds of the series to
see if it needed to expand, nor did it maintain termination with an
"END!" value the way a normal series did.
So instead of using typical series append operations, it would bump
the stack by an arbitrary amount in those routines that were known to
run out of space.  Most were given headroom of 20 slots to work in,
with the assumption that if it were not enough then that routine
would have to include the manual bumping as well.
That was somewhat failure-prone, and Ren-C sought to have a stack
"service layer" that …
=> Optimize stack indexing and expansion

src/boot/root.r, src/core/b-init.c, src/core/d-print.c, src/core/n-control.c, src/core/n-io.c, src/core/n-system.c
This adds features to PRINT and FAIL, and offers the functionality to
make a string via FORM/NEW (because there is speculation that FORM may
wind up being the word taken for this behavior, despite breaking legacy
compatibility with the quoted-vs-non-quoting default).
Largely this is folding a native implementation of what was called
"COMBINE" into the basic behavior of PRINT.  Changes are:
BINARY! is not molded as a Rebol constant, rather interpreted as UTF8;
if Rebol molding is desired that must be requested explicitly:
>> print ["Hello" #{52656E2D43} "World"]
Hello Ren-C World
>> print ["Hello" mold #{52656E2D43} "World"]
Hello #{52656E2D43} World
Blocks can be used as in PARSE for grouping or recursion.  Also as in
PARSE, this creates the opportunity for stack overflows (but if one
is …
=> PRINT/FAIL new design, recursion, |, BINARY! UTF8

src/boot/actions.r, src/boot/errors.r, src/boot/root.r, src/boot/types.r, src/boot/typespec.r, src/core/b-init.c, src/core/c-do.c, src/core/c-function.c, src/core/m-gc.c, src/core/s-mold.c, src/core/t-block.c, src/core/t-typeset.c, src/core/t-varargs.c, src/include/sys-core.h, src/include/sys-do.h, src/include/sys-series.h, src/include/sys-value.h, src/tools/file-base.r
This is a preliminary implementation of a variadic function design. (It
is relatively isolated and not too likely to cause problems in code not
using it, so being integrated for experimentation and feedback.)
The basic idea is to put <...> on an argument, which defers the reading
of it until TAKE is used on the variable during the body run.
>> foo: func [x [integer! <...>]] [
print ["foo takes" take x "and then" take x]
]
>> foo 1 2
foo takes 1 and then 2
>> foo 1 + 2 3 + 4
foo takes 3 and then 7
However it interacts with quoting, type checking, error reporting, and
allows for complex chaining--including the mutation to and from blocks
to process the arguments.  TAIL? is also available as an operation,
as is FIRST for one element of lookahead (if argument is hard quoted).
Please see the …
=> *experimental* VARARGS! - highly flexible variadics

src/core/c-error.c
With the various changes to the stack model, the NEAR reporting had
atrophied.  This repairs it by picking up to three values to the left
of the execution point and three values to the right, and then splicing
in a marker to indicate the point of error.  If it truncates either
the left or the right it adds an ellipsis.
=> Improve error NEAR reporting

src/boot/errors.r, src/core/c-do.c, src/core/n-control.c, src/include/sys-do.h
This modifies CASE to be more tightly integrated with the evaluator
(for improved performance and error reporting).  It also changes the
handling of expression barriers, so that they are only allowed between
the case pairs.
>> case [false 1 | true 2]
== 2
>> case [false 1 true | 2]
** Script error: Expression barrier hit in middle of CASE pairing
** Where: case
** Near: false 1 true ?? | 2
=> CASE special handling of expression barriers

src/core/d-print.c, src/core/n-io.c, src/mezz/mezz-legacy.r
This adds an /ONLY switch to PRINT in order to have it print a value
without adding a newline, nor reducing it if it's a block.  PRIN is
then rewritten in terms of PRINT/ONLY (reducing blocks first).
It also changes the nesting logic so that a block will only be
reduced and handled in the "print dialect" if it appears literally.
Hence `print ["a" [reverse "hello"] "b"]` will run the reverse, while
`foo: [reverse "hello"] print ["a" foo "b"]` will not.  This is a
step toward avoiding accidental reducing, although further changes to
the "print dialect" will likely be needed.
=> Add PRINT/ONLY, only dialect nested PRINTs if literal

src/boot/errors.r, src/core/b-init.c, src/core/c-bind.c, src/core/c-do.c, src/core/c-error.c, src/core/c-eval.c, src/core/c-frame.c, src/core/c-function.c, src/core/c-port.c, src/core/d-crash.c, src/core/m-gc.c, src/core/m-stacks.c, src/core/n-control.c, src/core/n-data.c, src/core/n-reduce.c, src/include/sys-core.h, src/include/sys-do.h, src/include/sys-value.h, src/os/host-main.c
The concept of the "frameless" optimization was that pushing stack
space, iterating argument lists, and type-checking could be foregone
or simplified in certain foundational operations (IF, EITHER, QUOTE,
CASE) by having those routines operate directly on the input series--
as if those natives were part of the Do_Core() function itself.
Between the time of the initial idea and today, some changes made the
idea less of a win.  The evaluator had its state turned "inside out"
such that all functions had frame objects, and it was merely that these
routines were becoming "varless".  Also, the number of conditions under
which varlessness could be exercised were reduced, so several checks
were needed to decide whether to put it into effect--creating cost for
both varless and non-varless …
=> Retire varless ("frameless") native optimization

src/core/m-stacks.c, src/include/sys-stack.h
Because the function arguments are put in the Reb_Chunks, which reside in
the fix-sized Reb_Chunkers, the number of arguments is limited to
((CS_CHUNKER_PAYLOAD - sizeof(struct Reb_Value_Header)) / sizeof(REBVAL)),
which is 63 on 64-bit systems.
This commit removes the limit by making the chunker size dynamic.
=> Loose the limit on the number of function arguments

src/mezz/base-infix.r, src/mezz/mezz-legacy.r, src/mezz/prot-tls.r, src/tools/r2r3-future.r
In Ren-C, infix AND OR and XOR are all logical operators.  (The prefix
logical forms are AND?, OR?, and XOR?)
The bitwise and "mathy" and-and-or use their boolean logic symbols
so infix operators are AND* and OR+.  Initial trials named the XOR
operator XOR- with a trailing minus sign.
But the exclusive-OR operation is symbolized by a + with a circle around
it.  Although there is some light parallel to subtraction (1 - 0 = 0,
1 - 1 = 0) the dangling hyphen on the end looks awkward and slight,
so it is probably better to just go ahead and make both OR+ and XOR+
use a plus symbol to denote they are bit math forms of the operations.
=> Change infix bitwise xor from XOR- to XOR+

src/boot/sysobj.r, src/core/c-eval.c, src/core/d-print.c, src/core/n-data.c, src/core/t-map.c, src/core/u-parse.c, src/mezz/base-funcs.r, src/mezz/mezz-control.r, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/sys-load.r, src/tools/common.r, src/tools/make-boot.r, src/tools/r2r3-future.r
*(NOTE: This commit is from late March, and was tied up as part of the specific binding branch.  It is being extracted as part of the `pre-specific-binding` "frozen" branch, since the decision is now firmed up, after experimenting with alternatives like `check-set`.)*
---
With the demise of "reified unsets", the role of the non-reified unset
(a "void" or "no expression result") is being reconsidered.  Its
advantage as a return value from routines that need an "out of band"
result, such as to distinguish `first []` from `first [_]`...is high.
Historically Rebol has sought to be ergonomic by conflating "no result"
with a "NONE! result", because of the hot-potato nature of handling an
UNSET! value.  A non-negotiable aspect of the hot-potato is on typical
GET, because otherwise a typo like …
=> Re-introduce legality of `x: ()` assignments

src/core/l-scan.c, src/core/m-series.c, src/core/s-mold.c, src/include/sys-scan.h, src/mezz/base-defs.r, src/mezz/prot-tls.r
This change makes a single _ equivalent to a literal NONE! value, and
is how a NONE! is molded to the display.  It establishes BLANK! as an
alias, and a test function BLANK?...but with no word BLANK to look
up to the value, as the underscore is intended to speak for itself.
WORD! with an underscore-only name would have to be done in construction
syntax.  (Note: #_ was seen in use in a very old copy of Red.)
The rationale for introducing this new literal form is due to an interest
in making it more useful in dialecting, and to remove it from the set of
things that the users might treat as a variable.  This will make it a
safer choice for dialects which just need to indicate a "slot", but do
not wish to establish their own keyword for slots.  Since NONE! needed
a literal form anyway, …
=> Literal blank for none

src/boot/errors.r, src/boot/sysobj.r, src/core/b-init.c, src/core/c-error.c, src/core/c-eval.c, src/core/c-function.c, src/core/c-path.c, src/core/d-legacy.c, src/core/l-scan.c, src/include/sys-do.h, src/include/sys-globals.h, src/include/sys-value.h, src/mezz/base-series.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/prot-tls.r, src/mezz/sys-load.r
This canonizes refinement values in both system-called functions and
frame-invoked functions to only allowing LOGIC! true and false.
This is a change from one of the earliest Ren-C adaptations, which was
to try and take advantage of making refinements their own WORD! in
order to ease chaining.  e.g. a function with a refinement /ONLY could
then chain that to APPEND by writing `append/:only`, where if it were
none in the calling function it would not be applied, and if it were 'ONLY
in the calling function it would be used.
While that was a useful feature for its time, a lot has changed since.
With GROUP! executable in paths, one can write `append/(if only 'only)`
which is not much longer.  There are also other possibilities with
APPLY for doing proxying of words from the current frame …
=> not TRUE/NONE, not WORD/NONE but TRUE/FALSE refinements

src/tools/common.r
The routine `to-c-name` was turning things like "+" into "plus" with
a switch statement.  However, it was not copying the strings.
As a consequence, callers who used `to-c-name` with the expectation that
they could modify the result (e.g. that it was acting like a FORM)
would wind up modifying the strings in the switch statement.
This is one good example of why there are likely strong good reasons for
considering source immutable by default.
=> Mutation bugfix for common.r's to-c-name

src/mezz/mezz-help.r
Param and it's types were not being added to the result correctly.
=> Fix two SPEC-OF bugs

src/boot/sysobj.r, src/core/c-eval.c, src/core/d-eval.c, src/core/m-gc.c, src/include/sys-do.h, src/mezz/mezz-legacy.r, src/mezz/mezz-math.r, src/mezz/prot-tls.r, tests/core-tests.r
(Note: r3-legacy compatibility switch as `no-infix-lookahead`)
Typically the evaluator is "greedy", so here it sees 10, then sees an
= operation whose first argument gets 10, and then as much is consumed
as possible...so `add 5 5` is processed:
>> 10 = add 5 5
== true
This greediness leads to errors if one doesn't see that an expression
is actually incomplete, e.g. before doing an equality test:
>> add 5 5 = 10
** Script error: expected logic! not integer!`
There it's the case that for the second argument to add, 5 keeps looking
and turns into the logic expression (5 = 10) as the second argument.
It's a simple and longstanding rule.  But R3-Alpha had a strange infix
"feature" that twisted it the other way:
>> 5 + 5 = 10
true
>> 10 = 5 + 5
** Script error: expected logic! not integer! …
=> Set-Words/paths pushed, lookahead in lookback operations

src/core/c-function.c, src/mezz/base-funcs.r, src/mezz/mezz-legacy.r, src/mezz/mezz-math.r, src/mezz/mezz-secure.r, src/mezz/sys-load.r, tests/datatypes/function.test.reb
This moves the /WITH refinement on FUNCTION as a feature to be the
<in> tag.  So instead of:
f: function/with [spec...] [body...] obj
You can write:
f: function [spec... <in> obj] [body...]
It also switches the block-based statics aspect of that /WITH to be a
<static> feature.  So instead of:
f: function/with [spec...] [body...] [x: 1 y: 2]
You can write:
f: function [spec... <static> x (1) y (2)] [body...]
The /EXTERN feature on the other hand took the "with" name, as a way
of defining the outer words you want to define as "being brought in
with" the function defintion.  So instead of:
f: function/extern [spec...] [body...] [a b c]
You can write:
f: function [spec... <with> a b c] [body...]
Along with these conveniences is the ability to use parentheses as a
way of providing defaults to …
=> <in>, <with>, <static> function specs...plus defaults

src/core/n-data.c, src/include/sys-bind.h, src/include/sys-value.h, src/mezz/base-funcs.r
In order to line up with the usual type checking routines like
integer? (which is void-tolerant to fail the test), MAYBE would allow
voids... even though they have no type.  This pushes it further so
that even `maybe :void? ()` will work.  It passes through the void.
Also includes a ? version to hand back logic, in case knowing whether
the test passed generically (even for FALSE, BLANK, and voids) is more
important than passing through the value.
=> Add MAYBE? variant for MAYBE, improve void handling

src/boot/words.r, src/core/c-function.c, src/core/n-data.c, src/mezz/base-defs.r, src/mezz/base-funcs.r
Checking against types or typesets was previously done by way of
specializing an arity-2 HAS-TYPE? function, which took both a data
type and a value to check.  So during bootstrap, a loop would make
a specialization for each type, something like:
string?: specialize :has-type? [type: string!]
However, there is a small cost to the specializations compared to
having something more like a separate native function to check each
type.
This commit does something almost as good performance-wise as having
a native per type and typeset.  It introduces TYPECHECKER, which is a
function generator that makes a different type of function.  The "body"
is actually the type or typeset to check, and it uses a different
dispatcher for types and typesets...so even that doesn't have to be
branched on. …
=> Replace HAS-TYPE? specializations with TYPECHECKER

src/core/s-mold.c, src/mezz/mezz-legacy.r
While there is no UNSET! (or VOID!) type in Ren-C, an implementation
detail of functions and contexts uses a 0 Reb_Type value to signal the
absence of a value...hence this bit is used to carry the `<opt>`
optionality status of a parameter.  (This is an optimization, and is
becoming more obviously so in light of design for user-defined types.)
However, this trick was exploited to implement the ANY-TYPE! typeset
for r3-legacy.  This made a user facing typeset that contained a
"non type", which was causing an assertion to fire when the ANY-TYPE!
typeset from r3-legacy was shown (since there was no symbol).
This changes the trick so that the ANY-TYPE! typeset is just a synonym
for ANY-VALUE!.  The ability to allow for optional arguments to
functions is done with a different compatibility …
=> ANY-TYPE! synonym for ANY-VALUE! except in r3-legacy FUNC

src/core/a-lib.c, src/core/b-init.c, src/core/f-extension.c, src/core/m-gc.c, src/core/m-pools.c, src/core/t-routine.c, src/include/sys-core.h, src/include/sys-handle.h, src/include/sys-rebser.h, src/include/sys-rebval.h, src/include/sys-value.h
This creates a new kind of "Managed" HANDLE!, which is distinct from
the traditional "Simple" HANDLE! (that was just an opaque pointer to
some data the system knew how to interpret, but that the user was
not supposed to see).
A managed handle uses a singular array--which is the size of a REBSER
node--in order to engage the garbage collector.  When the handle is
GC'd, it calls a hook function that receives the handle's REBVAL*
to do a finalization.
As an added advantage to managed handles, changing their content will
change all the references to that handle.  This means a pointer can be
moved or reallocated safely, even if several copies of that handle
REBVAL have been made.
=> Introduce "managed handles" with a GC cleanup function

src/boot/errors.r, src/core/n-control.c, src/include/sys-value.h, tests/control/if.test.reb, tests/datatypes/error.test.reb
A very common mistake for new users is to place a BLOCK! around a
conditional expression.  Since blocks are always TRUE, this leads to
confusion and bugs.
(It's an especially easy mistake to make when converting a WHILE into
an IF.)
Mechanically, functions in Ren-C are able to distinguish when a value
received as an argument was the product of an evaluation vs. literal
at the callsite.  So it can tell the difference between:
x: [something]
if x [print "legal case, evaluated"]
if [something] [print "illegal case, literal"]
This distinction is used to generate an error.  Bypassing the check
can be done with a GROUP!:
if ([something]) [print "now the block is an evaluation product"]
This extends the check to CASE, which is likely to help catch casual
errors where a body block is accidentally …
=> No literal blocks in condition of IF/UNLESS/EITHER/CASE

src/boot/sysobj.r, src/core/c-eval.c, src/mezz/mezz-legacy.r
In R3-Alpha, `10 = 5 + 5` would be an error due to lookahead
suppression from `=`... so it gets interpreted as `(10 = 5) + 5`.
However, `10 = x: 5 + 5` would not be an error, as the SET-WORD!
caused a recursion in the evaluator which was morally equivalent
to as if a single-arity prefix function were being called.
For efficiency in Ren-C, SET-WORD!s do not bear the overhead of state
of a recursion--which is reserved for cases requiring "FRAME!s".  Hence
the introduction of SET-WORD!s or SET-PATH!s into expressions merely
"sample" the value at that point--in a ghostly fashion--without
affecting the flow of the expressions.
This is likely good, because it means that although PROBE may change
the evaluation flow, a SET-WORD! will not.  That makes them a good
tool for sampling the value at …
=> Add sets-suppress-lookahead flag for R3-Legacy

src/boot/errors.r, src/core/n-native.c, src/core/s-ops.c, src/core/s-unicode.c, src/include/sys-function.h, tests/misc/fib.r
This commit is @HostileFork's first set of suggestions for the user
native interface.
* The step of creating a native generates a function without compiling
it yet.  Then a separate COMPILE command is used to group together
some number of user natives and other source string fragments.
* If COMPILE is not explicitly called on a native before that native
is called, then a default COMPILE containing just that native's
code will attempt to run.
* The PARAM() and REFINE() macros are generated automatically in the
body of the function, so the user does not have to type those in.
* A linker name for the user native is automatically generated if one
is not provided explicitly.
See the changes to %tests/misc/fib.r for some of the impact.
=> User native enhancements, separate MAKE-NATIVE and COMPILE steps

src/core/b-init.c, src/core/c-error.c, src/core/c-eval.c, src/core/n-native.c, src/include/reb-ext.h, src/include/sys-do.h, src/mezz/base-defs.r, src/mezz/base-infix.r
While postfix operators were possible in theory, none existed...so there
was a bug in the handling of them if they were the last value in a
series.  This does a light reorganization of the evaluator to correct
that issue and get rid of some redundant code.
Given the ability to defer the left hand argument in postfix, then the
concept becomes much more interesting--because it means a complete
expression can be gathered before it is applied.  This uses deferment
as a trial for ? to be a postfix test for ANY-VALUE?:
>> blk: [1 2 3 4]
>> while [x: take blk ?] [print x]
1
2
3
4
This replaces the previous experiment of ? as a prefix synonym for
ANY-VALUE?.
(Also, updates some comments.)
=> Update evaluator to properly handle postfix, make ? postfix

src/core/a-lib.c, src/core/c-bind.c, src/core/c-function.c, src/core/e-func-symbols.c, src/core/m-stacks.c, src/core/n-control.c, src/core/n-native.c, src/core/s-mold.c, src/core/t-function.c, src/include/sys-function.h
If you write something like `foo: func [...] []`, this substitutes the
ordinary dispatcher with one that is an absolute no-op and returns
void.  This means there's no invocation equivalent to `DO []`, and
there is also no overhead for frame reification.
While this may seem like an uncommon case to optimize for, it actually
does have an application, exemplified by the default definition for
ASSERT...which is an empty body.  It's only when you are in "debug mode"
(currently the default) that ASSERT gets HIJACKed with an actual
implementation.
So in addition to helping optimize the rare case where a body ends up
being a no-op due to a COMPOSE or other random reason, this makes it
possible to create low-overhead stubs for instrumentation...which can
be hijacked with implementations when …
=> Optimization for empty user function bodies

src/boot/root.r, src/core/b-init.c, src/core/c-frame.c, src/core/c-function.c, src/core/t-object.c, src/include/sys-core.h, src/mezz/base-funcs.r, src/mezz/mezz-series.r
Ren-C replaced FUNCTION's /EXTERN refinement with the idea of having
`<with>` in function specs, paralleling how locals are specified.  This
adds `<with>` to FUNC, even though there is no "locals gathering" which
would affect it in the way FUNCTION needs externs.
This allows for easier transitions between FUNC and FUNCTION modes of
coding.  The `<with>` lets you put strings after the words which are
ignored, which can help serve commentary purposes on what external
variables are for.  (The strings are thrown out and not stored anywhere
accessible to HELP, merely source comments.)
k: 10
foo: func [
x [integer!]
<with> k "number of variants"
][
k: x ;-- <with> was commentary, no mechanical difference
]
But most interestingly, it gets rid of the awkward <no-return> and
<no-leave> refinements …
=> Add <with> to FUNC, eliminate <no-return> and <no-leave>

src/core/c-function.c, src/core/m-gc.c, src/core/n-loop.c, src/core/n-sets.c, src/include/sys-function.h, src/include/sys-rebser.h
This permits you to use `for-each f function! [...]` to get an instance
of each function value that was in existence at the start of the
FOR-EACH.  If in the body any functions are created, they will not
be included in the enumeration.
This means that the routine has to snapshot all the values at the
start of the routine, and protect them from GC during it.  So it is
not a particularly efficient operation.  However, it is intended
primarily for instrumentation purposes (getting tables of functions to
print out for statistics).
To faciliate this, a REBSER identifying a function's paramlist is now
identified by an ARRAY_FLAG_PARAMLIST bit.  This also addresses an
outstanding issue with using functions as a garbage collection root--
as previously, it wasn't possible to tell if a REBSER was a …
=> Allow FOR-EACH to enumerate all the FUNCTION!s

src/core/c-eval.c, src/core/d-stack.c, src/core/f-extension.c, src/core/n-control.c, src/core/n-do.c, src/core/n-error.c, src/core/n-function.c, src/core/n-loop.c, src/core/n-native.c, src/core/p-signal.c, src/core/t-none.c, src/core/t-string.c, src/core/t-struct.c, src/core/t-varargs.c, src/core/t-word.c, src/core/u-compress.c, src/include/sys-function.h, src/include/sys-rebval.h, src/mezz/base-defs.r, src/mezz/prot-http.r
In the once-hotly-debated question of whether it made more sense for
UNTIL to be arity-2 (to match WHILE) and then have arity-1 forms of
both WHILE and UNTIL as "LOOP-UNTIL" and "LOOP-WHILE", it was decided
to keep UNTIL as arity-1 and put the burden of reconfiguring on the
user (and then to make sure that burden was very small).
To make that burden as small as possible, this goes ahead and does the
implementation of all four variants by the "ideal" definition.  Then
during boot it simply says:
until-2: :until
until: :loop-until
This can be undone by a user with `until: :until-2`.  The definitions
are used in Rebmu as UT, WH, LU, LW.
Includes some comment editing in %sys-rebval.h, and moves Reb_All to
not be platform dependent (but use platform-dependent REBUPT).
=> LOOP-WHILE, LOOP-UNTIL, and UNTIL-2

src/boot/root.r, src/core/b-init.c, src/core/c-eval.c, src/core/c-function.c, src/core/n-function.c, src/core/t-typeset.c, src/include/sys-typeset.h, src/mezz/base-funcs.r, src/mezz/base-infix.r
R3-Alpha achieved an apparent "left-to-right" via lookahead suppression.
So when evaluating:
1 + 2 * 3
Lookahead would be enabled by default, 1 would evaluate to itself
and see an OP! in that lookahead.  During evaluation of the remaining
`[2 * 3]`, lookahead would be disabled.  (This would happen during the
right-hand side evaluation of any OP!.)  Hence it would see the 2,
which would evaluate to itself, and the addition would run--thus
finishing the first infix operation.  Lookahead would be re-enabled, so
it would see the `*`, lookahead would be disabled while evaluating the
3...and so on.
(In this case there's nothing further to see, so the expression is 9.)
This form of limiting argument evaluation was seen as a poor default
behavior for Ren-C.  So enfixing operators would not have …
=> Replace <defer> with new semantics as <tight>

src/boot/actions.r, src/core/t-string.c, src/tools/make-headers.r
Rebol issue 1160 pointed out a problem with using a TAG! to search
over a string:
https://github.com/rebol/rebol-issues/issues/1160
This change uses FORM on the argument, so `find "<abc>" <abc>` will
account for the tag delimiters.
Searching has some strange ramifications for other types, given that
you can't really get a good result out of `find <abc> "<"`.  For
lack of a better rule, though, this goes ahead and FORMs.
Also gets rid of the unimplemented wildcard features in FIND and
SELECT, which are more suited to a PARSE or GLOB dialect.
=> FORM non-STRING! (instead of non-ANY-STRING!) in FIND

src/core/s-unicode.c, src/core/t-string.c, src/include/sys-core.h, src/include/sys-scan.h, src/mezz/mezz-types.r
The current implementation limits codepoints in strings to 2 bytes in
size maximum (the "standard" unicode plane).  This means it's not
possible to represent codepoints in the higher planes, which are
humorously referred to as the "astral planes".
Historically these were not very commonly used, and were for more
esoteric historical languages (egyptian linear B).  The growth of
emoji usage has made them more common in Internet communication.
As a stopgap to full support, this makes TO-STRING a native which can
accept a handler.  This handler can substitute other string or
character values for the high codepoints, e.g.:
>> test-data: #{22646973706C61796E616D65223A224A6F6E20F09F98BA22}
== #{22646973706C61796E616D65223A224A6F6E20F09F98BA22}
>> decode-cat: func [x] [
if x = 128570 [return …
=> /ASTRAL refinement for TO-STRING

src/core/c-context.c, src/core/c-error.c, src/core/n-data.c, src/core/t-image.c, src/core/t-object.c, src/include/sys-core.h
This allows building on HaikuOS with the distributed GCC 2.95 that
comes with the R1 alpha build, but must be built in C++ mode.
That version of GCC (over 15 years old) does not include options for
a C build to have declarations directly after statements.  That ability
was in C++ since its inception, and was formally added to C in the C99
standard.
There were a few errors resulting from compiler bugs regarding the
type coercion of ?: ternary operators.  Since there were so few and
accomodation so minor, casts were added to get the build working.
On the virtual machine tested, the compiler hit a problem when the
debug build was used.  So -DNDEBUG was also necessary.
The motivation for this is primarily to examine the dependencies of
the build, to see if it can still be built on older and …
=> Build patches on HaikuOS for gcc 2.95

src/core/a-lib.c, src/core/b-init.c, src/core/e-func-symbols.c, src/core/l-types.c, src/core/n-io.c, src/core/p-file.c, src/core/t-date.c, src/core/t-pair.c, src/include/reb-defs.h, src/include/reb-gob.h, src/include/sys-globals.h, src/os/posix/host-time.c, src/os/windows/host-lib.c, src/tools/make-os-ext.r
There were two aspects to the "host kit".  One was a library for
calling Rebol services from C...the so-called Reb-Lib-Api, or "RL_API".
The obvious service was RL_Do_String(), which would LOAD and DO a
C string of UTF-8 text.
The other aspect was services provided by the host.  This covered
things such as getting the system time, starting processes, generating
UUIDs, etc.  Any time a platform-specific service was needed, a new
function would be added into the table that a host needed to provide.
(Note: One of the most generalized hooks was the provision of code
for creating requests for "rebol devices", and then polling or
dispatching to these devices.  This was similarly ad-hoc.)
Because Rebol was closed source, it was assumed that the code providing
the OS services did not have access …
=> Make Date host API fill a date REBVAL, not arbitrary struct

src/core/b-init.c, src/core/d-stack.c, src/core/l-types.c, src/core/m-gc.c, src/core/m-pools.c, src/core/m-series.c, src/core/n-function.c, src/include/sys-pair.h
When it was made possible for "singular" Rebol Arrays to hold a value
inside the REBSER node itself (and still act as terminated), this
made it more feasible to use these singular arrays as a way of
generically getting GC behavior for small REBVAL-sized items.  This
was used in places like function bodies, or to make a form of HANDLE!
that could participate in GC.
Another place where lifetime management for individual REBVAL-sized
things would be helpful is the external C API (or "RL_API").  Before it
spoke in terms of proxy REBVALs called "RXIARG"s which had no design
for their lifetime.  If the REBVALs used in the API lived inside of
something like a singular REBSER, they could participate in GC, and
have their lifetime attached to something like the lifetime of the
function frame that …
=> Working implementation of stack-frame GC'd pairings

src/core/m-gc.c, src/core/n-loop.c, src/include/sys-array.h, src/include/sys-series.h
In Ren-C, CONTINUE has a /WITH refinement.  The meaning of calling
CONTINUE/WITH a value is to do exactly the same thing as if the loop
body had finished normally and evaluated to that value:
>> map-each x [1 2 3] [if x = 2 [continue/with 666] x + 100]
== [101 666 103]
(Note: BREAK also has a /WITH refinement--instead of /RETURN--with a
similar semantic of acting like the body returned the value...it just
also stops the loop after that.)
The next rule is that a CONTINUE *without* a /WITH refinement acts
exactly like if the loop body had no result.  Hence if one desires
the following:
>> foo: [1 2 3]
>> remove-each x foo [either x = 2 [true] [continue]]
>> probe foo
[1 3]
...that implies that if the loop body of REMOVE-EACH evaluates to no
value, it is "opting out" of the removal.  Hence …
=> Tweak voids in REMOVE-EACH/"UNTIL", use data stack in MAP-EACH

src/boot/words.r, src/core/b-init.c, src/core/c-error.c, src/core/f-stubs.c, src/core/m-gc.c, src/core/m-pools.c, src/core/m-series.c, src/core/m-stacks.c, src/core/s-mold.c, src/core/t-function.c, src/core/t-routine.c, src/core/t-struct.c, src/include/mem-pools.h, src/include/reb-c.h, src/include/reb-gob.h, src/include/reb-struct.h, src/include/sys-action.h, src/include/sys-function.h, src/include/sys-handle.h, src/include/sys-rebser.h, tests/misc/qsort_r.r
The FFI implementation originally used dedicated C structures, which
were allocated from a specialized memory pool.  This required some
fairly invasive changes to the GC in order to put these structures
into the graph of "live" references for the system.  Because these
specialized structures had their own GC code, it was also not as
complete as the system's ordinary code...meaning deeply nested
structures could overflow the stack.
Rather than keep expanding or bulletproofing that approach, this moves
in the other direction to get rid of the specialized code.  The "REBRIN"
and "struct Reb_Field" have been turned into ordinary BLOCK!s, which
are candidates for further becoming ordinary OBJECT!s (with keylists).
This change allows all the FFI-oriented code to be removed from …
=> Unentangle FFI code from core GC, some GC streamlining

src/tools/make-natives.r
Previously the presence of a specification block was used to identify natives. As a result, syntax errors in the specification block would mean that the native was skipped by the parser.
An error will now be raised if a specification block cannot be loaded.
=> Specification blocks for natives are now required.

src/core/n-control.c, src/core/n-loop.c, src/mezz/base-funcs.r, src/mezz/mezz-save.r, tests/control/all.test.reb, tests/control/any.test.reb
R3-Alpha's logic for handling "unset!" in ANY and ALL was to consider
it neither true nor false.  Yet still, it would overwrite the output
if it was in the last position.
This gave a somewhat unusual smattering of results:
>> all [1 () 2]
== 2
>> all [1 2 ()]
;-- no value
>> all []
== true
>> all [()]
;-- no value
Ren-C formalized this to where voids would "opt-out", yet would always
return a value.  This made ANY and ALL safe to use in conditionals.
Yet it still was throwing away information (`all [1 2 ()]` was true,
not 2).  The damage this did to ALL's ability to act as a chaining
operation wasn't a good "optimization", so this changes that.
Yet another problem in chaining was that the `any [()] => false` and
`any [()] => true` concept made it not possible to chain the idea of …
=> ANY and ALL chain "opt-outs" (return void)...add ANY? and ALL?

src/core/a-lib.c, src/core/b-init.c, src/core/c-word.c, src/core/f-extension.c, src/core/f-series.c, src/core/f-stubs.c, src/core/m-gc.c, src/core/m-pools.c, src/core/n-crypt.c, src/core/n-native.c, src/core/n-system.c, src/core/t-block.c, src/core/t-routine.c, src/core/t-struct.c, src/core/u-compress.c, src/include/reb-ext.h, src/include/reb-struct.h, src/include/sys-handle.h, src/include/sys-rebser.h, src/include/sys-rebval.h, src/include/sys-series.h
When the FFI was added by Atronix, it was able to "image" a structure
schema on top of memory that was not owned by Rebol, and then poke and
peek values out of it.  This was used for reading data created by
a non-Rebol DLL without having to copy its memory into a Rebol
series first.
However, there was also a desire to have Rebol provide the memory
backing the structures.  So a special kind of series was added which
could have its memory not controlled by Rebol, or an "external series".
While it may be tempting to consider this as a general feature of the
system, the notion that all code has to be bulletproofed generically
against the idea of not owning a series pointer is daunting.  That
adds a lot of edge cases for which the system is not prepared--not to
mention a consistent processing …
=> Replace EXTERNAL series with HANDLE + LENGTH

src/core/n-control.c, src/core/n-data.c, src/core/n-function.c, src/core/n-io.c, src/core/n-reduce.c, src/core/t-struct.c, src/include/sys-do.h, src/mezz/mezz-legacy.r, src/mezz/sys-ports.r
The evaluator skips over BAR!s, so that DO/NEXT does not see them.
They are considered conceptually void and "opt-out", so that
**do [| | |]** is a void, **all [true | true]** is true and,
**any [false | false]** is false.
This raises the question of how they should be treated by a REDUCE
operation.  Originally, since a REDUCE was merely moving along in
DO/NEXT steps, they would be omitted from the result so that
**reduce [1 + 2 | 3 + 4]** would be **[3 7]**.  This change makes the
REDUCE itself preserve BAR!s, so it would be **[3 | 7]**.
In order to allow BAR!s to provide a structural check on SET operations
this extends SET to allow a BAR! in a position so long as it lines up
in the right position.  Hence you can write:
set [a | b] [1 + 2 | 3 + 4]
For compatibility, GET is changed to …
=> REDUCE leaves BAR! in blocks, SET and GET tolerate BAR!

src/boot/actions.r, src/core/c-path.c, src/core/t-function.c, src/core/t-map.c, src/mezz/base-funcs.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/mezz/prot-tls.r, src/mezz/sys-load.r, src/os/host-start.r
Previously void was being used to "opt out" of a function refinement.
This made it easy to write:
append/(if condition ['only]) blk data
This didn't seem very invasive because functions did not use ordinary
path dispatch.  However, it seems generally unsafe to ignore voids
in path processing and go on to the next path item.  Using blanks is
not all that much more code:
append/(all [condition 'only]) blk data
However, the interpretation of blanks in path selection needs to be
type specific, because they are legal "values" and hence legal anywhere
an ANY-VALUE! is legal, such as a key in a MAP!
m: make map! [_ 10]
m/_ ;-- should be 10
This keeps the interpretation of BLANK! as being up to the type, and
makes void trigger an error in any path selection or with SELECT.
=> Make void illegal in SELECT and path selection

src/tools/make-ext-natives.r
if error list in a extension is empty then this bug appears. rejoin was missing.
=> fix for make-ext-natives in case of empty error-list

src/boot/root.r, src/core/b-init.c, src/core/c-eval.c, src/core/c-function.c, src/core/n-control.c, src/core/n-function.c, src/core/t-string.c, src/core/t-typeset.c, src/core/t-varargs.c, src/include/sys-do.h, src/include/sys-typeset.h
After significant philosophical debate, it was determined that there
is likely no getting around the need for having a parameter class
which is evaluative like normal parameters, but stops evaluation at
the point of seeing a function which acquires its first argument from
the left hand side.
This convention was only seen in R3-Alpha in OP!.  However, Ren-C has
embraced functions which get their first argument from the left hand
side that do not wish to associate that with a difference in how they
gather their right hand arguments.  It also has a difference in
wanting to have operations which "defer" their lookback arguments,
e.g. the precedence manipulators:
x: 1
y: 2
z: (x + y <| print "Stuff" print "Afterward")
The <| wants `x + y` to fully evaluate, then run the successive
prints, then …
=> Legitimize the "tight" convention as new parameter class

src/core/b-init.c, src/core/c-context.c, src/core/c-eval.c, src/core/c-function.c, src/core/c-port.c, src/core/d-eval.c, src/core/d-legacy.c, src/core/f-extension.c, src/core/m-gc.c, src/core/m-stacks.c, src/core/n-function.c, src/core/n-native.c, src/core/t-routine.c, src/core/t-varargs.c, src/core/u-parse.c, src/include/sys-frame.h, src/include/sys-function.h, src/include/sys-rebfrm.h, src/include/sys-rebser.h, src/include/sys-rebval.h, src/os/host-main.c
This is a change designed to permit flexibility in rewriting the
parameter conventions of function compositions.  The need was first
imagined with REDESCRIBE (to create adaptations and specializations
with more restrictive type conventions than the functions they were
composing, such as a specialization of APPEND that would only work
on STRING! series).  Yet the technical difficulty of actually
doing such a transformation wasn't seen until TIGHTEN tried to change
the parameter conventions of an arbitrary composition.
Now it is possible to TIGHTEN any function, including chains and
specializations and adaptations.  It can do this without needing to
copy or rebind the function body, and the resulting new function will
not add any runtime overhead beyond what the original cost.  It paves
the …
=> Simpler/Better "Facade" (e.g. can use TIGHTEN on any function)

src/core/c-error.c, src/core/c-value.c, src/core/d-eval.c, src/core/l-types.c, src/core/t-varargs.c, src/os/host-main.c, src/tools/r2r3-future.r
When the evaluator is called, it is given the memory address of where
the result value is to be written.  This address is known to the frame,
and the list of frames is known to the garbage collector--which allows
this arbitrary location in memory to keep any series it refers to
during the evaluation alive.
One issue with this that had not been addressed was what would become
of the bit pattern at that location in the event of an evaluation
that did not finish.  This could happen either due to a fail() partway
through, or something like a Ctrl-C.
This formalizes the decision such that an END marker is written into
every output slot when unwinding the frame stack, up to the level
that traps it.  A reason for choosing END instead of trash is because
the slot may be a function local which is …
=> fail() clears partial outputs, fix Ctrl-C Heisenbug in console

src/core/c-context.c, src/os/host-main.c, src/os/host-start.r
When the REPL was moved into userspace code, it used routines like
PRINT for I/O, etc.  This meant redefining any of those constructs
would break the REPL--consequently breaking `<r3-legacy>`
In the absence of an obvious ideal solution, this does the easy thing
and just binds the host r3.exe's startup and REPL code into lib.
=> Put REPL and host startup code into lib, not user

CREDITS.md, make/CMakeLists.txt, src/codecs/sha256/sha256.c, src/codecs/sha256/sha256.h, src/extensions/mod-crypt.c, src/tools/file-base.r
This is a simple SHA256 hasher which will take either a BINARY! or a
STRING!.  Strings will be UTF-8 encoded before the hash.
Returns a 32-byte binary.  C code used for the hash comes from:
http://bradconte.com/sha256_c
=> Add SHA256 hashing native to cryptography module

tests/lib/text-lines.reb, tests/source-tools.reb, tests/source/analysis.test.reb
Adds source analysis checking for Rebol source files and adds detection of inconsistent line termination.
At the time of this PR, running run-recover.r with these changes caused the assetion documented here: https://github.com/metaeducation/ren-c/issues/468
=> R source tests

tests/lib/text-lines.reb, tests/source-tools.reb
I.e. this check is moved from the C analyser to the Text analyser, which will encompass Rebol code.
=> Check for end of file newline for all text formats.

src/mezz/sys-load.r
* `import 'foo` searches first in local modules,
then falls back to rebol/locale/library
* `import <foo>` searches only in rebol/locale/library
=> IMPORT 'FOO falls back to IMPORT <FOO>

src/boot/errors.r, src/core/l-scan.c, src/core/s-mold.c, src/include/sys-scan.h, src/os/host-repl.r
The scanner had a uniform means of delivery, so that particular kinds
of scan errors were not getting distinct identities or arguments.
This is a first cut at changing the approach so that any particular
error could be given a unique identity if needed.
The main motivation was to get better discernment of cases like:
load "[ abc"
load "[ abc )"
load "abc ]"
Only cases like the first can be resolved by more input, so the
usermode REPL will keep allowing more typing when errors of that form
occur, but not the others.  This resolves bugs that were related to
not being able to distinguish cases, in particular of open strings.
This is only a first step, with the intention to allow the scan state
to be processed in a stack to provide a complete list of the tokens
which are outstanding.
=> Finer-grained errors from scanner, detect mismatched delimiters

src/boot/sysobj.r, src/os/host-repl.r, src/os/host-start.r
Synopsis...
* `system/user` object resurrected!   
* `system/user/home` is now set to the contents of HOME env variable on Rebol startup.
* New `system/user/rebol` field which is set to local user rebol directory (if found under `system/user/home`).
* New `system/repl` object containing properties & code for skinning repl.
* On REPL start-up it will load `%repl-skin.reb` if found in `system/user/rebol` directory.
Here is an extreme example of customising REPL using `%repl-skin.reb` :)  https://gist.github.com/draegtun/83ae0cd3307eb20ee010d8949121c4ba
Currently there are 3 types of *hooks* which can be changed in the REPL...
* shortcuts - Lookup word entered in `system/repl/shortcuts` object and transforms it to what it maps to.  
```
>> ;;  Q and LIST-SHORTCUTS are two predefined …
```
=> Added REPL object to allow skinning

src/core/c-eval.c, src/core/m-gc.c, src/include/sys-array.h, src/include/sys-function.h, src/include/sys-value.h, src/tools/make-make.r
This does some performance improvement of the debug build in general,
along with making it so that the debug build with asserts w/o symbols
uses the optimizer.  (There's not much reason not to use an optimized
build if it's un-debuggable due to lack of symbols...)
Performance improvements were based on noticing spikes in callgrind,
largely related to function facade macros being called often, and
the bit testing in GET_VAL_FLAG being excessive.  This changes to
just check that GET_VAL_FLAG is on a value whose raw type is > REB_0
and <= REB_MAX...which should catch cell-based ends, trash, and most
non-cell-based ends.
=> Improve performance with DEBUG=asserts, including -O2

src/os/host-repl.r, src/os/host-start.r
Following on from #475 I've made the following changes:
* Created a `repl!` object.   NB. @hostilefork - This is defined in `host-start.r`.  If there is a preferred place then I can update in next round of REPL changes.
* If last expression in `%repl-skin.reb` is a `repl!` object then this will update `system/repl`  - @zsx 
Here's a %repl-skin.reb example showing the new way to skin REPL:
Rebol []
?: :help
make repl! [
;; switch off gap but print newline after a result
print-gap: _
print-result: proc []  [print unspaced [result last-result | ]]
]
* `r3 -q` now doesn't print `REPL skinning` -  @giuliolunati 
* `print-error` method added -  @giuliolunati 
* `print-info` method added.   NB.   try `1 / 0` to see its effect :)
What I'm looking at next...
* Refactor repl! object bit more - @zsx …
=> REPL - simple fixes and refactoring

src/boot/sysobj.r, src/os/host-console.r, src/os/host-start.r, src/tools/make-host-init.r
This PR changes all (relevant) references of REPL to CONSOLE.  
Some pertinent info:
* `HOST-CONSOLE` & `host-console.r` are the new function! and filenames used.
* `console!` replaces `repl!` object.
* `%console-skin.reb` is new name for skin file (`%repl-skin.reb` is defunct).
So `%console-skin.reb` must end in a `console!` object for it skin the console: 
Rebol []
make console! [
prompt: ">>> "
result: "=== "
]
The REPL is dead.  Long live the CONSOLE :)
=> REPL renamed to CONSOLE

src/boot/sysobj.r, src/os/host-start.r
I believe take 2 of https://gist.github.com/draegtun/f37e0c15afbe1ba1c66527299510a020
is the most logical choice as it brings us closer to what Rebol 2 does/did on `system/options` & `system/user`
So this PR implements a first step towards that...
* `system/options/home` - [CHANGE] Now gives user HOME directory.  Same as Rebol 2 and matches Rebol 3 documentation.  
* `system/options/bin` - [NEW] Directory path where r3 executable binary lives (this is what `system/options/home` was showing previous to this PR
* `system/options/resources` - [NEW] Local user resource directory found under `system/options/home`.   NB. This is where things like `%console-skin.reb` are kept.
NB.  if `/home` or `/resources` cannot be resolved or found at boot then they will be set to `_`
* `--resources …
=> Fix system/options/home + other related changes

src/boot/sysobj.r, src/os/host-start.r
`%user.r` is resurrected!
* `%user.r` is loaded if found under `system/options/resources` directory.
* This is a change to Rebol 2 (looks first in current directory and then directory where r3 executable lives) and the Rebol 3 docs (looks first in `system/options/home` and then in current directory).
* There is nothing special about how it runs/loads `%user.r` (ie. doesn't pick up last expression ala `%console-skin.reb`).  So if you want to set anything in `system/user` then it needs to be:
system/user/name: "Bazza"
* New `--suppress` command-line switch
r3 --suppress "%console-reb.skin"      # stops skinning
r3 --suppress "%rebol.r %user.r"       # stop both these files loading
r3 --suppress "*"               # suppresses %rebol.r, %user.r & %console-skin.reb
* `system/options/suppress` …
=> Added back %user.r start-up script

src/tools/make-make.r
Useful for setting cross-compiling:
e.g.
TOOLS="$ANDROID_TOOLCHAIN_PREFIX"
TOOLS_CC_FLAGS="--sysroot="$ANDROID_PLATFORM_SYSROOT"
=> Add optional TOOLS_CC_FLAGS env var

src/os/host-start.r
see: #499 
Any evaluation errors found in`%rebol.reb` or `%user.reb` startup scripts will now fail gracefully.
Example of a bad `%user.reb` file:
Rebol [
title: "my user.reb"
file: %user.reb
version: 0.0.1
date: 11-May-2017
]
xxx
When `r3` is run this produces following output:
Script: my user.reb Version: 0.0.1 Date: 11-May-2017
Startup encountered an error!
** Error found in user.reb script
!! use --verbose for more detail
Doing `r3 --verbose` produces following output:
...
... culled other verbose messages...
...
Script: my user.reb Version: 0.0.1 Date: 11-May-2017
Startup encountered an error!
** Error found in user.reb script
** Script Error: xxx has no value
** Where: do catch either either --anonymous-- do trap if if --anonymous--
** Near: ... make object! [
[self: title name type …
=> Added DIE, a graceful way to FAIL in host-start

.travis.yml
1. FFI is disabled
because libffi should be compiled with -f PIC
2. TCC is disabled
because I'm lazy
=> Add Android5 (0.13.2) to Travis builds

src/boot/sysobj.r, src/os/host-start.r
This is what the console start-up now looks like (example):
Rebol 3 (Ren/C branch) [version: 2.102.0.2.5 build: 12-May-2017/13:25:34]
Welcome to the Rebol console.  For more information please type in the commands below:
HELP    - For starting information
ABOUT   - Information about your Rebol
CHANGES - What's different about this version
>>
Typing ABOUT will bring up full banner previously displayed before this PR.  
To see it on startup use `r3 --about` command-line switch.
NB. CHANGES is just a stub at moment (console shortcut)
Ref: See last comments in #502
=> More lightweight banner/intro to Console

src/os/host-console.r, src/os/host-start.r
Tidied verbose output by:
* Removing printing of `system/options`
* Added start-up script confirmation (%rebol.reb & %user.reb)
* Added message on start of Console code
Example of `r3 --verbose` with `%rebol.reb` & `%user.reb` start-up scripts present:
Loading boot extensions...
Checking for rebol.reb file in /Users/barry/code/GitHub/ren-c/make/
Script: MyRebolReb Version: Date:
Finished evaluating script: /Users/barry/code/GitHub/ren-c/make/rebol.reb
Checking for user.reb file in /Users/barry/.rebol/
Script: my user.reb Version: 0.0.1 Date: 11-May-2017
Finished evaluating script: /Users/barry/.rebol/user.reb
Starting console...
Rebol 3 (Ren/C branch) [version: 2.102.0.2.5 build: 12-May-2017/18:31:21]
Welcome to the Rebol console.  For more information please type in the commands below: …
=> Host-start --verbose changes

CHANGES.md, src/os/host-start.r
* see http://keepachangelog.com/en/0.3.0/
* CHANGES console shortcut now jumps to version anchor in CHANGES.md
=> Convert CHANGES.md into CHANGELOG format

src/os/host-start.r
- Tightened what to-dir, get-home-path & get-resources-path can return
- Have to cover that exists? returns word `file` or `dir`
Fixes #523
=> Return from helper functions needed fixing

src/core/c-path.c, src/core/d-print.c, src/core/l-scan.c, src/core/p-event.c, src/core/s-mold.c, src/core/s-unicode.c, src/core/t-gob.c, src/core/t-integer.c, src/core/u-parse.c, src/os/posix/host-readline.c, src/tools/file-base.r, src/tools/make-make.r
GCC 7 will have -Wimplicit-fallthrough turned on by -Wextra. There are a
number of ways to inform the compiler that falling through is intended.
This commit just uses the comment to do that, which is the most
conservative (least destructive) way: if the compiler doesn't recognize
it, nothing's gonna be broken.
=> Add "falls through" comments

tests/call/call.test.reb, tests/call/print.reb, tests/core-tests.r
Tests CALL by running external Rebol program and checking expected output.
There are currently 3 tests:
- Expect 100 bytes back - PASSES
- Expect 9000 bytes back - FAILS
- Expect 80,000 bytes back - CRASHES
This PR is part of Issue #537 so hopefully can fix last two failing/crashing tests.
=> Platform independent tests for CALL

src/core/b-init.c, src/core/c-eval.c, src/core/n-system.c, src/include/sys-globals.h
The debug version of the interpreter keeps tracking of a do_count, and
can raise a break signal at a given do_count point before evaluating the
expression. This is very useful for debugging the evaluator, however,
it can only break at a hardcoded point, which means it needs to be
recompiled after changing; moreover, it's very hard to find out the
do_count to break.
This commit adds a rebol function to set such a break point, no
recompilation is needed, and multiple breaking points can be set. When
the function is called, it will break at next point, in next x points
by using /skip, or at an certain point by using /at
e.g.
c-break-debug
a: 1
will make it break in Do_Core right before evaluating "a: 1"
=> Add a native to set C break point

tests/call/call.test.reb
- `git log` only runs if git binary found
- Only %/usr/bin/git is checked.  More paths could be added
- This test will probably only run on Linux & Mac OSX (maybe Cgywin Windows?)
- Returns TRUE if test not run (no way found to skip test)
=> CALL/OUTPUT Test - Platform independence change

src/tools/make-zlib.r
Fixes syntax and the URL update avoids the redirect issue, so it works properly without manually downloading/cloning ZLIB files.
=> Fix syntax changes for %make-zlib.r

src/mezz/sys-load.r
Allows the following NEEDS form in modules:
```
Rebol [
Title: "Some Script..."
Needs: [<json>]
]
```
=> Permit references to modules by tag in NEEDS header.

src/core/c-eval.c, src/core/n-data.c, src/mezz/base-funcs.r, tests/control/if.test.reb
This changes the logic of how the evaluated/unevaluated bit is done
such that groups don't affect it.  Hence `(1 2 3)` would come back
with 3 and consider it to be "unevaluated", while `(1 + 2)` would
give back a 3 and consider it evaluated.
This means that should IF not welcome evaluated integers and you need
to subvert that, you can write `if condition (semiquote do [1 + 1])`.
Otherwise you're forced to write `if condition semiquote do [1 + 1]`.
This would limit the caller's flexiblity of grouping for readability.
However, putting a value in a GROUP! was the previous way of forcing
the evaluated bit onto things.  Rather than introduce a SEMIEVAL
function, this observes that really what SEMIEVAL is is the Identity
Function:
https://en.wikipedia.org/wiki/Identity_function …
=> Add IDENTITY, have GROUP! not affect VALUE_FLAG_UNEVALUATED

src/core/c-eval.c, src/include/sys-rebfrm.h, src/mezz/mezz-series.r, src/mezz/sys-codec.r, src/os/host-start.r
When an enfixed function has a "normal" (non-tight) first argument,
the initial implementation would hold lookahead in a suspended state,
leading to full completion of arguments on the left hand side.
This "full" completion led to undesirable effects, such as ELSE's
"Dark Corner".  For instance:
print if false ["a"] else ["b"]
This would be interpeted as `(print if false ["a"]) else ["b"]`  This
is because when ELSE was first seen, it would be immediately after the
["a"] had been written into the output cell of IF's frame, creating a
situation like this with IF and PRINT on the stack above:
print>if> *D_OUT* else ["b"]
Rather than take the D_OUT as its left hand side (the way a tight
argument would), it would yield...allowing the expression which had
requested one argument evaluation …
=> Limit Left-Hand Enfixed Normal Fulfillment to "one expression"

src/boot/types.r, src/core/n-data.c, src/mezz/base-funcs.r, src/mezz/base-infix.r, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r, tests/datatypes/op.test.reb
This consolidates the two names for making functions that get their
first argument from the left under the single term "enfix", as it is
the more user-facing concept...while lookback is more of an internal
detail of the evaluator.
For full discussion, see:
https://forum.rebol.info/t/214/8
This commit also deletes some superfluous helpers like SET-INFIX and
SET-POSTFIX which were conveniences introduced prior to ENFIX's
existence (or before it could have existed, due to no left quoting
in enfixed functions).
Several comments are also brought up to date.
=> Rename SET/LOOKBACK to SET/ENFIX, LOOKBACK? to ENFIXED?

src/mezz/mezz-files.r, src/mezz/mezz-legacy.r, src/mezz/mezz-math.r, src/mezz/mezz-secure.r, src/mezz/mezz-series.r, src/os/host-start.r, src/tools/make-boot.r, src/tools/make-ext-natives.r, tests/atronix/ms-drives.r, tests/atronix/test-libs.r, tests/datatypes/closure.test.reb, tests/datatypes/function.test.reb, tests/misc/fib.r
The ++ and -- operators were not used very frequenty in Rebol, due to
their "non-Rebol" appearance.  They were prefix, would modify their
argument (quoted as a WORD!), and would return the prior result.
>> x: 10
>> -- x
== 10
>> x
== 9
To a casual observer, it was not clear that x was being modified...
especially because it wasn't even being passed as a WORD!.  A proposal
favored by @gchiu and @earl was that it might better be an
arity-2 infix operator which would quote its left hand side, and
allow incrementing or decrementing by any amount.  (Hence more like
C's += and -=)
>> x: 10
== 10
>> x: ++ 3 * 3
== 19
>> x: -- 2
== 17
>> t: 12:00
== 12:00
>> t: ++ 3:00:42
== 15:00:42
>> s: [a b c d]
== [a b c d]
>> s: ++ 2
== [c d]
If one wished for simple incrementing or decrementing, it doesn't …
=> Enhance increment (++) and decrement (--) operators

src/mezz/base-infix.r
For reasons of visibility, Perl6 chose to use ?? and !! instead of
? and : for a ternary operator:
https://docs.perl6.org/language/operators#infix_??_!!
This actually does appear to look better than the ? and ??.  Consider:
1 > 2 ? [a] ?? () ?? () ?? [x] ?? () ?? [y]
1 > 2 ?? [a] !! () !! () !! [x] !! () !! [y]
The operator stands out better in the second case, and is more clearly
differentiated.  With agreement from @draegtun, this makes the change
for Ren-C.
(Note that ?? and !! are not generic replacements for IF and ELSE.
If you write `condition ?? 1 + 1 !! 2 + 2` then both additions will
be run, since to "block" an evaluation there must be a BLOCK!
involved.  So while evaluation is allowed, if you use it, note that
they are ordinary function parameters and both will be evaluated.) …
=> Use ?? and !! instead of ? and ??...make ? a SET? test

src/core/c-eval.c, src/core/n-control.c, src/core/n-loop.c, src/include/sys-action.h, src/include/sys-do.h, src/mezz/base-funcs.r
This changes Run_Branch_Throws() to also take the condition which
triggered the branch.  This way, if the branch is an arity-1 function,
that condition can be provided as a parameter to the function:
>> if false func [x] [print x | 304]
;-- no result
>> if 1020 func [x] [print x | 304]
1020
== 304
It works with loops like WHILE as well, should the body be an arity-1
function, as well as all the conditionals like CASE, THEN, ELSE...
SWITCH is a little odd because there's no such thing as a function
literal, but if you compose a function into the cases block it will
currently do the same thing.
>> switch 1 compose [1 (func [x] [print x])]
1
== _
Also, with "blankification" more uniform as a process, this moves it
into the handler for Run_Branch_Throws() to reduce repetition.  As a
result, …
=> Arity-1 Function Branches receive conditional arguments

src/mezz/base-funcs.r, src/mezz/mezz-legacy.r, src/mezz/mezz-secure.r, src/mezz/mezz-series.r, src/mezz/sys-base.r, src/mezz/sys-load.r, src/os/encap.reb, src/tools/make-ext-natives.r, src/tools/r2r3-future.r
Ren-C changed SET-WORD!-based assignments to allow voids without error.
x: () ;-- legal
There were numerous advantages to allowing this, though it did remove
one potential "safety" check.  So ENSURE was introduced:
>> x: ensure 3
== 3
>> x: ensure () ;-- error
Though in a type-unsafe system, it's hard to say how a variable being
void is that much worse than if it's an integer and you were expecting.
So a "test dialect" started emerging.  This led to two different
rity-2 constructs: MAYBE and ENSURE
>> x: ensure [integer! string!] "hi"
== "hi"
>> x: ensure [integer! string!] <some-tag> ;- error
>> x: maybe [integer! string!] "hi"
== "hi"
>> x: maybe [integer! string!] <some-tag>
== _
Hence MAYBE and ENSURE were parallel functions, one of which would pass
through values that matched the …
=> ENSURE => REALLY, restoring ENSURE to original concept

.travis.yml, src/core/c-context.c, src/core/c-eval.c, src/core/c-function.c, src/core/d-stack.c, src/core/f-stubs.c, src/core/m-gc.c, src/core/n-do.c, src/include/sys-frame.h, src/include/sys-rebfrm.h, src/include/sys-value.h, src/tools/make-make.r, tests/control/apply.test.reb, tests/functions/specialize.test.reb, tests/pending-tests.r
A concept tried in Ren-C early on was that when you create a frame via
MAKE FRAME! :SOME-FUNCTION, the frame context would be used directly
for the instance of the function call.  The frame's variables would not
be copied when you would DO it--actual heap-based context fields would
be used--as opposed to pushing new stack-based variables and copying
the MAKE'd frame's fields into them.
This turned out to be a bad idea for several reasons.
For one thing, the person who built the FRAME! and is DO-ing it now has
access to the state of the frame after the function has finished.
Rebol functions make no promises about the values of their arguments at
the end of execution...they only promise a return value.  But by using
the FRAME! that the caller had built directly, a non-debug caller can
see …
=> DO of FRAME! copies vars for instantiation, FRAME! fixes

src/mezz/mezz-legacy.r, tests/series/rejoin.test.reb
The original implementation used JOIN-ALL, but JOIN-ALL does not tolerate () which are not in the first position of the block because it is based upon REDUCE.
Reduction in REJOIN needs to be tolerant of () at any position in the block. So I decided to implement a tolerant reduction as part of this implementation of REJOIN.
This implementation and tests are meant to behave as R3 Alpha does.  However, the behaviour of REJOIN look odd when examining some of these test cases. An argument could be made for simplifying REJOIN's behaviour.
I welcome review and update of this implementation to reflect any opportunities that Ren-c offers to make it simpler.
=> Fix REJOIN bug and add REJOIN tests.

src/core/n-native.c, src/core/s-mold.c, src/core/t-function.c, src/core/t-routine.c, src/include/sys-context.h, src/include/sys-rebser.h, src/include/sys-value.h, src/os/host-main.c, tests/functions/specialize.test.reb
The concept of a FRAME! is to enable the representation of a state of
a Rebol function invocation (or a potential invocation) of a Rebol
function, or specific invocation, as a context that resembles OBJECT!.
Not only is this useful in debugging, but in the design of custom
APPLY-like operations.
That model is complex to simulate for the user, because the operations
that do function compositions (SPECIALIZE, CHAIN, ADAPT, HIJACK...)
don't actually create distinct stack frames to run their code.  This
gives them a significant performance advantage over methods which would
rewrite the bodies of functions or otherwise execute more retriggering
levels.  An adaptation of a specialization of an adaptation of a
specialization would find each adaptation layer "perceiving" a
different number of …
=> Specialization uses facades to suppress hidden keys in frames

src/core/n-data.c, src/core/n-loop.c, src/include/sys-word.h, src/mezz/base-funcs.r
The R3-Alpha implementation of USE would build a closure (indefinite
extent lifetime for its arguments, refinements, and locals) based on
the given spec.  Then it would DO that function.
There's an inefficiency in this, because it constructs a function, that
takes time and also makes entities that need to be GC'd, when that
function is to be called only once.
This reduces the overhead of USE significantly by making it a native
and reuses the same code that copies and rebinds bodies of loops.
This helps USE not be specifically tied to the behavior or decisions
regarding indefinite or definite lifetimes in functions.  It also
puts the decision closer to behaviors which would be able to take
advantage of working virtual binding.
=> USE=>native: performance + decouple from "closure" semantics

src/boot/errors.r, src/core/m-pools.c, src/core/m-stacks.c, src/core/n-loop.c, src/include/sys-do.h, src/include/sys-frame.h, src/include/sys-rebfrm.h, src/include/sys-rebser.h, src/include/sys-rebval.h, src/include/sys-series.h, tests/control/remove-each.test.reb
The REMOVE-EACH primitive was unusual because it would perform mutation
on the very series it was iterating, based on the results of calling
into arbitrary user code.  This gives rise to a category of problems,
one very simple one being:
data: copy [1 2 3 4]
remove-each item data [
protect data
true
]
Since user code can transition a series from being mutable to being
immutable, this meant there'd have to be a check of whether that had
changed on every step of the REMOVE-EACH.  This isn't the only problem,
but it demonstrates the slippery slope one starts to be on if the
attempted answer is to add a "did-the-protection-status-change" test
on every loop iteration.
The need to constantly keep the input array in sync with the removals
also presented a performance problem, because each …
=> REMOVE-EACH locks series until end, performs all removes atomically

src/core/b-init.c, src/core/c-eval.c, src/core/c-function.c, src/core/d-trace.c, src/core/n-do.c, src/core/n-loop.c, src/core/n-system.c, src/include/sys-do.h, src/include/sys-globals.h, src/include/sys-rebfrm.h
Ren-C reimagined the evaluator in terms of acting on a C structure that
reflects the run state (a "REBFRM"), which could then be tied to a
Rebol value that introspected it (a "FRAME!").  This meant that the
entire evaluator was--effectively--a void function taking a single
parameter.  This function is called Do_Core().
One consequence of this is that the evaluator can be swapped out...
most likely for another evaluator that augments Do_Core() but uses it
as part of the implementation.  These augmentations could add tracing,
statistics, or debugging features.
Historically TRACE was implemented by setting Trace_Flags, and then the
choice to output trace information was made by doing `if (Trace_Flags)`
multiple times in the Do_Core() routine.  This commit institutes a new
strategy: to make …
=> Make core DO and APPLY actions hookable, implement TRACE as hook

scripts/changes-file/changes-file.reb, scripts/changes-file/cherry-pick-map.reb, src/boot/errors.r, src/boot/root.r, src/core/b-init.c, src/core/c-function.c, src/extensions/locale/ext-locale-init.reb, src/include/sys-bind.h, src/include/sys-function.h, src/include/sys-typeset.h, src/mezz/base-funcs.r, src/mezz/mezz-legacy.r, src/mezz/mezz-math.r, src/mezz/mezz-secure.r, src/mezz/mezz-series.r, src/mezz/prot-tls.r, src/mezz/sys-load.r, src/os/host-console.r, src/os/host-start.r, src/tools/make-zlib.r, src/tools/r2r3-future.r, src/tools/rebmake.r, tests/comparison/equalq.test.reb, tests/comparison/sameq.test.reb, tests/comparison/strict-equalq.test.reb, tests/context/bind.test.reb, tests/core-tests.r, tests/datatypes/closure.test.reb, tests/datatypes/function.test.reb, tests/datatypes/object.test.reb
Ren-C originally aimed to bring the features of CLOSURE! to all
FUNCTION!s at "acceptable cost".  This was partially achieved with
specific binding, and with the ability to use non-reified stack frames
as "specifiers" the costs are hopefully becoming very low for that
binding property (and will be extended to other binding forms).
The second property of CLOSURE! was the indefinite lifetime of all
arguments and locals after the function call.  This was costly, and
entailed making a deep copy of the body of the function on every
invocation.  Ren-C managed to remove the need for that copy, but still
the idea of creating a GC-tracked object for *all* the locals and
arguments in each invocation was heavy-handed.
With implementation techniques getting more sophisticated, the burden
was …
=> Remove CLOSURE and `<durable>`, `<has>` back to `<static>`

src/core/a-lib.c, src/core/c-error.c, src/core/c-eval.c, src/core/c-function.c, src/core/d-break.c, src/core/d-dump.c, src/core/d-eval.c, src/core/d-stack.c, src/core/d-stats.c, src/core/d-trace.c, src/core/m-gc.c, src/core/m-stacks.c, src/core/n-do.c, src/core/n-function.c, src/core/t-varargs.c, src/core/u-parse.c, src/extensions/ffi/t-routine.c, src/include/sys-context.h, src/include/sys-frame.h, src/include/sys-rebfrm.h
Historically, there has been a symbol --anonymous-- which was used in
slots where a function name might appear but there isn't a relevant
one. For instance:
takes-int: func [x [integer!]] [...]
do compose [(:takes-int) #not-an-integer]
The error message would say "--anonymous-- does not allow ISSUE! for its
x argument", with the WORD! --anonymous-- fabricated as the parameter
to the error.
Under this scheme, there's no way when interpreting the error/etc.
as talking about a function whose name is *actually* --anonymous-- vs.
one that has been made up.  It also feels rather sketchy to be writing
`label = '--anonymous--` as that test ("wait, how many dashes was it?")
This commit switches to actually having the stack frames distinguish
between having a symbol and not, and when reflecting the …
=> Discern anonymous functions from ones named --anonymous--

src/core/b-init.c, src/core/c-bind.c, src/core/c-context.c, src/core/c-function.c, src/core/f-blocks.c, src/core/n-data.c, src/core/n-loop.c, src/core/n-protect.c, src/core/t-object.c, src/include/sys-bind.h, src/include/sys-rebser.h, src/include/sys-rebval.h, src/include/sys-value.h, tests/control/for-each.test.reb
This change allows a LIT-WORD! to be passed to loops, e.g. FOR-EACH,
and signify that an existing variable should be assigned instead of
a new variable and binding.  So:
>> x: 10 | for-each 'x [1 2 3] [print x] | print x
1
2
3
3
This contrasts with (and is faster than) WORD!, which generates a new
variable and will currently deep copy and rebind the body to that new
variable:
>> x: 10 | for-each x [1 2 3] [print x] | print x
1
2
3
10
(Note that as of time of writing, Red has chosen the LIT-WORD! semantic
for regular WORD!s--a breaking change from historical Rebol.)
If multiple variables are specified, e.g. `for-each [x 'y z] ...`, then
each individual variable will be handled according to the WORD! or
LIT-WORD! status.  Presently this means that if any ordinary WORD! are
used, then the …
=> LIT-WORD! passed as loop variable reuses existing binding

src/core/c-context.c, src/core/c-error.c, src/core/c-function.c, src/core/f-stubs.c, src/core/m-gc.c, src/core/m-pools.c, src/core/m-stacks.c, src/core/n-function.c, src/core/t-block.c, src/core/t-function.c, src/core/t-library.c, src/core/t-object.c, src/extensions/ffi/t-routine.c, src/include/sys-array.h, src/include/sys-context.h, src/include/sys-frame.h, src/include/sys-function.h, src/include/sys-library.h, src/include/sys-rebser.h, src/include/sys-rebval.h
There are two spare platform-pointer-size fields in every REBSER node
which are used for various purposes, depending on the role of that
node.  The early development of the "meta" feature would use one of
the fields on the *keylist* of objects to store the pointer to the
ANY-CONTEXT! to serve as the meta object.  But since keylists may be
shared between object instances, this didn't allow different object
instances with shared keylists to have distinct meta object.
This moves the meta link to the varlist to solve that problem.  But
that raised another issue where although FRAME! was an ANY-CONTEXT!, it
was using the varlist slot for an important shared property--namely
the reverse link to the C struct representing an active call frame,
which needed to be NULLed out in the series node so …
=> SET-META individually on ANY-CONTEXT! (including FRAME!)

src/core/b-init.c, src/core/l-scan.c, src/core/t-block.c, src/include/sys-scan.h, src/include/sys-word.h, src/os/host-main.c
Because of the careful choices made in arranging the bits of headers of
Rebol values, it's possible to know from examining the first byte of
a void pointer whether it is a UTF-8 string or a REBVAL*.
This adapts the scanner to be able to accept a feed of pointers to
UTF-8 strings and Rebol values (as opposed to just one UTF-8 pointer).
If a value is encountered in-between tokens, that value will be
"spliced" into the scan.
Currently this can be used to construct arrays, such as in this code:
REBVAL *item1 = ...;
REBVAL *item2 = ...;
REBVAL *item3 = ...;
REBSTR *filename = ...; // where to say code came from
REBARR *result = Scan_Va_Managed(filename,
"if not", item1, "[\n",
item2, "| print {Close brace separate from content}\n",
"] else [\n",
item3, "| print {Close brace with content}]\n", …
=> Make source scanning accept a va_list for splicing in REBVALs

src/core/a-lib.c, src/mezz/mezz-files.r, src/os/host-console.r, src/os/host-main.c, src/os/posix/host-readline.c, src/os/windows/dev-stdio.c
The very old/crufty R3-Alpha POSIX termios-based code was considered to
be only a temporary codebase to be replaced with something better.  No
truly suitable replacement has been found, so this commit bites the
bullet and pushes the existing code to make it more tolerable.
It now supports UTF-8 entry...although the cursor-oriented commands
need to be updated to account correctly for multibyte characters.
Though those cursor commands are unfinished, it is still a significant
improvement.
It also supports multiline pasting.  This was inspired by a patch
submitted by @Oldes as a proof of concept (and the provocation for
this reworking).  Consequently hitting enter on an empty line no longer
terminates in-progress multiline input with an error message.
The way to cancel REPL input is now to …
=> POSIX console UTF8, multiline paste, escape/cancel INPUT

src/core/a-lib.c, src/core/d-crash.c, src/core/n-do.c, src/os/host-console.r, src/os/host-main.c, src/os/windows/dev-stdio.c
The HOST-CONSOLE code is called directly from C code, as the topmost
level of evaluation.  So one problem with situations where running
the console raises an error is that there's nowhere to escalate that
error to... *the console is supposed to be the way errors are delivered
and values are probed*.  So a bug in the console basically means the
whole program has to crash out.
This makes the console a bit tough to debug.  With the extensive
usermode skinning added by @draegtun, the potential for errors being
triggered or infinite loops arises even more.  This makes crashes
likely while developing usermode skins.
To address this problem, this commit introduces a new concept of the
HOST-CONSOLE function being able to ask the C code calling it to run
code *on its behalf* as opposed to *on the …
=> Sandbox HOST-CONSOLE calls into usermode code, disable Ctrl-C

src/core/a-lib.c, src/core/d-trace.c, src/os/host-console.r, src/os/host-main.c, src/os/host-start.r, src/tools/make-host-init.r
The HOST-CONSOLE function has been receiving a LAST-RESULT value, as
well as a LAST-FAILED value...in order to print out the result of the
last execution request.
In the previous commit, HOST-CONSOLE was allowed to return either a
GROUP! or a BLOCK! to be executed, with a BLOCK! being interpreted as
an implementation sandboxing that the console was using on its own
behalf...vs. user code.  Failures when asking to execute a BLOCK!
could then be more severe, causing the console to reset the skin to
try and salvage a working REPL.  It was important to know whether the
previous request came from a BLOCK! or a GROUP!, so the LAST-FAILED
status became more complex to try and encode that information.
This changes that to just pass a third value in to each iteration of
the HOST-CONSOLE loop... …
=> Unify startup code into HOST-CONSOLE, fix command line cancellation

src/boot/errors.r, src/boot/words.r, src/core/a-constants.c, src/core/a-lib.c, src/core/b-init.c, src/core/c-error.c, src/core/c-eval.c, src/core/c-function.c, src/core/c-value.c, src/core/d-crash.c, src/core/d-dump.c, src/core/d-eval.c, src/core/m-pools.c, src/core/m-series.c, src/core/n-data.c, src/core/n-do.c, src/core/n-system.c, src/core/u-parse.c, src/include/reb-defs.h, src/include/sys-do.h, src/include/sys-frame.h, src/include/sys-globals.h, src/include/sys-rebfrm.h, src/include/sys-rebser.h, src/include/sys-rebval.h, src/include/sys-series.h, src/include/sys-trap.h, src/include/sys-value.h, src/os/host-console.r
The "C-DEBUG-BREAK" native is helpful for interrupting evaluation to
kick into the C debugger at a "just-in-time" moment where you want to
step through a specific call.  But if you wrote something like:
print c-debug-break mold foo
...it took no arguments, and returned nothing.  So it would not be
possible to continue after this operation...as PRINT cannot print void.
The same mechanism that PROBE uses can't be used here.  PROBE takes an
evaluated parameter, and then passes it through as its result.  But if
C-DEBUG-BREAK did that, it would undermine the point: e.g. in the
example above, it's supposed to break into the debugger *before* the
MOLD, not after it.
This commit makes C-DEBUG-BREAK an arity-1 hard quoted operation.  It
then queues up its break, and proceeds to take the hard …
=> Invisible C-DEBUG-BREAK, QUOTE/SOFT, UNEVAL voids/BAR!s

src/os/host-console.r, src/os/host-start.r
When a script or `--do` is taken on the command line, it may error.
It might be interesting to examine the state of the interpreter, but
this would mean automated processes could not tell the difference
between a crashed script and one that is simply taking a long time.
This implements my suggestion that the default be to count down and
allow user interaction to bring up the console.  That interaction is
currently only able to be Ctrl-C, which doesn't seem so bad a choice
regardless.
More sophisticated command line switches could allow the time to be
adjusted from 5, or `--on-error=console` or `on-error=quit`, or even
to specify some kind of translation of the kind of error to a specific
error code.  This just does a proof of concept that the countdown is
possible (and not too much …
=> 5-second count for Ctrl-C to get console in erroring script

src/core/n-io.c, src/extensions/process/ext-process-init.reb, src/extensions/view/ext-view-init.reb, src/mezz/mezz-control.r, src/mezz/mezz-files.r, src/mezz/mezz-legacy.r, src/mezz/mezz-secure.r, src/mezz/mezz-shell.r, src/os/host-start.r, src/tools/make-make.r, src/tools/r2r3-future.r, src/tools/rebmake.r, tests/run-recover.r, tests/run-tests.r
Rebol wants to standardize FILE! literals to speak in the forward-slash
format.  So `%\foo\bar` gets turned into `%/foo/bar`.
(Arguably, it should complain about the literal form and refuse to
LOAD it instead of losing information)
This tightens the data types such that LOCAL-TO-FILE takes a STRING!
and returns a FILE!, and FILE-TO-LOCAL takes a FILE! and returns a
STRING!.  Another feature added is the /ONLY flag, which permits
pass-thru of an already converted quantity.  So if LOCAL-TO-FILE/ONLY
gets a FILE! as input, it won't error but will return a copy of that
FILE! instead.
(Note: It would be possible to subvert and get re-conversion on a FILE!
by saying AS STRING! MY-FILE, but that would defeat the purpose of
using the datatype to distinguish converted vs. non-converted values.)
=> TO-LOCAL-FILE/TO-REBOL-FILE as LOCAL-TO-FILE/FILE-TO-LOCAL

src/core/l-types.c
While Rebol2, R3-Alpha, and Red attempted to apply some amount of
decoding (e.g. how %20 is "space" in http:// URL!s), this changes to
leave URLs "as-is".
This serves the goal that a URL may be copied from a web browser bar,
printed/molded out, and pasted back round-trip.  It also means that the
URL may be used with custom schemes (odbc://...) that have different
ideas of the meaning of characters like `%`.
The current concept is that URL!s typically represent the *decoded*
forms, and thus express unicode codepoints normally...preserving
either of:
https://duckduckgo.com/?q=hergé+&+tintin
https://duckduckgo.com/?q=hergé+%26+tintin
Then, the encoded forms with UTF-8 bytes expressed in %XX form would be
converted as STRING!, where their datatype suggests the encodedness: …
=> Treat URL! as normal strings with no encoding behavior

src/boot/errors.r, src/boot/sysobj.r, src/core/c-eval.c, src/core/c-function.c, src/core/n-do.c, src/core/n-function.c, tests/core-tests.r, tests/functions/enclose.test.reb
This adds a new function generator called ENCLOSE.  It is similar to
a combination of ADAPT and CHAIN, but is strictly more powerful than
both (alone or combined).
ENCLOSE takes an outer function and an inner function.  The outer
function should be single-arity, and accept a fulfilled frame for
invoking the inner function (which it does with DO, as DO on a FRAME!
knows what function that frame is for).
This allows code to be run both before and after the wrapped function's
execution--as well as mutations to the wrapped function's frame before
running (similar to ADAPT).  But it can also carry state across the
execution and use it to mutate the result (whereas CHAIN has to be
a pure function of the output of the previous function in the chain)
Imagine you want a hooked version of multiply …
=> ENCLOSE call to "inner" function in an "outer" function

src/core/c-eval.c, src/core/n-data.c, src/core/n-do.c, tests/core-tests.r, tests/functions/redo.test.reb
REDO is a function that takes a running FRAME! (or a means of finding
a running FRAME!--such as a WORD! of a local variable, or FUNCTION!
representing a definitional return) and causes it to restart the
function with its current state--without creating another stack frame.
This allows one to program in a style similar to recursion, but
without running the risk of stack overflows.  Consider this recursive
function definition:
foo: func [n /accum a] [
case [
not accum [a: 0]
n = 0 [return a]
]
foo/accum (n - 1) (a + 2)
]
For small initial values of n, such as `foo 1000`, this works fine and
gives back 2000.  But even just `foo 10000` causes a stack overflow.
Using REDO, the function can be implemented in a similar style but
with only one stack frame:
foo: func [n /accum a] [
case [
not …
=> Tail-Call recursions via REDO primitive

src/core/c-eval.c, src/core/n-do.c, tests/functions/redo.test.reb
Ren-C has a sophisticated model of frame reuse in function composition.
Functions like ADAPT and SPECIALIZE are able to reuse a frame, as
opposed to adding layers to the call stack.  This makes them similar
in nature to tail-calls.
The original conception of REDO was that the only functions you could
REDO would be ones that were part of the current composition.  By
definition, those functions all have a compatible frame layout.  Yet
it's also possible for frames to be compatible when they are not
part of the same composition.  e.g. two distinct adaptations of the
same underlying function both have frames compatible with the
underlying function, hence also with each other.
The idea of doing a tail call optimization which jumps to the top of
another function is called a "sibling tail call". …
=> Allow "Sibling Tail Calls" via REDO/OTHER

src/core/c-eval.c, src/core/c-function.c, src/core/d-eval.c, src/core/d-stats.c, src/core/d-trace.c, src/core/n-do.c, src/include/sys-action.h, src/include/sys-function.h, src/mezz/base-defs.r, src/mezz/mezz-help.r, tests/core-tests.r, tests/functions/invisible.test.reb
This introduces two new categories of "invisible" functions.  They are
designed to return nothing--not even void.
The way to say how a function is in this category in the moment is to
give it a `return: []` in its spec, to say the null set (even excluding
`<opt>` for void) is what it can return.  This means it will do its
best to omit any influence from the chain of evaluator (outside running
the body of the function itself).
Category #1 is when the function is not enfix.  This simplification
will attempt to complete the left-hand side of an expression before
running.  This gives a mostly-intuitive order of evaluation, as shown
by the DUMP debug primitive--which has been changed to be invisible:
>> x: 10
>> y: 20
>> z: 1 + 2 * 3 dump [z y x]
z: => 9
y: => 20
x: => 10
== 9
The cost of such …
=> Invisible mechanic: COMMENT mostly invisible, ELIDE fully so

src/core/c-eval.c, src/core/n-do.c, src/include/sys-rebfrm.h, src/include/sys-varargs.h, src/tools/common.r, tests/control/dont.test.reb, tests/core-tests.r
This is a very early-stage implementation of a primitive called DON'T.
Its goal is to be able to answer whether expressions have a knowable
arity (e.g. do not have variadic character) and thus can be skipped
over safely.
It uses a new evaluator flag DO_FLAG_NEUTRAL which is supposed to tell
all expressions that could have side effects not to have them.  (This
isn't working perfectly yet, e.g. GROUP!s inside of PATH!s currently
still evaluate--but fixing that likely will involve eliminating the
specialized REBPVS path-value-state structure and merging path dispatch
with REBFRM for frames.)
Since there's no value to return, DON'T returns either TRUE or FALSE.
If FALSE, that means there was some variadic element which inhibited
the ability of it to determine the expression evaluation …
=> Primordial "DON'T" primitive for neutral evaluation analysis

src/core/t-block.c
The RANDOM function shuffles a BLOCK! by swapping values
at random positions. An assertion was failing when a
value was being swapped with itself.
=> Avoid a failed assertion when calling RANDOM on a BLOCK!

src/mezz/base-infix.r, src/mezz/mezz-debug.r
When short-circuiting was introduced for the conditional logic
operators, the idea of being able to "run the evaluator in neutral" to
skip expressions did not work unless the expression was in a GROUP!.
This furthers that restriction, by demanding that the short-circuit
expression indeed be a literal GROUP!.
Whether this will be the ultimate definition of AND/OR/etc. or not is
up in the air, but is submitted for continued experimentation.
For details, see:
https://github.com/rebol/rebol-issues/issues/1879
=> Require GROUP! for right hand side of short-circuit AND/OR/etc.

src/os/posix/host-readline.c
Some functions didn't recognize multibyte characters, resulting in a
misaligned or out-of-bounds cursor. More work is needed in order to
intercept non-printable characters such as modifiers and "variation
selectors".
=> Update POSIX terminal functions to properly handle UTF-8.

make/make.r, src/tools/common.r, src/tools/make-make.r
The goal is to allow one write e.g.
>> ./r3-make make.r prep
or
>> ./r3-make make.r r3
or
>> ./r3-make make.r clean prep r3
etc...
- tools/common.r:
PARSE-ARGS/ALL accepts 'standalone' args (without '=')
- tools/make-make.r:
- standalone args interpreted as targets
- multiple targets allowed
- `r3` as synonym of `execution` target
- allowed `prep` target
- make/make.r:
a wrapper for tools/make-make.r
Examples:
`./r3-make make.r clean`
is the same as
`./r3-make ../src/tools/make-make.r target=clean`
`./r3-make make.r clean r3`
is the same as
`./r3-.ake make.r target='[clean r3]'`
is the same as
`./r3-make ../src/tools/make-make.r target=clean;
./r3-make ../src/tools/make-make.r target=execution`
=> tools/make-make.r: extend cmdline syntax

src/core/c-value.c, src/include/sys-do.h, src/include/sys-value.h
This adds two debugging conveniences.  One is that in the C++ build,
type templating is used to make it so that PROBE() can return the
exact type, value, and cv-qualifiers it gets in...like Rebol's PROBE.
This means it can be used e.g. as
return PROBE(Get_Some_Mutable_Series(...));
...or...
return PROBE(Get_Some_Const_Value(...));
The other addition is something which probably should have been added
much sooner.  Previously you could break on a tick, but it would always
put you in the evaluator loop at the point where the tick was bumped.
If the location you wanted to debug was somewhere else, you'd have to
go put a breakpoint there...but then worry about disabling that
breakpoint on the next debug run and re-enabling it.
This sidesteps all that just by having a BREAK_ON_TICK() macro you …
=> PROBE() passes through value in C++, add BREAK_ON_TICK macro

tests/read-deep.reb, tests/source-tools.reb
Modify source analysis for recursive read strategy
A number of source files were ignored by the source analysis routines because they were not included in the fixed path configuration. Originally this was to avoid an R3 Alpha READ bug on linux.  As the source tools can now assume they will be run by the recent build, a recursive read strategy for %src/ has been implemented.
The %tests/ folder has also been included for source analysis.
In addition this PR fixes some paths in source-tools.reb that were broken by recent repo changes.
=> Check more source

src/core/n-control.c, src/core/n-loop.c, src/include/sys-do.h, src/mezz/base-funcs.r, src/mezz/mezz-files.r, src/mezz/mezz-math.r, src/mezz/mezz-series.r, src/os/host-start.r, tests/control/default.test.reb, tests/control/switch.test.reb, tests/misc/shttpd.r
This commit backpedals on a change adopted early after R3's open
sourcing, which allowed simple values to be used as branches in a
conditional.  Hence instead of writing:
x: if 1 < 2 ["one is less than two"]
You could simply write:
x: if 1 < 2 "one is less than two"
This was in the spirit of Rebol's reluctance to require boilerplate
unless it was absolutely necessary, such as not having the condition
of the IF be in blocks.  The concept wasn't necessarily that people
would stop using the delimiters, but that they might feel other choices
would give them "more bang for the buck" for each character, perhaps
in this case preferring:
x: if (1 < 2) "one is less than two"
This had some drawbacks, for instance that writing `if condition body`
would look up the variable corresponding to body even …
=> Only BLOCK!/FUNCTION! branches for conditionals (IF, CASE, etc.)

src/mezz/base-funcs.r, src/mezz/sys-load.r, tests/control/default.test.reb
This introduces the WAS operator, which fetches the prior value of a
SET-WORD! or SET-PATH! and evaluates to that, but also performs it as
an assignment.
>> x: 10
>> was x: 20
== 10
>> x
== 20
It works based on variadic lookahead, which means it doesn't actually
consume the SET-WORD! as a parameter.  This means it is compatible with
operations that quote backwards to find the SET-WORD!, for example
the DEFAULT operator.
>> x: _
>> was x: default [20]
== _
>> x
== 20
Also includes some stray changes to %sys-load.r which make it use the
short circuit AND.
=> WAS operator for getting last value while setting a new one

make/r2r3-future.r, src/boot/actions.r, src/core/f-series.c, src/core/n-sets.c, src/core/s-ops.c, src/core/t-bitset.c, src/core/t-char.c, src/core/t-date.c, src/core/t-integer.c, src/core/t-logic.c, src/core/t-string.c, src/core/t-tuple.c, src/core/t-typeset.c, src/include/sys-core.h, src/mezz/base-infix.r, src/mezz/mezz-legacy.r, src/mezz/prot-tls.r, src/mezz/sys-load.r, src/os/host-start.r, src/os/unzip.reb, tests/atronix/ms-drives.r, tests/control/case.test.reb, tests/control/for.test.reb, tests/control/repeat.test.reb, tests/datatypes/closure.test.reb, tests/datatypes/decimal.test.reb, tests/datatypes/function.test.reb, tests/math/and.test.reb, tests/old/r2-tests.r
This folds the prefix form of "bitwise" math into the corresponding
set operations, and then makes AND+/OR+/XOR+ the enfixed versions of
those operations.  This broadens the applicable types that can be used
with the infix operator:
>> "ade" or+ "bcf"
== "adebcf"
It also gets rid of the not-very-well-named prefix forms of the math
operation.
This change was proposed long ago to accompany the switch of plain
AND and OR to be "conditional" boolean logic operations.  However, two
details were glossed over.  One is that what should happen on a
BINARY! is slightly ambiguous, as it might be desirable to treat it
as a set of bytes vs. as something to operate on bitwise.  The other
issue is that DIFFERENCE on DATE! is an outlier in when the behavior
is conceptually an XOR, and is more a play on …
=> Fold AND~/OR~/XOR~ in INTERSECT/UNION/DIFFERENCE, AND*=>AND+

src/core/t-logic.c, src/mezz/base-constants.r, src/mezz/mezz-legacy.r, tests/series/difference.test.reb
TRUTHY? and FALSEY? operators were added to see if anyone liked them,
but they were unpleasant.  This removes them, assuming you would use
NOT anytime you would want FALSEY?.
Yet there is no general consensus on what the "opposite of NOT is",
since usually the opposite of NOT is just taking it away.  TO-LOGIC is
a substitute, but it feels a bit drawn-out and long.
A suggestion came up that at least sometimes seems okay.  DID.
logic-variable: did find [a b c] 'd
flag1: did all [...]
flag2: did any [...]
While it is somewhat strange to say `did 1` -> true, if one didn't
have the background to understand it then `not 1` -> false might also
look quite strange.  So in the interest of perhaps being a trendsetter,
this goes ahead and gives it a try...it's not hard to beat TRUTHY?. …
=> Add "DID" native, remove ! as built-in synonym for NOT

make/make.r
Include path was missing from `mod-odbc` for the header file `%tmp-ext-odbc-init.inc`, this lets Visual Studio 2017 build properly
=> Add odbc include path to mod-odbc

make/make.r
Dynamic extensions were not having their module include paths processed on each step. This should fix the issue with at least mingw.   I am not able to test on other OSes.
=> Fix dynamic extension includes

make/make.r, make/tools/make-boot.r, make/tools/make-ext-natives.r, make/tools/r2r3-future.r, src/core/c-function.c, src/mezz/base-funcs.r, src/mezz/mezz-debug.r, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r, src/mezz/mezz-save.r, src/mezz/mezz-secure.r, src/mezz/mezz-series.r, src/mezz/sys-base.r, src/mezz/sys-load.r, src/mezz/sys-ports.r, src/os/encap.reb
This addresses the question of what the "anti-default" should be called
by taking the name MAYBE:
>> x: maybe 1 + 2
== 3
>> x: maybe blank
== 3
>> x: maybe ()
== 3
>> x: maybe* blank ;-- * means count _ as value
== _
>> x: maybe [1 + 2] ;-- not what you meant
** Error: Literal block! used w/MAYBE, use () if intentional
All in all, it's a very good name for what it does.  It's a tool for
*maybe* doing an assignment, if the right hand side is "something"...
where something usually means not-void and not-blank, but can be
fallen back upon to mean just not-void.
A parallel function called REALLY operates in much the same way, but
instead of not doing the assignment it will fail.
>> x: really ()
** Script Error: really requires value argument to not be void
>> x: really blank
** Error: REALLY …
=> MAYBE+REALLY => arity 1, MATCH+ENSURE => arity 2

src/core/a-lib.c, src/core/c-eval.c, src/core/n-control.c, src/core/n-do.c, src/mezz/base-defs.r, src/mezz/base-funcs.r, src/mezz/base-infix.r, src/mezz/base-series.r, src/mezz/mezz-debug.r, src/mezz/mezz-files.r, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, src/os/encap.reb, tests/control/apply.test.reb, tests/functions/invisible.test.reb, tests/functions/redo.test.reb, tests/test-framework.r
The ELIDE routine was originally designed as an attempt to create a
"truly invisible" comment.  If given a BLOCK!, it would act like
COMMENT, and if given a GROUP!, it would execute code.  Both could
be done without interfering with the flow of surrounding evaluation.
The reason COMMENT was not done this way is because the definition of
a truly invisible operator wound up being a little weird.  It would
have to be--in effect--an enfix tight operation which was able to
"beam" the state after its parameters were gathered back to be its
return result.  This meant when ELIDE executed code, the moment of
execution made it appear fairly erratic...when most operations that
wanted to be "invisible" would prefer to sacrifice true invisibility
in order to execute code at a more reasonable moment. …
=> Repurpose ALSO, kill after, add THEN, swap ELIDE/COMMENT behavior

make/default-config.r, make/tools/make-boot.r, src/core/c-eval.c, src/core/n-do.c, src/extensions/uuid/make-libuuid.reb, src/mezz/base-infix.r, src/mezz/mezz-files.r, src/mezz/mezz-math.r, src/mezz/mezz-secure.r, src/mezz/mezz-series.r, tests/atronix/ms-drives.r, tests/atronix/test-libs.r, tests/datatypes/closure.test.reb, tests/datatypes/function.test.reb, tests/math/add.test.reb, tests/misc/fib.r
Debates about whether to take `//` or `--` for comment based on their
"line-y" looks triggered the question of how these symbol-based items
might be given to purposes besides rarely-used math operations.  It
seems much more Rebol-like to have a test dialect be able to do the
likes of the following when saying the following tests relate to issue
#1020
-- #1020 --
[x > 1]
[x < 2]
Freeing up the "drawing-ish" operator repetitions for users to assign
for such uses makes more sense than hardcoding them for rarely (or
even barely) used math operators, that don't look good.  So the idea
of a generic ME operator came up, where:
>> some-var: 20
>> some-var: me + 1 * 10
>> print some-var
210
Being able to write `some-var: me + 10` isn't as "simple" <ahem> as:
* making ME a backwards quote operator …
=> Introduce ME operator, kill off ++, --, **, and //

src/core/c-eval.c, src/core/n-do.c, src/mezz/base-infix.r, tests/series/append.test.reb
This commit adds an implementation for MY that allows a SET-WORD!'s
existing value to be slipped in the first argument to a function
which overwrites it.  e.g.
>> block: copy [a b c d]
>> block: my next
>> probe block
[b c d]
>> block: my append [1 2 3]
>> probe block
[a b c d 1 2 3]
Unfortunately the trickery involved does not work for PATH!s at this
time (e.g. append/only), only for WORD!s.  The reason is because it
is actually pretending the right hand argument is an enfix function
even though it is not, and running through the same machinery that
fills the first frame argument of enfix functions with a prior single
value while doing the rest of an evaluation normally.
(A less dodgy technique for doing the same thing should be possible to
design in the future--e.g. this is not …
=> MY operator for prefix functions (complement to ME for enfix)

src/core/a-lib.c, src/core/c-eval.c, src/core/l-scan.c, src/core/n-system.c, src/include/sys-do.h, src/include/sys-scan.h
This is a *very rough* proof of concept, showing for the first time
a functional form of intermixing REBVAL* API pointers and UTF-8
text to a parameterized rebDo.  This pattern permits flexible
combinations of text runs with spliced content, e.g.
rebDo("print [", value1, "+ (2 *", value2, ")]", END);
One central trick is the usage of platform-independent byte ordering
macros, which are able to make the pattern of valid UTF-8 strings
distinct from the pattern of Rebol values (also distinct from
Rebol series, END markers, freed cells, etc).
There are numerous issues to resolve: one is how binding will be
handled (both for the string runs and for the spliced values).  But
also the semantics of evaluation, regarding whether WORD! or FUNCTION!
values will need to be live by default and QUOTEd …
=> First cut demo of intermixing UTF-8 with REBVAL* in rebDo()

make/tools/make-ext-natives.r, make/tools/native-emitters.r, src/extensions/bmp/mod-bmp.c, src/extensions/crypt/mod-crypt.c, src/extensions/debugger/mod-debugger.c, src/extensions/ffi/mod-ffi.c, src/extensions/ffi/t-struct.c, src/extensions/gif/mod-gif.c, src/extensions/jpg/mod-jpg.c, src/extensions/locale/mod-locale.c, src/extensions/odbc/mod-odbc.c, src/extensions/png/mod-lodepng.c, src/extensions/process/mod-process.c, src/extensions/uuid/mod-uuid.c, src/extensions/view/mod-view.c
There are two conflicts when an extension and core have natives with
same name: the parameter macmros INCLUDE_PARAMS_OF and the C function
name N_, because they share the same globale name space, and sys-core.h
is included by each module source. The conflicts are solved by prefixing
INCLUDE_PARAMS_OF with CORE_ or module name (e.g.
CRYPT_INCLUDE_PARAMS_OF) and redefining REBNATIVE in each module to
include the module name in the C functions (e.g. N_rc4 becomes
N_CRYPT_rc4)and keep the names of the core natives unchanged.
=> Allow extension and core to have natives with the same name

src/core/c-eval.c, src/core/d-eval.c, src/include/sys-do.h, src/include/sys-value.h, src/mezz/base-defs.r, tests/functions/invisible.test.reb
This adds a new usermode function which consumes items in a way
that makes it appear evaluation of a BLOCK!/GROUP! has ended:
>> do [1 + 2 end 10 + 20 | 100 + 200]
== 3
It does this by being a hard-quoted variadic, that just takes its
arguments without looking at them...and then it is also an "invisible".
Testing this exposed a difference between:
>> do [1 +]
** + is missing its value2 argument
>> do [1 + end]
** + does not accept void as its value2 argument
That was because the internals of Do_Core() would convert ENDs into
voids too early for argument fulfillment to tell the difference.  This
commit changes it so that the conversion to a void is done later by
those callers of the evaluator that need it.
The benefit applies to other invisibles, like COMMENT, in making sure
that they …
=> END ignores values to end of block/group, simplify invisibles

make/tools/make-boot.r, src/core/b-init.c, src/core/m-gc.c
Because C only lets you initialize arrays with compile-time constants,
some macros were used to talk about the embedded natives and code.
These could get out of sync and commonly lead to boot errors when
a change was made to the mezzanine.
This adds extern const values for those macros to be linked to instead
of hardcoded into the callsites, so that recompiling the file with
the C literal data and relinking is enough to avoid the boot error.
=> MAKE PREP without need for MAKE CLEAN for mezzanine

src/boot/sysobj.r, src/boot/words.r, src/core/t-datatype.c, src/mezz/mezz-legacy.r
The `do <r3-legacy>` compatibility mode had atrophied somewhat from
lack of use, and several of the code paths inside the interpreter's C
code were removed to tighten things up.
This brings back a less-bend-over-backward compatibility mode, that is
not geared toward emulating obscure quirks of R3-Alpha.  Rather it acts
in the interest of aiming to enable a stylization of code as a "lowest
common denominator" which could run in R3-Alpha/Rebol2/Red, or this
`<r3-legacy>` mode of Ren-C.
To accomplish this, it does things like provide augmented FUNC and
FUNCTION generators that use FRAME! reflection to translate LOGIC!
false refinements into BLANK! values, and void arguments to unused
refinements into BLANK!s.  These function generators also provide a
definitional EXIT, in the spirit of the …
=> Resurrect `<r3-legacy>` emulation, via more usermode code

src/core/n-control.c, src/mezz/sys-load.r, tests/control/case.test.reb
This commit switches CASE to use soft-quoting semantics on its branch
values.  The limiting aspect of this is you can no longer say, e.g.
3 = case [
true reduce ['add 1 2]
]
If you wanted to say that, you would have to write:
3 = case [
true (reduce ['add 1 2])
]
There are significant benefits to modifying CASE to this rule.  First,
if a condition is false, it is possible to skip over the branch slot
as it is only one element in size.  This is to say that the following
would not print, and return void:
void? case [
false (print "won't print" ['add 1 2])
]
While pinning down the semantics of CASE has been a longstanding goal
of Ren-C, the actual motivating scenario was to not "double-evaluate"
branches in the general case, so that ELIDE/DUMP/COMMENT and other
invisibles could be used …
=> Enable ELIDE, COMMENT, etc. in CASE interstitials

src/core/c-eval.c, src/core/c-function.c, src/core/c-path.c, src/core/c-specialize.c, src/core/n-data.c, src/core/n-do.c, src/core/n-function.c, src/core/t-varargs.c, src/core/u-parse.c, src/include/sys-bind.h, src/include/sys-do.h, src/include/sys-rebfrm.h, tests/datatypes/error.test.reb, tests/series/append.test.reb
This makes APPLY and MY speak the protocol for pushing refinements to
the stack for Do_Core() to process them, by factoring out code that
was introduced for SPECIALIZE.
>> some-block: copy [a b c]
>> some-block: my append/dup/part [d e f] 3 2
== [a b c d e d e d e]
One difficult aspect was that the baseline of the stack needs to be
known, yet Do_Core() may be called on a stack that is constantly
building itself up.  (e.g. REDUCE which pushes a frame and then does
several consecutive evaluations with that frame pushed).  Previously
the DSP was captured on each Do_Core() entry, but this modifies it
so that it gets captured in DECLARE_FRAME(), allowing one to put it
at a separate point from Push_Frame() or a Do_Core() entry.
=> Make APPLY and MY work with PATH!

src/boot/actions.r, src/boot/errors.r, src/core/s-crc.c, src/core/t-map.c, tests/datatypes/map.test.reb, tests/series/unique.test.reb
The hashing code for MAP!s is shared with set operations.  A rather old
commit (Jan 24, 2016) for facilitating case-sensitivity in maps had a
side effect of breaking case-insensitive set operations:
https://github.com/metaeducation/ren-c/commit/20c8e506431c9b773e9c7ee14286f5eabc6167e5
They haven't worked right since Jan 2016.  But no one noticed.  :-)
Rather than fix that sole issue, this commit attempts to resolve the
longstanding puzzle the change was intending to address: being able to
use differently-cased versions of the same key in MAP!s.  The feature
has provoked prolonged debates, and raises some semantic questions.
Rather than invent two different data types (case sensitive maps and
non-case-sensitive), the plan thus far--shared by Red--is to make the
maps preserve the case of …
=> Fix uncased UNIQUE, PUT/CASE for ambiguous MAP! key casings

src/boot/errors.r, src/core/a-lib.c, src/core/c-error.c, src/core/c-specialize.c, src/core/n-protect.c, src/core/t-map.c, src/extensions/locale/ext-locale-init.reb, src/extensions/locale/iso3166.r, src/extensions/locale/iso639.r, src/include/sys-rebser.h, src/include/sys-series.h, src/mezz/mezz-legacy.r, src/mezz/mezz-series.r, tests/datatypes/map.test.reb
R3-Alpha's MAP! would give wrong answers if a key used in a map were
changed after the insertion.  Ren-C safeguarded against this by
only allowing keys that had been LOCK'd immutably, with a promise
that they would remain immutable (as there is no UNLOCK).  This also
allowed ANY-ARRAY!s or OBJECT!s to be used as map keys.
For efficiency, the key passed in was not automatically copied before
locking, as that could have surprising memory usage and performance
consequences.  Instead, an already locked key would be used directly,
and a key that hadn't been locked would give an error...which would
allow the person doing the insertion to decide if they felt they
needed a separate mutable copy (shallow or deep)...and they could
either make a copy and lock it, or just lock what they had.
This …
=> Automatically lock series backing map keys when inserted

src/boot/actions.r, src/core/c-context.c, src/core/d-stack.c, src/core/f-modify.c, src/core/l-scan.c, src/core/n-io.c, src/core/n-reduce.c, src/core/s-mold.c, src/core/s-ops.c, src/core/t-block.c, src/core/t-gob.c, src/core/t-image.c, src/core/t-map.c, src/core/t-port.c, src/core/t-string.c, src/include/sys-array.h, src/include/sys-core.h, src/include/sys-rebser.h, src/include/sys-rebval.h, tests/convert/mold.test.reb, tests/source-tools.reb
Historically each value cell in a Rebol array offered a place to put
a "new line marker".  This new line marker would indicate that a
new-line should be output *before* that value was molded.
Yet an N-element array has N + 1 "in-between" positions where a newline
might be indicated.  This approach meant that there was no way to
say that the tail of an array had a new line on it...meaning that one
could not write:
data: copy [
a b c
]
new-line (tail data) true
append data 10
...and get back:
[
a b c
10
]
Because there was no memory in C of the fact that a new-line was at
the tail.  The only reason it appears there is a new line is that
there was some logic in mold that said if any new lines were output
during a mold, then the close brace would be on its own line.  You
could not preserve …
=> Head *and* Tail NEW-LINE positions, APPEND/LINE (+INSERT,CHANGE)

make/make.r, make/tools/make-boot.r, make/tools/make-ext-natives.r, make/tools/make-os-ext.r, make/tools/r2r3-future.r, src/boot/actions.r, src/boot/sysobj.r, src/core/f-extension.c, src/core/n-data.c, src/mezz/base-funcs.r, src/mezz/base-infix.r, src/mezz/mezz-help.r, src/mezz/mezz-legacy.r, src/mezz/mezz-save.r, src/mezz/sys-load.r, src/mezz/sys-ports.r, tests/comparison/equalq.test.reb, tests/control/apply.test.reb, tests/control/break.test.reb, tests/control/continue.test.reb, tests/control/leave.test.reb, tests/control/loop.test.reb, tests/control/return.test.reb, tests/control/throw.test.reb, tests/datatypes/error.test.reb, tests/datatypes/module.test.reb, tests/datatypes/unset.test.reb
In R3-Alpha, Rebol2, and Red, getting a variable that is unset is
an error.  Ren-C experimented with the idea that GET would be more
tolerant, and return a blank on failure.
The new model going forward in Ren-C has been to very purposefully use
null results as a kind of "soft" failure.  Most routines reject null
inputs, but if given a blank input will return void.  This makes each
step in an evaluation chain a place that one can elect to put a
TO-VALUE (now, also taking the old name TRY) or not.  Failing to put
in a TRY means one's attention is raised to the failed operation.
So this makes GET return void, while GET/TRY can be used to ask for
blankification.  For ordinary parameters this is the same as TRY GET,
but since blocks cannot hold nulls it's necessary to be a refinement
for block …
=> Make GET return null if variable is not set, /ONLY => /OPT

src/mezz/prot-http.r
Previously when we used the no-redirect keyword only 302s were not followed.  Now, we do this for all 30n codes ignoring that 305 is no longer used.  See https://developer.att.com/video-optimizer/docs/best-practices/http-300-status-codes
>> to string! write http://www.ayadesajn.net [no-redirect GET []]
== {<html>^M
<head><title>301 Moved Permanently</title></head>^M
<body bgcolor="white">^M
<center><h1>301 Moved Permanently</h1></center>^M
<hr><center>nginx/1.4.6 (Ubuntu)</center>^M
</body>^M
</html>^M
}
>> read http://www.ayadesajn.net
** Access Error: protocol error: "Redirect to other host - requires custom handling"
** Where: fail switch take* any unless awake either do-redirect then if switch check-response switch take* any unless _ wake-up either while-not _ wait while-not sync-op …
=> all 30n responses can be ignored

make/tools/r2r3-future.r, src/core/b-init.c, src/core/c-error.c, src/core/c-eval.c, src/core/l-scan.c, src/core/n-data.c, src/core/n-math.c, src/mezz/base-funcs.r, src/mezz/base-infix.r, src/mezz/mezz-legacy.r, src/mezz/sys-load.r, src/os/host-console.r, src/os/host-start.r, tests/datatypes/unset.test.reb, tests/test-framework.r
This contains a number of changes provoked by the idea that `SET 'WORD`
should act the same as `WORD:`, while settling on the concept that
`:WORD` acts the same as `GET 'WORD`.
One idea is that the <- operator disallow null.  Its previous main
purpose was precedence manipulation, such that you could write
`return <- if condition [...] else [...]` to stop the default
interpretation as `(return if condition [...]) else [...]`.  But
there's not a particularly compelling reason for it to allow null,
so it can do double duty as a checking construct.
e.g. consider `foo: <- :bar` .  Precedence-wise that's interpreted as
`foo: (:bar)`, which doesn't change anything, since there is no enfix
involved.  But the null check means the person doing the assignment can
be confident that the :bar fetched …
=> Scan => and =<, kill ?, <- enforce non-NULL, nullable SET

make/tools/common-emitter.r, make/tools/make-boot-ext-header.r, make/tools/make-boot.r, make/tools/make-embedded-header.r, make/tools/make-ext-init.r, make/tools/make-ext-natives.r, make/tools/make-headers.r, make/tools/make-host-init.r, make/tools/make-os-ext.r, make/tools/make-reb-lib.r, make/tools/native-emitters.r, make/tools/rebmake.r, src/boot/errors.r, src/boot/types.r
This pushes the build process to use more CSCAPE-based code, which
gives a better view of the templated output of the C being produced.
It introduces the new features of $[] to output a list with a delimiter
on each line (e.g. `$[fields];` can be used output a block that
contains a list of struct fields with a semicolon on each line) and
$() to output a list with a delimiter on all lines but the last
(e.g. `$(enum-items),` will put a comma on each line except the last.
This means that many "emit-as-you-go" bits of code have been changed
to "collect and then emit".  While somewhat slower, it is vastly
more clear to read.
Also changes the type table to not have an entry for 0.
=> Replace EMIT-ITEM/EMIT-LINE usages with CSCAPE EMIT

src/mezz/prot-http.r
The tiny webserver from Carl uses an incorrect separator between the header and body.  This checks for this.
=> patch to prot-http.r to not fail on tiny webserver

src/boot/types.r, src/core/c-path.c, src/core/t-word.c, src/mezz/prot-tls.r, tests/datatypes/path.test.reb
This makes it so that any evaluator-inactive type at the head of a path
will curb evaluation of that path.  Hence you can write:
>> <json>/1.2.30
== <json>/1.2.30
>> /dir/subdir ;-- first path element is REFINEMENT!
== /dir/subdir
>> "abc"/2
== "abc"/2
The path can become activated by either putting the head element in
a GROUP!, or referring to it via an evaluative entity
>> ("abc")/2
== #"b"
>> text: "abc"
>> text/2
== #"b"
Since ANY-WORD! historically has no path behavior, it was difficult
to demonstrate the inert vs. active difference.  This adds a quick and
dirty ability to pick characters by integer out of words--which with
the ANY-STRING!/ANY-WORD! unification would ultimately align with
whatever other operations might be legal on strings.
=> PATH!s with inert head elements are themselves inert

src/mezz/base-funcs.r, src/mezz/mezz-files.r, src/mezz/mezz-legacy.r, src/mezz/prot-http.r, src/mezz/sys-start.r, tests/control/unless.test.reb
The speculative feature UNLESS has turned out to be extremely useful,
such that it is unlikely anyone will be mourning its loss as a synonym
for IF NOT.  A shim detects "old-style" UNLESS usages with high
reliability, and directs users to the new definition, as well as
offering `unless: :if-not` as a workaround.
>> 10 + 20 unless case [
false [<no>]
false [<nope>]
false [<nada>]
]
== 30
>> 10 + 20 unless case [
false [<no>]
true [<yip!>]
false [<nada>]
]
== <yip!>
This commit also changes UNLESS to consider any non-null value to
override the left.  This means blanks now count:
>> 10 unless _
== _
Previously, this behavior would only happen if you used the special
UNLESS* operation.  However, most operations either trigger off of
null/non-null (e.g. ELSE, ALSO, !!) or truthy/falsey (IF, …
=> Enable new UNLESS for all users, drop UNLESS*/MAYBE*

src/core/t-block.c, src/core/t-string.c, src/core/t-vector.c, tests/series/pick.test.reb
Consensus in general was that the negative indexing behavior of
R3-Alpha was not pleasing.  This restores the historical behavior.
Also makes it so that picking with DECIMAL! will round the decimal
down and use the INTEGER! value, vs. SELECT-ing the DECIMAL.
Commit initiated by Oldes in:
https://github.com/Oldes/r3/pull/5
His comments there:
"In Rebol2, picking value with index 0 was always returning null. In
R3-Alpha it was changed that zero index was working like index -1...
more at this blog http://www.rebol.net/cgi-bin/r3blog.r?view=0173"
"I decided to revert this change and let it working as before (and so
be compatible with Red too)"
"So now it works for example like:"
>> pick tail "123" -1
== #"3"
>> pick tail "123" 0
== none
"and it is also consistent with AT positioning:"
>> at …
=> Restore Rebol2-era PICKing/PATHing of negative/zero indices

make/make.r, make/tools/common-emitter.r, make/tools/make-boot.r, make/tools/make-headers.r, make/tools/r2r3-future.r, make/tools/rebmake.r, src/core/c-eval.c, src/core/n-control.c, src/core/n-do.c, src/extensions/ffi/make-spec.r, src/extensions/odbc/make-spec.r, src/include/sys-do.h, src/mezz/base-funcs.r, src/mezz/mezz-legacy.r, src/mezz/sys-start.r, tests/control/case.test.reb, tests/control/switch.test.reb
The speculative feature of "SWITCH fallout" has been endorsed as a
legitimate way to return a value from a switch.  This says that if the
last match item is reached with no associated branch block after it,
the match item itself is the evaluative result:
>> switch 3 [1 ["one"] 2 ["two"] "other"]
== "other"
A question posed about this was:
"Does fallout make SWITCH feel like it's fancier and has good
dialecting bones, taking advantage of Rebol's unconventional-ness?
Or does it make SWITCH seem weird...like you're looking at
incomplete code, missing the branch for the last switch case?"
The decision was that for Rebol's domain, this kind of implementation
choice goes well with the "fast-and-loose" character of the language,
especially with a "fully evaluative switch".  It enables styles of …
=> liberal SWITCH eval, kill SWITCH/DEFAULT, CASE fallout

make/tools/common-emitter.r, make/tools/r2r3-future.r, make/tools/rebmake.r, src/boot/errors.r, src/core/n-control.c, src/core/u-parse.c, src/os/host-start.r, tests/parse-tests.r
PARSE is not strictly a LOGIC!-returning function, and can return
anything with RETURN.  Hence, it is useful to make its failure map
to null instead of false, so it can be used e.g. like:
value: <not-found> unless parse data [
some 'foo return (<some-foos-found>)
]
This changes the failure to be a null.  The default return of success
is a BAR! value, which is what is typically used for "synthesized"
truthy values...as returning #[true] would give the incorrect
impression that the failure case would be #[false].  Hence it cues
users to go to either a DID PARSE or NOT PARSE (if they were interested
in a LOGIC!) or a TRY PARSE (if they were going to return a value or
fail otherwise, and want to put that value into a variable).
Also, speculatively makes PARSE able to take a BLANK! value in …
=> PARSE returns null/BAR! by default, allow THROW of ERROR!

src/boot/sysobj.r, src/core/c-eval.c, src/core/c-function.c, src/core/c-port.c, src/core/c-specialize.c, src/core/n-data.c, src/core/n-function.c, src/core/n-native.c, src/core/t-varargs.c, src/include/sys-do.h, src/include/sys-typeset.h, src/include/sys-value.h, src/mezz/base-funcs.r, tests/control/else.test.reb, tests/control/leave.test.reb
This commit changes it so that RETURN can always be given an argument
or not.  If it is not given an argument, then it acts just the same
as if someone had written RETURN VOID.  Hence the following is legal:
foo: func [x] [
if x > 0 [return] else [return 100]
]
The return type will still be type checked, so void must be one of the
legal return types for the function.  (It is legal if there is no
return type annotation given.)
Historical Rebol had two different forms of RETURN...an arity-1 version
called RETURN, and an arity-0 version called EXIT.  Either form could
be used from any function, and invoking EXIT would mean that the
result would be an UNSET!.
Definitional returns changed the mechanics of RETURN significantly, and
there were two different kinds of function generators: …
=> Make RETURN endable, all can be arity 0 -or- 1

src/core/n-control.c, tests/control/case.test.reb
The following is legal in an IF statement:
branch: [print "this prints"]
if true branch
As is this:
if false (print "this prints too" [print "doesn't print"])
When CASE is thought of as a construct whose behavior parallels IF,
that would suggest the following would be legal as well:
branch: [print "this prints"]
case [
false (print "this prints too" [print "doesn't print"])
true branch
]
That means branches can have a single evaluation step (on false, to
get the branch but not use it) or a double evaluation (on true, because
it adds in the step of running that branch as well).
Ren-C initially brought consistency to this, by doing a 1st-level
branch evaluation even to false cases.  However, the first-level
evaluation caused problems with ELIDE, because it had been forced to
run along with …
=> Resurrect evaluative CASE branches (brings back IF parity)

.travis.yml, make/make.r, src/core/b-init.c, src/core/c-eval.c, src/core/c-path.c, src/core/l-scan.c, src/core/m-gc.c, src/core/m-pools.c, src/core/n-function.c, src/core/s-mold.c, src/core/t-block.c, src/core/t-function.c, src/core/t-gob.c, src/core/t-map.c, src/extensions/ffi/t-struct.c, src/extensions/zeromq/mod-zeromq.c, src/include/sys-eval.h, src/include/sys-frame.h, src/mezz/base-infix.r, src/mezz/mezz-math.r, tests/datatypes/error.test.reb, tests/datatypes/path.test.reb
This changes `/` from being a WORD! to being a zero-length path.  It
also makes `foo/` the representation of a length-1 path, which acts
the same as whatever the single element would be if not in a path.
(Reasoning for a length-1 path acting like the element alone is to
simplify code which might put an ACTION! in the first slot of a PATH!,
and then progressively build a list of refinements...but wind up with
an empty list.  By allowing the path to run anyway, this means there's
no need to special-case that as just an ACTION!.)
The concept is that the zero length path dispatch in the evaluator goes
to the type on the left, just like in ordinary path dispatching.  But
it runs different code.  Hence `a/b` and `a / b` are two distinct ways
in which the value on the left is "pathed".  The …
=> Simplified `/`-as-zero-length-path implementation

make/configs/emscripten.r, make/default-config.r, make/tools/make-reb-lib.r, src/core/a-lib.c, src/extensions/javascript/README.md, src/extensions/javascript/ext-javascript-init.reb, src/extensions/javascript/ext-javascript.c, src/extensions/javascript/make-spec.r, src/extensions/javascript/mod-javascript.c
This is a first cut at adding a "JavaScript extension" which provides
a way to make "JavaScript natives".  These have specs which are BLOCK!
but bodies which are a TEXT! of code that will run in JavaScript.
While the question of how to extract the arguments from such functions
is open, this adds a special `rebArg()` function for the purpose.
=> Preliminary implementation of JS-NATIVE

src/boot/sysobj.r, src/core/n-loop.c, tests/control/remove-each.test.reb
This changes both MAP-EACH and REMOVE-EACH to fall in line with the
convention of returning NULL if a BREAK is encountered, and dropping
the in-progress partial operation:
>> map-each x [1 2 3 4] [
if x = 3 [break]
x + 10
]
;-- null (would have historically been [11 12])
Now if an in-progress mapping wants to keep partial results, it would
need to do so manually by rejecting subsequent map items:
>> skipping: false
>> map-each x [1 2 3 4] [
if skipping [continue]
if x = 3 [skipping: true | continue]
x + 10
]
== [11 12]
*This is for a reason*:
The ability to be able to tell from outside a loop whether it had a
break or not is very important in building composite loop operations.
For instance, imagine a MAP-BOTH which took two MAP-EACH operations and
wanted to run them in sequence for two …
=> MAP-EACH/REMOVE-EACH return NULL on BREAK, no BREAK/WITH

src/boot/errors.r, src/core/c-error.c, src/core/c-eval.c, src/core/n-data.c, src/core/t-gob.c, src/extensions/ffi/t-struct.c
This restores the behavior from the initial development of null, which
allows it to unset variables:
>> x: 10
== 10
>> x: null
// null
>> x
** Script Error: x has no value
However, VOID! values (which unlike null *are* values and may appear in
arrays and can be accessed without a GET-WORD!) still cause errors:
>> x: do []
** Script Error: x: can't be VOID! (use TRY, OPT, or SET*)
>> x: print "hi"
hi
** Script Error: x: can't be VOID! (use TRY, OPT, or SET*)
Allowing null assignments to mean "unset" provides convenient means of
removing keys from maps, which [could be difficult otherwise](https://github.com/red/red/wiki/%5BNOTES%5D-Design-notes-on-removing-keys-from-MAP!-values):
>> m: make map! [1 a 2 b]
== make map! [
1 a
2 b
]
>> m/1: _
>> m
== make map! [
1 _
2 b
]
>> m/1: null
>> m
== …
=> Allow null to unset a SET-WORD! or SET-PATH!

make/tools/common-emitter.r, make/tools/common.r, make/tools/make-reb-lib.r, make/tools/r2r3-future.r, src/core/n-io.c, src/core/n-strings.c, src/core/s-mold.c, src/mezz/base-defs.r, tests/datatypes/error.test.reb, tests/datatypes/unset.test.reb, tests/functions/invisible.test.reb, tests/series/delimit.test.reb
This is a change which was contemplated for some time (as early as
the proposal for "COMBINE") which is to distinguish the situation of
a block-to-string conversion that entirely opts out by returning a
null to indicate opting out.
>> unspaced ["a" if false ["b"] "c"]
== "ac"
>> unspaced [if false ["a"] if false ["b"] if false ["c"]]
// null
Previously an empty string would be returned.  This can still be done
a number of ways, one of which is to provide any empty string as
input in the block:
>> unspaced ["" if false ["a"] if false ["b"] if false ["c"]]
== ""
But it can also be done with ELSE, UNLESS, or any other null-reactive
construct.  By doing it this way, empty string isn't the only option,
so for instance if you want to comply with the C standard for function
arguments you aren't …
=> DELIMIT (and UNSPACED, SPACED, etc.) null if all opt out

src/core/b-init.c, src/core/c-function.c, src/core/f-modify.c, src/include/sys-array.h, src/include/sys-globals.h, src/include/sys-rebfrm.h, src/mezz/mezz-series.r, tests/call/call.test.reb, tests/core-tests.r, tests/series/replace.test.reb
This modifies the behavior of the CHANGE function w.r.t. NULL when a
/PART refinement is used.
Previously, it would consider a NULL to signal a no-op...now it
considers it the absence of a replacement.  This makes it similar to
a /PART when splicing an empty array:
>> head change/part copy [a b c d] [] 2
== [c d]
>> head change/part copy [a b c d] null 2
== [c d]
This is applied for BINARY! and STRING! as well.  Since REPLACE is
a mezzanine based on CHANGE, this means it now can support a null
pattern (signaling a no-op) or a null replacement (meaning to just
vaporize any instances of the pattern)
[3 4] = replace copy [3 0 4] 0 null
[3 0 4] = replace copy [3 0 4] null 1020
[2 0 2 0] = replace/all copy [1 0 2 0 1 0 2 0] [1 0] null
"34" = replace copy "304" "0" null
"304" = rplace copy …
=> REPLACE allows null to opt out of pattern or replacement

src/core/n-loop.c, tests/control/continue.test.reb, tests/control/remove-each.test.reb
Ren-C initially introduced the idea of a /WITH parameter to CONTINUE,
so that a CONTINUE operation would be able to make it seem as if that
iteration of the body had returned a value.
However, since CONTINUE is at the tail of an operation, it's possible
to take advantage of that by having it be able to act as arity-0 or
arity-1 depending on the presence of an argument:
>> map-each x [1 2000 3000] [
if x > 1000 [continue]
x + 1
]
== [2]
>> map-each x [1 2000 3000] [
if x > 1000 [continue <big>]
x + 1
]
== [2 <big> <big>]
This parallels the behavior of RETURN, which allowed to repurpose the
EXIT command.
=> Make CONTINUE "endable"

src/core/n-loop.c, src/mezz/mezz-legacy.r, tests/atronix/test-libs.r, tests/control/forever.test.reb
The FOREVER construct seemed on the surface as a more efficient and
more fluent way to write `while [true]`.  But its name is long-ish, and
actually rather jarring for casual use of "loop until some condition
sensed within the loop causes a break".  That is not sensibly called
"forever"--so it didn't really seem to get used much at all.
CYCLE is a shorter name, without that baggage.  "Keep cycling until
something stops the cycle".
It also adds a distinct feature of STOPping cycles with a result value.
While loops aren't allowed to "return a value from a break", that's
because they need to distinguish a stopping request from normal
completion.  However, *CYCLE has no normal loop termination condition*.
It isn't counting anything, or testing anything.  So its return result
would go somewhat …
=> Rethink FOREVER construct as CYCLE, add STOP ability

make/tools/common-parsers.r, scripts/redbol.reb, src/core/n-control.c, src/core/n-data.c, src/core/n-error.c, src/core/n-loop.c, src/extensions/ffi/ext-ffi-init.reb, src/extensions/process/ext-process-init.reb, src/include/sys-frame.h, src/mezz/base-files.r, src/mezz/base-funcs.r, src/mezz/prot-http.r, src/mezz/sys-base.r, src/mezz/sys-ports.r, src/os/encap.reb, src/os/host-console.r, src/os/host-start.r, src/os/unzip.reb, tests/control/attempt.test.reb, tests/control/catch.test.reb, tests/control/reduce.test.reb, tests/control/try.test.reb, tests/control/while.test.reb, tests/datatypes/error.test.reb, tests/datatypes/function.test.reb, tests/misc/gtk.r, tests/system/gc.test.reb, tests/test-parsing.r
R3-Alpha's error-trapping function (TRY) could take a handler--which
could be a block or a single-arity function--for handling the case
when an error was raised.  If no handler was provided, it would
return the error value...but this would be mixed up with the possible
return value of the expression evaluated itself.
This rethinks TRAP to return NULL if there is no failure.  That means
it doesn't need to interact with handlers, you can use THEN and ELSE.
This does make it a little harder to get a return value from the
expression, but many expressions written as:
foo: trap [...]
Can be rewritten as:
trap [... foo: ...]
=> Change TRAP to return NULL on no failure

src/core/n-loop.c, tests/control/for-each.test.reb
This allows the enumeration of arbitrarily large amounts of data
without needing the values generated into a block ahead of time.  A
function is called instead--which returns any value.  Once it returns
NULL, then that is taken to be the end.
>> make-one-thru-five: function [<static> count (0)] [
if count = 5 [return null]
return count: count + 1
]
>> for-each i :make-one-thru-five [-- i]
-- i: 1
-- i: 2
-- i: 3
-- i: 4
-- i: 5
It's designed to work with multiple items at a time, as with the other
enumerations.  If at least some of the variables can be set they
will, with the others being unset:
>> for-each [a b] :make-one-thru-five [-- a b]
-- a: 1
-- b: 2
-- a: 3
-- b: 4
-- a: 5
-- b: // null
Implementing this required some cleanup to the Loop_Each() internal C
function, which was …
=> Allow ACTION! as data source for FOR-EACH, MAP-EACH, etc.

src/extensions/process/mod-process.c
Signed-off-by: Stéphane Aulery <lkppo@free.fr>
=> Like OSX, OpenBSD need an explicit declaration of "environ" variable

scripts/redbol.reb, src/core/c-eval.c, src/core/n-control.c, src/core/n-data.c, src/core/u-parse.c, src/extensions/console/ext-console-init.reb, src/extensions/ffi/ext-ffi-init.reb, src/include/sys-do.h, src/include/sys-eval.h, src/include/sys-rebfrm.h, src/mezz/base-files.r, src/mezz/base-funcs.r, src/mezz/base-infix.r, src/mezz/mezz-dump.r, src/mezz/mezz-help.r, src/os/encap.reb, src/os/host-start.r, tests/control/else.test.reb, tests/control/try.test.reb, tests/convert/load.test.reb, tests/convert/mold.test.reb, tests/datatypes/path.test.reb, tests/datatypes/quoted.test.reb, tests/misc/help.test.reb, tests/test-framework.r, tests/test-parsing.r
R3-Alpha only evaluated one left-hand side element for infix operators.
Ren-C needed to allow for more evaluation in order to implement various
ideas like ELSE:
if condition [...] else [...]
The ELSE required some verdict from IF about whether the condition was
true and the branch ran or not.  But if it were limited to only seeing
one block on the left, it couldn't learn anything from the IF.
Argument conventions for the left enfix were decided to be NORMAL,
TIGHT, SOFT QUOTED, and HARD QUOTED.  The only one of these conventions
obeyed by R3-Alpha for infix "OP!s" was the one called TIGHT...which
took one unit of value cell and evaluated it (something like a hard
quoted operator that ran one unit of evaluation).  The question arose
as to how much more evaluation than that a NORMAL …
=> Restore "One Expression" Left Normal Enfix Rule

make/tools/make-boot.r, src/boot/errors.r, src/core/c-error.c, src/core/c-function.c, src/core/m-stacks.c, src/core/n-function.c, src/core/t-typeset.c, src/include/sys-value.h, tests/core-tests.r, tests/functions/redescribe.test.reb
This is a proof of concept for changing the parameter conventions of
functions.  Right now all it allows is to change the return type to
return any value:
returns-int: func [return: [integer!] x] [x * 10]
returns-text: enclose 'returns-int func [f] [
f/x: f/x + 1
to text! do f
]
>> returns-text 10
** Script Error: returns-text doesn't have RETURN: enabled for text!
>> skin: reskinned [return: [<opt> any-value!]] :returns-text 
>> skin 10
== 10
But it only does *exactly that*.  So the question is how this fits in
with REDESCRIBE; what does the native do, what does the usermode code
do, and how they fit together.  This is to start that conversation,
based on what can be done that gets @giuliolunati the most leverage
in the near term.
=> Beginning of a RESKIN technique for parameter conventions

src/boot/words.r, src/core/u-parse.c, src/include/sys-roots.h, tests/parse-tests.r
(Note: This is not particularly well tested, and is being committed
due to community demand...where it is expected that the community
will invest in making the tests for it!  Expect bugs, but the gist
seems to work.)
This implements COLLECT and KEEP keywords in PARSE.  They are justified
as features tailored to parse specifically because it is desirable
to have rule failures back out kept items.  For instance, with the
following code:
parse [1 2 3] [
collect x [
keep integer! keep integer! keep text!
|
keep integer! keep [some integer!]
]
]
Without backtracking, this would give x as [1 2 1 2 3], when the likely
intended result was [1 2 3].
In addition to providing the backtracking (that Red did not with its
COLLECT), this changes it to take a variable to set, which is more
like SET and …
=> COLLECT and KEEP in PARSE (with backtracking)

make/tools/bootstrap-shim.r, make/tools/common-emitter.r, make/tools/make-boot.r, make/tools/make-reb-lib.r, make/tools/native-emitters.r, make/tools/prep-extension.r, scripts/redbol.reb, src/extensions/console/ext-console-init.reb, src/mezz/base-series.r, src/mezz/mezz-help.r, src/mezz/mezz-series.r, tests/datatypes/varargs.test.reb
It is technically desirable for COLLECT to be built on a null-returning
foundation.  It has better performance and memory use characteristics
to not allocate a series node and array memory block if it is not
needed.  Additionally, many clients can benefit from discerning a
"nothing was collected" case, and being null means the result is both
logically false and able to trigger reactions from THEN/ELSE/ALSO.
However, the block form is also useful.  It is also arguable that the
distinct result of "nothing collected" may be usefully discerned from
having a blank input to the collect, to chain out a NULL.
In the balance of both having advantages, this errs on the side of
compatibility (and @rgchris's preference) to give the empty-block
returning COLLECT the primary name--while still building …
=> Return COLLECT to empty block default, chains on COLLECT*

make/tools/bootstrap-shim.r, make/tools/rebmake.r, scripts/changes-file/changes-file.reb, src/extensions/process/call-posix.c, src/extensions/process/call-windows.c, src/extensions/process/ext-process-init.reb, src/extensions/process/mod-process.c, src/mezz/mezz-control.r, tests/call/call.test.reb
R3-Alpha had a very primitive call, with /WAIT as the only refinement.
Atronix updated this to add the input/output/error features for
redirection on Windows and POSIX, but preserved the /WAIT behavior,
which seems to run counter to Rebol's ease of use defaults.
Several oddities of the difference between Windows and POSIX--as well
as the differentiation between direct process execution and shell
execution--leaked through in the implementation to where a seemingly
simple idea like `call {my.exe an-arg}` was not running it in the way
one would expect.  For a summary of the reasons that convenience was
not favored, see these notes:
https://github.com/rebol/rebol-issues/issues/2225
This commit is a reimagination that tries to "fix all the problems":
* Text strings passed are parsed and …
=> Large number of usability improvements to CALL

make/configs/emscripten.r
I updated the quoting so that emcc won't crash on Windows when building Emscripten. This update has been tested on both Linux and Windows, and it works on both.
=> Fixed a quoting issue with emcc on Windows

.travis.yml, make/configs/emscripten.r, make/configs/emterpreter.r, make/default-config.r, make/make.r, make/tools/systems.r
build emterpreted asm.js code and add to Travis
it sets some words, then chains* to configs/emscripten.r
* new mechanism to "chain" configs files:
put in a `config: NEXT-CONFIG-FILE` line
So you can build a tree of config files.
=> Add configs/emterpreter.r + chain config files

src/core/u-parse.c, src/mezz/mezz-series.r, tests/parse-tests.r
PARSE's COPY command was changed between Rebol2 and R3-Alpha to
preserve the BINARY!/string distinction.  Previously a parsed binary
would come back as a string:
rebol2>> parse #{42434445} [copy x to end]
== true
rebol2>> x
== "BCDE"
This was changed--but beyond changing just this case, it was assumed
that the returned type from COPY should match the type of the input.
This meant that copying a fragment out of a URL! would give a URL!
(for instance) even though it was not well-formed.
r3-alpha>> parse http://example.com ["http://" thru "." copy x to end]
== true
r3-alpha>> x
== com
r3-alpha>> type? x
== url!
Other awkward situations arose for copying pieces out of PATH!, which
are now considered illegal in Ren-C due to path immutability and
making them follow specific rules (they are not …
=> Make PARSE COPY give just BLOCK!/GROUP!/TEXT!/BINARY!

make/tools/make-reb-lib.r, src/extensions/javascript/mod-javascript.c
This adds the ability to use the JavaScript AWAIT statement in a
JS-AWAITER.  It does so by labeling those functions `async`.
These functions were previously not expected to return a value, rather
to (eventually) call one of the resolve() or reject() functions passed
to them as implicit parameters.  With this change, they will return
an ES6 Promise.  If AWAIT is called then that promise will not be
in a fulfilled state when the promise is returned, and it must be
waited on.
=> Make it possible to AWAIT in JS-AWAITER

extensions/javascript/mod-javascript.c, extensions/javascript/prep-libr3-js.reb
The first hack for implementing a string eval in the JavaScript
extension was to create a one-off JS-NATIVE whose body was the string
(but took no arguments), and call it once.  That was terribly
inefficient, but took care of the concerns of moving the code to the
appropriate thread.
That did not allow for global evaluation, however...since proxying code
to a main thread always involved running inside a function.  And it
seemed that if you called eval() from in a function you could not add
global variables as `var x = ...` (you'd have to say `window.x = ...`)
But since code existed for JS-DO'ing URLs, that code for using a
`<script>` tag was adapted to add a script tag and await on notice of
that script tag finishing.  This was also terribly inefficient.
This commit solves both of those …
=> Faster generic JS-EVAL* low-level evaluation native

src/boot/words.r, src/core/c-bind.c, src/core/c-function.c, src/core/c-specialize.c, src/core/n-function.c, tests/core-tests.r, tests/functions/let.test.reb
R3-Alpha introduced the idea of a "FUNCT", which would notice when a
SET-WORD! was used in a function body that was not one of the arguments
or locals in the spec.  It would then automatically "gather" these and
add them as locals in the spec.
This was much more convenient than having to maintain by hand a list
of the locals in the spec, which might get out of date as the body was
edited.  The convenience was such that this concept took the name
FUNCTION away from it former use (as a slight variant of FUNC which
let you separate the locals into their own parameter block).
However, the idea of auto-gathered locals based on SET-WORD! runs into
several problems in Rebol--as SET-WORD!s are used for many purposes
besides local variables.  Function frames became inflated with stray
variables …
=> Clunky first implementation of LET in FUNC/FUNCTION

extensions/crypt/easy-ecc/LICENSE.txt, extensions/crypt/easy-ecc/README.md, extensions/crypt/easy-ecc/ecc.c, extensions/crypt/easy-ecc/ecc.h, extensions/crypt/make-spec.r, extensions/crypt/mod-crypt.c, scripts/prot-tls.r
This PR brings in new C natives for implementing the cryptography math behind the elliptic curve `secp256r1`, which is popularly used in TLS handshakes today.  *(Notably the Discourse installation via Docker--as used on [`forum.rebol.info`](http://forum.rebol.info) is by default not willing to connect to anything not using this form of cryptography.)*
The math comes from a small C implementation of secp256r1 from the "easy-ecc" project:
https://github.com/esxgx/easy-ecc
This PR also adapts the %prot-tls.r file to be able to participate in the ECDHE protocol.  In TLS 1.2 this is a kind of sub-negotiation that was slipstreamed by means of "extensions" (e.g. agreeing on a cipher suite that has ECHDE in it is not the end of the negotiation process, as that identifies a family of processes …
=> Ephemeral Elliptic Curve Crypto for TLS (secp256r1)

extensions/filesystem/file-posix.c, extensions/filesystem/file-windows.c, scripts/prot-http.r, src/boot/errors.r, src/core/l-scan.c, src/core/l-types.c, src/core/n-data.c, src/core/n-strings.c, src/core/s-make.c, src/core/t-string.c, src/include/datatypes/sys-char.h, src/include/datatypes/sys-string.h, src/include/reb-defs.h, src/mezz/mezz-save.r, src/mezz/mezz-types.r, tests/series/copy.test.reb, tests/series/emptyq.test.reb, tests/string/deline.test.reb, tools/bootstrap-shim.r, tools/make-headers.r, tools/make-natives.r, tools/prep-extension.r
This commit tries to build on Rebol's historical concept of unifying
strings within the system to use LF-only.  But rather than try "magic"
to filter out CR LF sequences (and "magically" put them back later), it
adds in speedbumps to try and stop CR from casually getting into
strings.  Then it encourages active involvement at the source level
with functions like ENLINE and DELINE when a circumstance can't be
solved by standardizing the data sources themselves:
https://forum.rebol.info/t/1264
It also revises Ren-C's rules to be  prescriptive about disallowing 0
bytes in strings, to more safely use the rebSpell() API, which only
returns a pointer and must interoperate with C.  It enforces the use of
BINARY! if you want to embed 0 bytes (and using the rebBytes() API,
which always returns a …
=> Revise Ren-C's rules for CR and 0 bytes in strings

extensions/serial/ext-serial-init.reb, scripts/encap.reb, scripts/prot-http.r, scripts/prot-tls.r, scripts/unzip.reb, src/boot/sysobj.r, src/core/t-binary.c, src/core/t-integer.c, src/include/sys-core.h, src/mezz/mezz-legacy.r, src/mezz/mezz-types.r, src/mezz/sys-ports.r, tests/convert/enbin.test.reb, tests/core-tests.r
Rebol2 had an asymmetrical sense of conversion for BINARY! and INTEGER!
rebol2>> to binary! 32
== #{3332}  ; #{33} is ASCII "3", #{32} is ASCII "2"
rebol2>> to integer! #{3332}
== 13106  ; 0x3332 is the internal big endian form of 13106
R3-Alpha "corrected" this unusual behavior by changing TO BINARY!.  The
conventional wisdom seemed to be that `TO BINARY! TO STRING! 32` was
not a common desire, but easy enough to express if you wanted it.  The
harder conversion for users (which was "easy" for Rebol to do) involved
the internal byte representations of native C integers:
r3-alpha>> to binary! 32
== #{0000000000000020}  ; 0x20 is 32 in hexadecimal
r3-alpha>> to integer! #{0000000000000020}
== 32
While this might seem more sensible on the surface, it was awkward for
users to get the INTEGER! …
=> ENBIN + DEBIN draft/sketch implementation

extensions/console/ext-console-init.reb, extensions/javascript/prep-libr3-js.reb, extensions/uuid/make-libuuid.reb, scripts/changes-file/changes-file.reb, scripts/prot-http.r, scripts/unzip.reb, src/core/s-mold.c, src/mezz/base-defs.r, src/mezz/mezz-help.r, src/mezz/mezz-save.r, tests/misc/shttpd.r, tests/red/run-red-test.reb, tests/series/delimit.test.reb, tests/system/gc.test.reb, tools/native-emitters.r
This embraces the concept of "what space is to strings, BLANK! is to
blocks", by taking that notion forward to let a BLANK! be rendered
as a space character:
>> unspaced ["a" "b" _ "c"]
== "ab c"
Having a shorthand notation for a space improves visibility while
saving on characters (over typing `space` out as a word):
>> unspaced ["x:" space first block space "+ 10"]
vs.
>> unspaced ["x:" _ first block _ "+ 10"]
It also can be preferable to tacking spaces in with adjoining string
parts (in cases where that is possible).  Because they are the same
character in the language used to separate values themselves.  This
makes it sometimes hard to see where a string beginning or end is:
>> unspaced ["x: " first block " + 10"]
; ...at a glance, `" first block "` might look like a string
; vs.
>> …
=> BLANK! as space character in DELIMIT/UNSPACED/SPACED

src/core/c-error.c, src/core/l-scan.c, src/core/u-parse.c, src/include/sys-feed.h, src/include/sys-scan.h, src/main/main.c, src/mezz/sys-load.r, tests/convert/load.test.reb, tests/core-tests.r, tests/string/transcode.test.reb, tests/system/gc.test.reb, tests/test-framework.r, tests/test-parsing.r, tools/bootstrap-shim.r, tools/common-parsers.r
Much of LOAD was written in userspace and built on top of TRANSCODE.
In R3-Alpha, this meant the scanner was limited in what it could
report for errors...it was receiving strings and knew what line on
the string it was on, but did not know the filename to report any
errors on.  Also, it only knew the line offset within the string...
so when headers were scanned separately the line numbers were off
by the number of lines in the header.
Ren-C had tunneled in a line number variable to TRANSCODE to resolve
the line number issue.  However, the filename was not threaded through
the loading machinery...which was difficult to navigate and read.
This commit attempts to get to the bottom of the issue by making LOAD
account for the filename.  As part of the process, this involves
improving LOAD and …
=> TRANSCODE redesign with multi-return, error improvements

src/core/n-reduce.c, src/core/s-mold.c, src/core/u-parse.c, src/mezz/mezz-series.r, tests/context/set.test.reb, tests/control/reduce.test.reb, tests/functions/modal.test.reb, tests/functions/specialize.test.reb, tests/misc/assert.test.reb, tests/parse/parse.test.reb, tests/series/delimit.test.reb
This tweaks the handling of BLANK! to allow it to be used at "source
level" in dialects, while prescribing it as a synonym for NULL if
it is fetched from evaluation or a variable.
Being able to discern a "source" blank from a fetched one is thus
important, and the previous commit's tweak is used to move in steps
that allow blanks after comments to be discerned as source or not:
>> spaced ["a" _ comment <b> _ "c"]
== "a  c"
>> spaced ["a" blank comment <b> blank "c"]
== "a c"   ; acts as if you'd written `spaced ["a" "c"]`
DELIMIT is also modified to use tight spacing for ISSUE!, which is
an aspect of the transition to a merged ISSUE!/CHAR! datatype.  This
integrates well with the source-level spacing feature, for clear
results that don't require mixing SPACED and UNSPACED calls, and
thus …
=> Tune DELIMIT and PARSE handling of BLANK!, ISSUE!

src/core/l-scan.c, src/core/n-strings.c, src/include/sys-scan.h, tests/core-tests.r, tests/datatypes/issue.test.reb, tests/scanner/source-comment.test.reb
Historically, Rebol allowed semicolons to abut directly against
other tokens in order to start a comment:
rebol2>> load "a;b"
== a
This was relaxed in Ren-C for URL!, given that semicolon is a valid
character in urls:
>> load "http://example.com/a;b.html"
== http://example.com/a;b.html
With the introduction of ISSUE!, there is now another type that could
benefit from allowing semicolons that are not "spaced out" to merge
into the token itself:
>> if #; = second "a;b" [print "Convenient."]
Convenient.
However, a policy of "sometimes merging with the token and sometimes
not" seems shaky.
Given the overall theme of space significance in the lexical model,
this makes the shift to where semicolons are only considered comments
when they are spaced out.  Token types that don't accept semicolon …
=> Require space before `;` is considered a comment

src/core/c-function.c, src/core/functionals/c-adapt.c, src/core/functionals/n-function.c, src/core/n-do.c, src/include/datatypes/sys-frame.h, src/include/sys-throw.h, src/mezz/mezz-dump.r, tests/functions/invisible.test.reb, tests/scanner/source-comment.test.reb
This makes invisibility a return state that a function can have...but
it can decide that while it is running.  (Previously a function could
be either fully invisible or not at all invisible, based on the
return spec being `return: []` or not.)
Returning invisibly is done by providing the return value via code
to run inside of a @(...) hence just returning invisibly an be done
as easily as @():
>> foo: func [x] [print [x] return @()]
>> <before> foo 10
10
== <before>
The likely-temporary way to indicate that invisibility is one of the
return options in a spec is by saying `<invisible>`:
>> vanish-if-odd: func [return: [<invisible> integer!] x] [
if even? x [return x]
return @()
]
>> <test> vanish-if-odd 2
== 2
>> <test> vanish-if-odd 1
== <test>
The benefit of having the form for …
=> Functions can be invisible sometimes, vs always

extensions/console/ext-console-init.reb, scripts/prot-tls.r, src/core/d-gc.c, src/core/evaluator/c-action.c, src/core/evaluator/c-eval.c, src/core/functionals/n-function.c, src/core/n-control.c, src/core/n-data.c, src/core/n-error.c, src/core/n-loop.c, src/include/datatypes/sys-nulled.h, src/include/datatypes/sys-void.h, src/include/sys-do.h, src/mezz/base-constants.r, src/mezz/base-defs.r, src/mezz/mezz-help.r, src/mezz/mezz-series.r, tests/control/all.test.reb, tests/control/any.test.reb, tests/control/either.test.reb, tests/control/every.test.reb, tests/control/if.test.reb, tests/control/loop.test.reb, tests/control/reduce.test.reb, tests/control/while.test.reb, tests/datatypes/null.test.reb, tests/datatypes/void.test.reb, tests/functions/oneshot.test.reb
Historically there has been a struggle over the potential conflation of
NULL as a special signal ("no branch ran", "loop encountered a BREAK")
and "branch/body evaluated to null".
The "simple" technique used to help distinguish these cases was to
reserve NULL for the signal, and mutate any branch or body result to
a VOID! value so it would not collide:
>> if false [<whatever>]
; null
>> if true [null]
== ~branched~
This was known as voidification, and it successfully avoided the
behavior of inadvertently running a branch along with an ELSE clause:
>> if true [print "branch", null] else [print "this shouldn't run"]
branch
== ~branched~
However, it caused collateral damage to the return result.  The
answer given for users who did not want voidification applied was to
mark branches "as-is" …
=> NULL Isotopes (The End of Voidfication!)

extensions/crypt/mod-crypt.c, src/core/c-bind.c, src/core/c-function.c, src/core/functionals/c-does.c, src/core/functionals/c-reskin.c, src/core/l-types.c, src/core/n-control.c, src/core/n-do.c, src/core/n-loop.c, src/core/n-reduce.c, src/core/t-quoted.c, src/core/t-varargs.c, src/include/datatypes/sys-typeset.h, src/mezz/base-defs.r, src/mezz/base-funcs.r, tests/datatypes/varargs.test.reb, tests/functions/enfix.test.reb, tests/functions/function.test.reb, tools/bootstrap-shim.r, tools/common-emitter.r
In function specs, Rebol2 used :FOO to mean "pass value at callsite
literally", while it used 'FOO to mean "pass value literally unless it
is a GET-WORD! or a GET-PATH!, in which case GET it".
R3-Alpha moved this to where 'FOO also would evaluate GROUP!s.
Ren-C has GET-GROUP!, so it completed the escaping pattern as GET-WORD!
plus GET-PATH! plus GET-GROUP!, returning GROUP!s to being quoted
normally for the escapable kind.
This commit makes another adjustment...which is to flip it.  It makes
more sense for the single quote tick to mean always use parameter
as is (as if it had been quoted at the callsite).  Then the form
with a colon logically lines up for meaning that if the callsite
matches the GET-XXX! pattern, then it will be escaped.
=> Swap parameter meanings of 'FOO and :FOO

scripts/uparse.reb, tests/parse/uparse.test.reb
The combinator-based approach to parsing breaks each parse keyword or
datatype behavior out into a "parser function".
This is a simple implementation of COLLECT and KEEP combinators that
collaborate with the BLOCK! combinator to do rollback.  It would be
preferable to have some kind of "generic rollback facility", but this
is more or less what the C code was doing to implement the feature.
The PARSE as a whole maintains a block that it collects, and marks the
high-water point on each block recursion...so that if an alternate
fails it just drops the mark down.
=> Simplistic combinator-based COLLECT+KEEP in UPARSE

extensions/uuid/make-libuuid.reb, scripts/encap.reb, scripts/unzip.reb, src/core/u-parse.c, src/mezz/base-files.r, src/mezz/base-funcs.r, src/mezz/base-series.r, src/mezz/mezz-series.r, tests/comparison/sameq.test.reb, tests/comparison/strict-equalq.test.reb, tests/context/virtual-bind.test.reb, tests/parse/parse.test.reb, tests/source/source-tools.reb, tests/test-parsing.r, tools/common-parsers.r, tools/parsing-tools.reb, tools/text-lines.reb
This is a small step toward broadening the applications of SET-WORD!
and GET-WORD! in the parse dialect.  The idea is that SET-WORD! will
be used for capturing more than just parse positions, so the general
purpose HERE rule can be used in the case that the parse position is
what you want.
If you use a lone SET-WORD! without HERE after it, the near-term
behavior for that will be to raise an error at the offending location.
So long as you are updating, consider how commas might make the
rules more readable, e.g.
pos: any [integer! | text!]
=>
pos: here, any [integer! | text!]
That case is a good example showing the immediate readability benefits
the change brings.  What it ultimately is intended for--however--is
to broaden the application of SET-WORD! in the dialect as a whole.
The …
=> Save parse position with POS: HERE, seek with SEEK POS

.github/workflows/android-build.yml, configs/android-common.r
There does not appear to be a standard for the name of an environment
variable where the NDK is installed.  Some code on the internet seems
to use $NDK, while the original Ren-C Android build scripts assumed the
name was $ANDROID_NDK
With multiple environment variables in play, it's not clear what this
represents...it could be the version, or whether to install it or not.
So it had been changed to ANDROID_NDK_DIR to be more communicative.
However, when trying out the emulator in the android SDK (Java+tools)
it turns out there is a standard for that: ANDROID_SDK_ROOT
This would make the best choice appear to be ANDROID_NDK_ROOT as it
communicates that it is a directory and lines up with what the
binaries in the SDK look for in its variable.
=> Change NDK variable to ANDROID_NDK_ROOT

extensions/filesystem/libuv/src/unix/fs.c, extensions/filesystem/make-spec.r, extensions/process/call-posix.c, extensions/process/mod-process.c, extensions/process/process-posix.c, extensions/uuid/libuuid/randutils.c, extensions/uuid/make-spec.r, extensions/uuid/mod-uuid.c, make.r, src/include/reb-c.h, src/include/reb-config.h, src/include/sys-zlib.h, tools/rebmake.r, tools/systems.r
Here are the changes I made to build on Haiku-x64.
Review carefully because my Rebol-fu is quite rusty.
Some changes are questionable (like stat()ing for each entry, but I didn't find any other way on Haiku) and could be considered misplaced (the stat() kludge probably belongs in libuv, but I didn't figure out how to access the directory descriptor).
I also had to change the make.r/rebmake.r stuff, generating makefiles didn't work for me.
=> Haiku-x64 port

src/mezz/mezz-help.r
I was playing around with the interpreter built from master and noticed `source` wasn't working correctly, where it was trying to apply/eval the `frame!` objects it was retrieving from the environment. Seems the code wasn't updated for the new evaluation semantics of `frame!`s, so I added the appropriate get-word forms and wrapped the actual frame in `unrun` so `frame?` works as intended. It now prints source code again.
=> %src/mezz/mezz-help.r fix unintended application forms in source
